/**
 * Power + Cases catalog helpers and product definitions.
 * Sample prices — owner re-verifies on apple.com / admin before launch.
 */
import { accessoriesManifest } from "./manifest";
import { accessoryBasePricesKes } from "./config";
import type { Accessory, FitResult } from "./models";
import { accessories, getAccessory } from "./models";

export type CaseVariant = {
  partNumber: string;
  colour: string;
  mainImage: string;
  swatchImage: string | null;
  angleImages: string[];
};

export type CaseVariantFamily = {
  id: string;
  folder: string;
  group: string;
  variants: CaseVariant[];
  colourCount: number;
  leadPartNumber: string;
};

function a(
  partial: Omit<Accessory, "basePriceKes"> & { id: keyof typeof accessoryBasePricesKes },
): Accessory {
  return { ...partial, basePriceKes: accessoryBasePricesKes[partial.id] };
}

export const powerCaseProducts: Accessory[] = [
  a({
    id: "power-adapter-20w",
    name: "20W USB-C Power Adapter",
    group: "power",
    generation: "20W",
    year: 2024,
    partNumber: "MWVV3",
    colours: ["white"],
    defaultColour: "white",
    connection: "USB-C",
    charging: "20W class",
    features: ["20W USB-C","Compact brick","Pairs with USB-C charge cable"],
    featureIds: ["20w-usb-c","compact-brick","pairs-with-usb-c-charge-cable"],
    weightG: null,
    tagline: "Everyday phone and small tablet charge.",
    whoItSuits: "iPhone, AirPods, small USB-C devices.",
    whyChoose: ["20W USB-C", "Match wattage to your device — higher is fine, lower may slow charge.", "Check final specs on Apple's list."] as [string, string, string],
    platform: "both",
    checkFinalSpecs: true,
    notes: "20W USB-C Power Adapter — check Apple's list for your device.",
    imageProductKey: "power-adapter-20w",
    connector: "usb-c",
    stocked: true,
    geoUs: false,
    wattage: 20,
    powerKind: "adapter",
  }),
  a({
    id: "power-adapter-35w-dual",
    name: "35W Dual USB-C Compact Power Adapter",
    group: "power",
    generation: "35W",
    year: 2024,
    partNumber: "MW2H3",
    colours: ["white"],
    defaultColour: "white",
    connection: "Dual USB-C",
    charging: "35W class",
    features: ["35W total","Two USB-C ports","Travel compact"],
    featureIds: ["35w-total","two-usb-c-ports","travel-compact"],
    weightG: null,
    tagline: "Two ports in one brick.",
    whoItSuits: "Phone plus Watch or earbuds on the go.",
    whyChoose: ["35W total", "Match wattage to your device — higher is fine, lower may slow charge.", "Check final specs on Apple's list."] as [string, string, string],
    platform: "both",
    checkFinalSpecs: true,
    notes: "35W Dual USB-C Compact Power Adapter — check Apple's list for your device.",
    imageProductKey: "power-adapter-35w-dual",
    connector: "usb-c",
    stocked: true,
    geoUs: false,
    wattage: 35,
    powerKind: "adapter",
  }),
  a({
    id: "power-adapter-40w-dynamic",
    name: "40W Dynamic Power Adapter",
    group: "power",
    generation: "40W",
    year: 2024,
    partNumber: "MGKN4",
    colours: ["white"],
    defaultColour: "white",
    connection: "USB-C",
    charging: "40W class",
    features: ["40W rated","Dynamic power","USB-C"],
    featureIds: ["40w-rated","dynamic-power","usb-c"],
    weightG: null,
    tagline: "Dynamic power with higher peak when one port leads.",
    whoItSuits: "Mixed USB-C charging when one device needs more.",
    whyChoose: ["40W rated", "Match wattage to your device — higher is fine, lower may slow charge.", "Check final specs on Apple's list."] as [string, string, string],
    platform: "both",
    checkFinalSpecs: true,
    notes: "40W Dynamic Power Adapter — check Apple's list for your device.",
    imageProductKey: "power-adapter-40w-dynamic",
    connector: "usb-c",
    stocked: true,
    geoUs: false,
    wattage: 40,
    powerKind: "adapter",
  }),
  a({
    id: "power-adapter-70w",
    name: "70W USB-C Power Adapter",
    group: "power",
    generation: "70W",
    year: 2024,
    partNumber: "MQLN3",
    colours: ["white"],
    defaultColour: "white",
    connection: "USB-C",
    charging: "70W class",
    features: ["70W USB-C","Mac daily driver","GEO_US plug shown"],
    featureIds: ["70w-usb-c","mac-daily-driver","geo-us-plug-shown"],
    weightG: null,
    tagline: "Daily MacBook Air and 14-inch Pro brick.",
    whoItSuits: "Most Air and 14 inch Pro owners.",
    whyChoose: ["70W USB-C", "Match wattage to your device — higher is fine, lower may slow charge.", "Check final specs on Apple's list."] as [string, string, string],
    platform: "both",
    checkFinalSpecs: true,
    notes: "70W USB-C Power Adapter — check Apple's list for your device.",
    imageProductKey: "power-adapter-70w",
    connector: "usb-c",
    stocked: true,
    geoUs: true,
    wattage: 70,
    powerKind: "adapter",
  }),
  a({
    id: "power-adapter-96w",
    name: "96W USB-C Power Adapter",
    group: "power",
    generation: "96W",
    year: 2024,
    partNumber: "MW2L3",
    colours: ["white"],
    defaultColour: "white",
    connection: "USB-C",
    charging: "96W class",
    features: ["96W USB-C","Higher headroom","GEO_US plug shown"],
    featureIds: ["96w-usb-c","higher-headroom","geo-us-plug-shown"],
    weightG: null,
    tagline: "Faster charge for higher-watt Macs.",
    whoItSuits: "MacBook Pro owners who want headroom.",
    whyChoose: ["96W USB-C", "Match wattage to your device — higher is fine, lower may slow charge.", "Check final specs on Apple's list."] as [string, string, string],
    platform: "both",
    checkFinalSpecs: true,
    notes: "96W USB-C Power Adapter — check Apple's list for your device.",
    imageProductKey: "power-adapter-96w",
    connector: "usb-c",
    stocked: true,
    geoUs: true,
    wattage: 96,
    powerKind: "adapter",
  }),
  a({
    id: "power-adapter-140w",
    name: "140W USB-C Power Adapter",
    group: "power",
    generation: "140W",
    year: 2024,
    partNumber: "MW2M3",
    colours: ["white"],
    defaultColour: "white",
    connection: "USB-C",
    charging: "140W class",
    features: ["140W USB-C","Pro laptop class","Needs high-watt cable"],
    featureIds: ["140w-usb-c","pro-laptop-class","needs-high-watt-cable"],
    weightG: null,
    tagline: "Full power for 16-inch class MacBooks.",
    whoItSuits: "Highest-watt MacBook Pro charging.",
    whyChoose: ["140W USB-C", "Match wattage to your device — higher is fine, lower may slow charge.", "Check final specs on Apple's list."] as [string, string, string],
    platform: "both",
    checkFinalSpecs: true,
    notes: "140W USB-C Power Adapter — check Apple's list for your device.",
    imageProductKey: "power-adapter-140w",
    connector: "usb-c",
    stocked: true,
    geoUs: false,
    wattage: 140,
    powerKind: "adapter",
  }),
  a({
    id: "power-extension-cable",
    name: "Power Adapter Extension Cable",
    group: "power",
    generation: "extension",
    year: 2024,
    partNumber: "MK122",
    colours: ["white"],
    defaultColour: "white",
    connection: "Apple power extension",
    charging: null,
    features: ["Extension cable","Pairs with Apple adapters"],
    featureIds: ["extension-cable","pairs-with-apple-adapters"],
    weightG: null,
    tagline: "Reach further from the wall.",
    whoItSuits: "Desk setups that need cable length.",
    whyChoose: ["Extension cable", "Official Apple accessory — sealed with serial on the invoice.", "Check final specs on Apple's list."] as [string, string, string],
    platform: "both",
    checkFinalSpecs: true,
    notes: "Power Adapter Extension Cable — check Apple's list for your device.",
    imageProductKey: "power-extension-cable",
    connector: "usb-c",
    stocked: true,
    geoUs: false,
    wattage: null,
    powerKind: "extension",
  }),
  a({
    id: "magsafe-charger-1m",
    name: "MagSafe Charger (1 m)",
    group: "power",
    generation: "magsafe",
    year: 2024,
    partNumber: "MGD74",
    colours: ["white"],
    defaultColour: "white",
    connection: "USB-C to MagSafe",
    charging: null,
    features: ["MagSafe snap","1 m cable","Needs USB-C adapter"],
    featureIds: ["magsafe-snap","1-m-cable","needs-usb-c-adapter"],
    weightG: null,
    tagline: "Snap charging for MagSafe iPhone.",
    whoItSuits: "Nightstand and desk MagSafe charge.",
    whyChoose: ["MagSafe snap", "Official Apple accessory — sealed with serial on the invoice.", "Check final specs on Apple's list."] as [string, string, string],
    platform: "both",
    checkFinalSpecs: true,
    notes: "MagSafe Charger (1 m) — check Apple's list for your device.",
    imageProductKey: "magsafe-charger-1m",
    connector: "usb-c",
    stocked: true,
    geoUs: false,
    wattage: null,
    powerKind: "magsafe",
  }),
  a({
    id: "magsafe-charger-2m",
    name: "MagSafe Charger (2 m)",
    group: "power",
    generation: "magsafe",
    year: 2024,
    partNumber: "MGDM4",
    colours: ["white"],
    defaultColour: "white",
    connection: "USB-C to MagSafe",
    charging: null,
    features: ["MagSafe snap","2 m cable","Needs USB-C adapter"],
    featureIds: ["magsafe-snap","2-m-cable","needs-usb-c-adapter"],
    weightG: null,
    tagline: "Extra length for MagSafe snap charge.",
    whoItSuits: "Sofa and floor reach.",
    whyChoose: ["MagSafe snap", "Official Apple accessory — sealed with serial on the invoice.", "Check final specs on Apple's list."] as [string, string, string],
    platform: "both",
    checkFinalSpecs: true,
    notes: "MagSafe Charger (2 m) — check Apple's list for your device.",
    imageProductKey: "magsafe-charger-2m",
    connector: "usb-c",
    stocked: true,
    geoUs: false,
    wattage: null,
    powerKind: "magsafe",
  }),
  a({
    id: "watch-magnetic-charger-1m",
    name: "Apple Watch Magnetic Fast Charger (USB-C, 1 m)",
    group: "power",
    generation: "watch",
    year: 2024,
    partNumber: "ML434",
    colours: ["white"],
    defaultColour: "white",
    connection: "USB-C magnetic Watch",
    charging: null,
    features: ["Watch magnetic","1 m","USB-C"],
    featureIds: ["watch-magnetic","1-m","usb-c"],
    weightG: null,
    tagline: "Magnetic fast charge for Apple Watch.",
    whoItSuits: "Watch owners on USB-C.",
    whyChoose: ["Watch magnetic", "Official Apple accessory — sealed with serial on the invoice.", "Check final specs on Apple's list."] as [string, string, string],
    platform: "both",
    checkFinalSpecs: true,
    notes: "Apple Watch Magnetic Fast Charger (USB-C, 1 m) — check Apple's list for your device.",
    imageProductKey: "watch-magnetic-charger-1m",
    connector: "usb-c",
    stocked: true,
    geoUs: false,
    wattage: null,
    powerKind: "watch",
  }),
  a({
    id: "cable-usbc-60w-1m",
    name: "60W USB-C Charge Cable (1 m)",
    group: "power",
    generation: "cable",
    year: 2024,
    partNumber: "MQKJ3",
    colours: ["white"],
    defaultColour: "white",
    connection: "USB-C to USB-C",
    charging: "60W class",
    features: ["60W","1 m","USB-C"],
    featureIds: ["60w","1-m","usb-c"],
    weightG: null,
    tagline: "Everyday USB-C charge cable.",
    whoItSuits: "Phone, tablet, and light laptop charge.",
    whyChoose: ["60W", "Pair with a matching adapter wattage.", "Check final specs on Apple's list."] as [string, string, string],
    platform: "both",
    checkFinalSpecs: true,
    notes: "60W USB-C Charge Cable (1 m) — check Apple's list for your device.",
    imageProductKey: "cable-usbc-60w-1m",
    connector: "usb-c",
    stocked: true,
    geoUs: false,
    wattage: 60,
    powerKind: "cable",
  }),
  a({
    id: "cable-usbc-240w-2m",
    name: "240W USB-C Charge Cable (2 m)",
    group: "power",
    generation: "cable",
    year: 2024,
    partNumber: "MU2G3",
    colours: ["white"],
    defaultColour: "white",
    connection: "USB-C to USB-C",
    charging: "240W class",
    features: ["240W","2 m","USB-C"],
    featureIds: ["240w","2-m","usb-c"],
    weightG: null,
    tagline: "High-watt USB-C charge cable.",
    whoItSuits: "High-power adapters and MacBooks.",
    whyChoose: ["240W", "Pair with a matching adapter wattage.", "Check final specs on Apple's list."] as [string, string, string],
    platform: "both",
    checkFinalSpecs: true,
    notes: "240W USB-C Charge Cable (2 m) — check Apple's list for your device.",
    imageProductKey: "cable-usbc-240w-2m",
    connector: "usb-c",
    stocked: true,
    geoUs: false,
    wattage: 240,
    powerKind: "cable",
  }),
  a({
    id: "cable-magsafe3-2m",
    name: "USB-C to MagSafe 3 Cable (2 m)",
    group: "power",
    generation: "cable",
    year: 2024,
    partNumber: "MLYV3",
    colours: ["white"],
    defaultColour: "white",
    connection: "USB-C to MagSafe 3",
    charging: null,
    features: ["MagSafe 3","2 m","Mac"],
    featureIds: ["magsafe-3","2-m","mac"],
    weightG: null,
    tagline: "MagSafe 3 snap charge for Mac.",
    whoItSuits: "MagSafe MacBooks.",
    whyChoose: ["MagSafe 3", "Pair with a matching adapter wattage.", "Check final specs on Apple's list."] as [string, string, string],
    platform: "both",
    checkFinalSpecs: true,
    notes: "USB-C to MagSafe 3 Cable (2 m) — check Apple's list for your device.",
    imageProductKey: "cable-magsafe3-2m",
    connector: "usb-c",
    stocked: true,
    geoUs: false,
    wattage: null,
    powerKind: "cable",
  }),
  a({
    id: "cable-tb4-1-8m",
    name: "Thunderbolt 4 (USB-C) Pro Cable (1.8 m)",
    group: "power",
    generation: "cable",
    year: 2024,
    partNumber: "MW5J3",
    colours: ["white"],
    defaultColour: "white",
    connection: "Thunderbolt 4",
    charging: null,
    features: ["Thunderbolt 4","1.8 m","Pro cable"],
    featureIds: ["thunderbolt-4","1-8-m","pro-cable"],
    weightG: null,
    tagline: "Data, video and charge over Thunderbolt 4.",
    whoItSuits: "Dock and display setups.",
    whyChoose: ["Thunderbolt 4", "Pair with a matching adapter wattage.", "Check final specs on Apple's list."] as [string, string, string],
    platform: "both",
    checkFinalSpecs: true,
    notes: "Thunderbolt 4 (USB-C) Pro Cable (1.8 m) — check Apple's list for your device.",
    imageProductKey: "cable-tb4-1-8m",
    connector: "usb-c",
    stocked: true,
    geoUs: false,
    wattage: null,
    powerKind: "cable",
  }),
  a({
    id: "cable-tb4-3m",
    name: "Thunderbolt 4 (USB-C) Pro Cable (3 m)",
    group: "power",
    generation: "cable",
    year: 2024,
    partNumber: "MWP02",
    colours: ["white"],
    defaultColour: "white",
    connection: "Thunderbolt 4",
    charging: null,
    features: ["Thunderbolt 4","3 m","Pro cable"],
    featureIds: ["thunderbolt-4","3-m","pro-cable"],
    weightG: null,
    tagline: "Longer Thunderbolt 4 Pro cable.",
    whoItSuits: "Room-crossing dock runs.",
    whyChoose: ["Thunderbolt 4", "Pair with a matching adapter wattage.", "Check final specs on Apple's list."] as [string, string, string],
    platform: "both",
    checkFinalSpecs: true,
    notes: "Thunderbolt 4 (USB-C) Pro Cable (3 m) — check Apple's list for your device.",
    imageProductKey: "cable-tb4-3m",
    connector: "usb-c",
    stocked: true,
    geoUs: false,
    wattage: null,
    powerKind: "cable",
  }),
  a({
    id: "cable-tb5-1m",
    name: "Thunderbolt 5 (USB-C) Pro Cable (1 m)",
    group: "power",
    generation: "cable",
    year: 2024,
    partNumber: "MDW94",
    colours: ["white"],
    defaultColour: "white",
    connection: "Thunderbolt 5",
    charging: null,
    features: ["Thunderbolt 5","1 m","Pro cable"],
    featureIds: ["thunderbolt-5","1-m","pro-cable"],
    weightG: null,
    tagline: "Latest Thunderbolt 5 Pro cable.",
    whoItSuits: "Newest Thunderbolt 5 Macs and docks.",
    whyChoose: ["Thunderbolt 5", "Pair with a matching adapter wattage.", "Check final specs on Apple's list."] as [string, string, string],
    platform: "both",
    checkFinalSpecs: true,
    notes: "Thunderbolt 5 (USB-C) Pro Cable (1 m) — check Apple's list for your device.",
    imageProductKey: "cable-tb5-1m",
    connector: "usb-c",
    stocked: true,
    geoUs: false,
    wattage: null,
    powerKind: "cable",
  }),
  a({
    id: "case-iphone-17-clear",
    name: "iPhone 17 Clear Case with MagSafe",
    group: "cases",
    generation: "Clear",
    year: 2025,
    partNumber: "MGF24",
    colours: ["Clear"],
    defaultColour: "Clear",
    connection: "MagSafe / case",
    charging: null,
    features: ["Clear","1 colour","Official Apple"],
    featureIds: ["clear"],
    weightG: null,
    tagline: "Made to fit — Clear.",
    whoItSuits: "Owners of iphone 17.",
    whyChoose: ["Clear finish", "Exact model fit matters", "Colour chosen at checkout — part number on bag"] as [string, string, string],
    platform: "iphone",
    checkFinalSpecs: true,
    notes: "Fits iphone-17 — check Apple's list.",
    imageProductKey: "case-iphone-17-clear",
    stocked: true,
    material: "Clear",
    fitsDeviceIds: ["iphone-17"],
  }),
  a({
    id: "case-iphone-17-pro-clear",
    name: "iPhone 17 Pro Clear Case with MagSafe",
    group: "cases",
    generation: "Clear",
    year: 2025,
    partNumber: "MGFT4",
    colours: ["Clear"],
    defaultColour: "Clear",
    connection: "MagSafe / case",
    charging: null,
    features: ["Clear","1 colour","Official Apple"],
    featureIds: ["clear"],
    weightG: null,
    tagline: "Made to fit — Clear.",
    whoItSuits: "Owners of iphone 17 pro.",
    whyChoose: ["Clear finish", "Exact model fit matters", "Colour chosen at checkout — part number on bag"] as [string, string, string],
    platform: "iphone",
    checkFinalSpecs: true,
    notes: "Fits iphone-17-pro — check Apple's list.",
    imageProductKey: "case-iphone-17-pro-clear",
    stocked: true,
    material: "Clear",
    fitsDeviceIds: ["iphone-17-pro"],
  }),
  a({
    id: "case-iphone-17-pro-max-clear",
    name: "iPhone 17 Pro Max Clear Case with MagSafe",
    group: "cases",
    generation: "Clear",
    year: 2025,
    partNumber: "MGFW4",
    colours: ["Clear"],
    defaultColour: "Clear",
    connection: "MagSafe / case",
    charging: null,
    features: ["Clear","1 colour","Official Apple"],
    featureIds: ["clear"],
    weightG: null,
    tagline: "Made to fit — Clear.",
    whoItSuits: "Owners of iphone 17 pro max.",
    whyChoose: ["Clear finish", "Exact model fit matters", "Colour chosen at checkout — part number on bag"] as [string, string, string],
    platform: "iphone",
    checkFinalSpecs: true,
    notes: "Fits iphone-17-pro-max — check Apple's list.",
    imageProductKey: "case-iphone-17-pro-max-clear",
    stocked: true,
    material: "Clear",
    fitsDeviceIds: ["iphone-17-pro-max"],
  }),
  a({
    id: "case-iphone-17-pro-max-silicone",
    name: "iPhone 17 Pro Max Silicone Case with MagSafe",
    group: "cases",
    generation: "Silicone",
    year: 2025,
    partNumber: "MGFR4",
    colours: ["Black","Bright Guava","Midnight","Orange","Purple Fog","Terra Cotta","Vanilla"],
    defaultColour: "Black",
    connection: "MagSafe / case",
    charging: null,
    features: ["Silicone","7 colours","Official Apple"],
    featureIds: ["silicone"],
    weightG: null,
    tagline: "Made to fit — Silicone.",
    whoItSuits: "Owners of iphone 17 pro max.",
    whyChoose: ["Silicone finish", "Exact model fit matters", "Colour chosen at checkout — part number on bag"] as [string, string, string],
    platform: "iphone",
    checkFinalSpecs: true,
    notes: "Fits iphone-17-pro-max — check Apple's list.",
    imageProductKey: "case-iphone-17-pro-max-silicone",
    stocked: true,
    material: "Silicone",
    fitsDeviceIds: ["iphone-17-pro-max"],
  }),
  a({
    id: "case-iphone-17-pro-silicone",
    name: "iPhone 17 Pro Silicone Case with MagSafe",
    group: "cases",
    generation: "Silicone",
    year: 2025,
    partNumber: "MGFK4",
    colours: ["Black","Bright Guava","Midnight","Orange","Purple Fog","Terra Cotta","Vanilla"],
    defaultColour: "Black",
    connection: "MagSafe / case",
    charging: null,
    features: ["Silicone","7 colours","Official Apple"],
    featureIds: ["silicone"],
    weightG: null,
    tagline: "Made to fit — Silicone.",
    whoItSuits: "Owners of iphone 17 pro.",
    whyChoose: ["Silicone finish", "Exact model fit matters", "Colour chosen at checkout — part number on bag"] as [string, string, string],
    platform: "iphone",
    checkFinalSpecs: true,
    notes: "Fits iphone-17-pro — check Apple's list.",
    imageProductKey: "case-iphone-17-pro-silicone",
    stocked: true,
    material: "Silicone",
    fitsDeviceIds: ["iphone-17-pro"],
  }),
  a({
    id: "case-iphone-17-silicone",
    name: "iPhone 17 Silicone Case with MagSafe",
    group: "cases",
    generation: "Silicone",
    year: 2025,
    partNumber: "MHVT4",
    colours: ["Electric Lavender","Anchor Blue","Black","Bright Guava","Light Moss","Purple Fog","Vanilla"],
    defaultColour: "Electric Lavender",
    connection: "MagSafe / case",
    charging: null,
    features: ["Silicone","7 colours","Official Apple"],
    featureIds: ["silicone"],
    weightG: null,
    tagline: "Made to fit — Silicone.",
    whoItSuits: "Owners of iphone 17.",
    whyChoose: ["Silicone finish", "Exact model fit matters", "Colour chosen at checkout — part number on bag"] as [string, string, string],
    platform: "iphone",
    checkFinalSpecs: true,
    notes: "Fits iphone-17 — check Apple's list.",
    imageProductKey: "case-iphone-17-silicone",
    stocked: true,
    material: "Silicone",
    fitsDeviceIds: ["iphone-17"],
  }),
  a({
    id: "case-iphone-17e-clear",
    name: "iPhone 17e Clear Case with MagSafe",
    group: "cases",
    generation: "Clear",
    year: 2025,
    partNumber: "MHWC4",
    colours: ["Clear"],
    defaultColour: "Clear",
    connection: "MagSafe / case",
    charging: null,
    features: ["Clear","1 colour","Official Apple"],
    featureIds: ["clear"],
    weightG: null,
    tagline: "Made to fit — Clear.",
    whoItSuits: "Owners of iphone 17e.",
    whyChoose: ["Clear finish", "Exact model fit matters", "Colour chosen at checkout — part number on bag"] as [string, string, string],
    platform: "iphone",
    checkFinalSpecs: true,
    notes: "Fits iphone-17e — check Apple's list.",
    imageProductKey: "case-iphone-17e-clear",
    stocked: true,
    material: "Clear",
    fitsDeviceIds: ["iphone-17e"],
  }),
  a({
    id: "case-iphone-17e-silicone",
    name: "iPhone 17e Silicone Case with MagSafe",
    group: "cases",
    generation: "Silicone",
    year: 2025,
    partNumber: "MHWJ4",
    colours: ["Soft Pink","Anchor Blue","Black","Bright Guava","Light Moss","Vanilla"],
    defaultColour: "Soft Pink",
    connection: "MagSafe / case",
    charging: null,
    features: ["Silicone","6 colours","Official Apple"],
    featureIds: ["silicone"],
    weightG: null,
    tagline: "Made to fit — Silicone.",
    whoItSuits: "Owners of iphone 17e.",
    whyChoose: ["Silicone finish", "Exact model fit matters", "Colour chosen at checkout — part number on bag"] as [string, string, string],
    platform: "iphone",
    checkFinalSpecs: true,
    notes: "Fits iphone-17e — check Apple's list.",
    imageProductKey: "case-iphone-17e-silicone",
    stocked: true,
    material: "Silicone",
    fitsDeviceIds: ["iphone-17e"],
  }),
  a({
    id: "case-iphone-18-pro-clear",
    name: "iPhone 18 Pro Clear Case with MagSafe",
    group: "cases",
    generation: "Clear",
    year: 2025,
    partNumber: "MKDU4",
    colours: ["Clear"],
    defaultColour: "Clear",
    connection: "MagSafe / case",
    charging: null,
    features: ["Clear","1 colour","Official Apple"],
    featureIds: ["clear"],
    weightG: null,
    tagline: "Made to fit — Clear.",
    whoItSuits: "Owners of iphone 18 pro.",
    whyChoose: ["Clear finish", "Exact model fit matters", "Colour chosen at checkout — part number on bag"] as [string, string, string],
    platform: "iphone",
    checkFinalSpecs: true,
    notes: "Fits iphone-18-pro — check Apple's list.",
    imageProductKey: "case-iphone-18-pro-clear",
    stocked: true,
    material: "Clear",
    fitsDeviceIds: ["iphone-18-pro"],
  }),
  a({
    id: "case-iphone-18-pro-max-clear",
    name: "iPhone 18 Pro Max Clear Case with MagSafe",
    group: "cases",
    generation: "Clear",
    year: 2025,
    partNumber: "MKDV4",
    colours: ["Clear"],
    defaultColour: "Clear",
    connection: "MagSafe / case",
    charging: null,
    features: ["Clear","1 colour","Official Apple"],
    featureIds: ["clear"],
    weightG: null,
    tagline: "Made to fit — Clear.",
    whoItSuits: "Owners of iphone 18 pro max.",
    whyChoose: ["Clear finish", "Exact model fit matters", "Colour chosen at checkout — part number on bag"] as [string, string, string],
    platform: "iphone",
    checkFinalSpecs: true,
    notes: "Fits iphone-18-pro-max — check Apple's list.",
    imageProductKey: "case-iphone-18-pro-max-clear",
    stocked: true,
    material: "Clear",
    fitsDeviceIds: ["iphone-18-pro-max"],
  }),
  a({
    id: "case-iphone-18-pro-max-silicone",
    name: "iPhone 18 Pro Max Silicone Case with MagSafe",
    group: "cases",
    generation: "Silicone",
    year: 2025,
    partNumber: "MK904",
    colours: ["Magenta","Black","Burgundy","Crisp Blue","Navy Blue","Olive"],
    defaultColour: "Magenta",
    connection: "MagSafe / case",
    charging: null,
    features: ["Silicone","6 colours","Official Apple"],
    featureIds: ["silicone"],
    weightG: null,
    tagline: "Made to fit — Silicone.",
    whoItSuits: "Owners of iphone 18 pro max.",
    whyChoose: ["Silicone finish", "Exact model fit matters", "Colour chosen at checkout — part number on bag"] as [string, string, string],
    platform: "iphone",
    checkFinalSpecs: true,
    notes: "Fits iphone-18-pro-max — check Apple's list.",
    imageProductKey: "case-iphone-18-pro-max-silicone",
    stocked: true,
    material: "Silicone",
    fitsDeviceIds: ["iphone-18-pro-max"],
  }),
  a({
    id: "case-iphone-18-pro-max-techwoven",
    name: "iPhone 18 Pro Max TechWoven Case with MagSafe",
    group: "cases",
    generation: "TechWoven",
    year: 2025,
    partNumber: "MKDM4",
    colours: ["Burgundy","Black","Chambray Blue","Mulberry","Olive","Taupe"],
    defaultColour: "Burgundy",
    connection: "MagSafe / case",
    charging: null,
    features: ["TechWoven","6 colours","Official Apple"],
    featureIds: ["techwoven"],
    weightG: null,
    tagline: "Made to fit — TechWoven.",
    whoItSuits: "Owners of iphone 18 pro max.",
    whyChoose: ["TechWoven finish", "Exact model fit matters", "Colour chosen at checkout — part number on bag"] as [string, string, string],
    platform: "iphone",
    checkFinalSpecs: true,
    notes: "Fits iphone-18-pro-max — check Apple's list.",
    imageProductKey: "case-iphone-18-pro-max-techwoven",
    stocked: true,
    material: "TechWoven",
    fitsDeviceIds: ["iphone-18-pro-max"],
  }),
  a({
    id: "case-iphone-18-pro-silicone",
    name: "iPhone 18 Pro Silicone Case with MagSafe",
    group: "cases",
    generation: "Silicone",
    year: 2025,
    partNumber: "MK8W4",
    colours: ["Crisp Blue","Black","Burgundy","Magenta","Navy Blue","Olive"],
    defaultColour: "Crisp Blue",
    connection: "MagSafe / case",
    charging: null,
    features: ["Silicone","6 colours","Official Apple"],
    featureIds: ["silicone"],
    weightG: null,
    tagline: "Made to fit — Silicone.",
    whoItSuits: "Owners of iphone 18 pro.",
    whyChoose: ["Silicone finish", "Exact model fit matters", "Colour chosen at checkout — part number on bag"] as [string, string, string],
    platform: "iphone",
    checkFinalSpecs: true,
    notes: "Fits iphone-18-pro — check Apple's list.",
    imageProductKey: "case-iphone-18-pro-silicone",
    stocked: true,
    material: "Silicone",
    fitsDeviceIds: ["iphone-18-pro"],
  }),
  a({
    id: "case-iphone-18-pro-techwoven",
    name: "iPhone 18 Pro TechWoven Case with MagSafe",
    group: "cases",
    generation: "TechWoven",
    year: 2025,
    partNumber: "MKD54",
    colours: ["Chambray Blue","Black","Burgundy","Mulberry","Olive","Taupe"],
    defaultColour: "Chambray Blue",
    connection: "MagSafe / case",
    charging: null,
    features: ["TechWoven","6 colours","Official Apple"],
    featureIds: ["techwoven"],
    weightG: null,
    tagline: "Made to fit — TechWoven.",
    whoItSuits: "Owners of iphone 18 pro.",
    whyChoose: ["TechWoven finish", "Exact model fit matters", "Colour chosen at checkout — part number on bag"] as [string, string, string],
    platform: "iphone",
    checkFinalSpecs: true,
    notes: "Fits iphone-18-pro — check Apple's list.",
    imageProductKey: "case-iphone-18-pro-techwoven",
    stocked: true,
    material: "TechWoven",
    fitsDeviceIds: ["iphone-18-pro"],
  }),
  a({
    id: "case-iphone-air-bumper",
    name: "iPhone Air Bumper",
    group: "cases",
    generation: "Bumper",
    year: 2025,
    partNumber: "MH024",
    colours: ["Light Blue","Black","Light Gray","Tan"],
    defaultColour: "Light Blue",
    connection: "MagSafe / case",
    charging: null,
    features: ["Bumper","4 colours","Official Apple"],
    featureIds: ["bumper"],
    weightG: null,
    tagline: "Made to fit — Bumper.",
    whoItSuits: "Owners of iphone air.",
    whyChoose: ["Bumper finish", "Exact model fit matters", "Colour chosen at checkout — part number on bag"] as [string, string, string],
    platform: "iphone",
    checkFinalSpecs: true,
    notes: "Fits iphone-air — check Apple's list.",
    imageProductKey: "case-iphone-air-bumper",
    stocked: true,
    material: "Bumper",
    fitsDeviceIds: ["iphone-air"],
  }),
  a({
    id: "case-iphone-air-case",
    name: "iPhone Air Case with MagSafe",
    group: "cases",
    generation: "Air Case",
    year: 2025,
    partNumber: "MGH24",
    colours: ["Shadow","Frost"],
    defaultColour: "Shadow",
    connection: "MagSafe / case",
    charging: null,
    features: ["Air Case","2 colours","Official Apple"],
    featureIds: ["air-case"],
    weightG: null,
    tagline: "Made to fit — Air Case.",
    whoItSuits: "Owners of iphone air.",
    whyChoose: ["Air Case finish", "Exact model fit matters", "Colour chosen at checkout — part number on bag"] as [string, string, string],
    platform: "iphone",
    checkFinalSpecs: true,
    notes: "Fits iphone-air — check Apple's list.",
    imageProductKey: "case-iphone-air-case",
    stocked: true,
    material: "Air Case",
    fitsDeviceIds: ["iphone-air"],
  }),
  a({
    id: "case-iphone-duo-case",
    name: "iPhone Duo Case",
    group: "cases",
    generation: "Duo Case",
    year: 2025,
    partNumber: "MKR84",
    colours: ["Navy Blue","Sand"],
    defaultColour: "Navy Blue",
    connection: "MagSafe / case",
    charging: null,
    features: ["Duo Case","2 colours","Official Apple"],
    featureIds: ["duo-case"],
    weightG: null,
    tagline: "Made to fit — Duo Case.",
    whoItSuits: "MagSafe iPhone owners — confirm model fit.",
    whyChoose: ["Duo Case finish", "Exact model fit matters", "Colour chosen at checkout — part number on bag"] as [string, string, string],
    platform: "iphone",
    checkFinalSpecs: true,
    notes: "Fits iphone-17, iphone-17-pro, iphone-17-pro-max, iphone-17e, iphone-air, iphone-18-pro, iphone-18-pro-max — check Apple's list.",
    imageProductKey: "case-iphone-duo-case",
    stocked: true,
    material: "Duo Case",
    fitsDeviceIds: ["iphone-17","iphone-17-pro","iphone-17-pro-max","iphone-17e","iphone-air","iphone-18-pro","iphone-18-pro-max"],
  }),
  a({
    id: "case-iphone-duo-folio",
    name: "iPhone Duo Folio with Kickstand",
    group: "cases",
    generation: "Duo Folio",
    year: 2025,
    partNumber: "MKR64",
    colours: ["Taupe","Navy Blue"],
    defaultColour: "Taupe",
    connection: "MagSafe / case",
    charging: null,
    features: ["Duo Folio","2 colours","Official Apple"],
    featureIds: ["duo-folio"],
    weightG: null,
    tagline: "Made to fit — Duo Folio.",
    whoItSuits: "MagSafe iPhone owners — confirm model fit.",
    whyChoose: ["Duo Folio finish", "Exact model fit matters", "Colour chosen at checkout — part number on bag"] as [string, string, string],
    platform: "iphone",
    checkFinalSpecs: true,
    notes: "Fits iphone-17, iphone-17-pro, iphone-17-pro-max, iphone-17e, iphone-air, iphone-18-pro, iphone-18-pro-max — check Apple's list.",
    imageProductKey: "case-iphone-duo-folio",
    stocked: true,
    material: "Duo Folio",
    fitsDeviceIds: ["iphone-17","iphone-17-pro","iphone-17-pro-max","iphone-17e","iphone-air","iphone-18-pro","iphone-18-pro-max"],
  }),
  a({
    id: "case-iphone-finewoven-wallet",
    name: "iPhone FineWoven Wallet with MagSafe",
    group: "cases",
    generation: "FineWoven",
    year: 2025,
    partNumber: "MK9G4",
    colours: ["Magenta","Black","Burgundy","Dark Olive","Navy","Wildflower Blue"],
    defaultColour: "Magenta",
    connection: "MagSafe / case",
    charging: null,
    features: ["FineWoven","6 colours","Official Apple"],
    featureIds: ["finewoven"],
    weightG: null,
    tagline: "Made to fit — FineWoven.",
    whoItSuits: "MagSafe iPhone owners — confirm model fit.",
    whyChoose: ["FineWoven finish", "Exact model fit matters", "Colour chosen at checkout — part number on bag"] as [string, string, string],
    platform: "iphone",
    checkFinalSpecs: true,
    notes: "Fits iphone-17, iphone-17-pro, iphone-17-pro-max, iphone-17e, iphone-air, iphone-18-pro, iphone-18-pro-max — check Apple's list.",
    imageProductKey: "case-iphone-finewoven-wallet",
    stocked: true,
    material: "FineWoven",
    fitsDeviceIds: ["iphone-17","iphone-17-pro","iphone-17-pro-max","iphone-17e","iphone-air","iphone-18-pro","iphone-18-pro-max"],
  }),
  a({
    id: "strap-crossbody",
    name: "Crossbody Strap",
    group: "cases",
    generation: "Strap",
    year: 2025,
    partNumber: "MK9D4",
    colours: ["Black","Burgundy","Crisp Blue","Light Gray","Magenta","Navy Blue","Olive","Sand","Taupe"],
    defaultColour: "Black",
    connection: "MagSafe / case",
    charging: null,
    features: ["Strap","9 colours","Official Apple"],
    featureIds: ["strap"],
    weightG: null,
    tagline: "Carry with MagSafe-compatible cases.",
    whoItSuits: "MagSafe iPhone owners — confirm model fit.",
    whyChoose: ["Strap finish", "Exact model fit matters", "Colour chosen at checkout — part number on bag"] as [string, string, string],
    platform: "iphone",
    checkFinalSpecs: true,
    notes: "Fits iphone-17, iphone-17-pro, iphone-17-pro-max, iphone-17e, iphone-air, iphone-18-pro, iphone-18-pro-max — check Apple's list.",
    imageProductKey: "strap-crossbody",
    stocked: true,
    material: "Strap",
    fitsDeviceIds: ["iphone-17","iphone-17-pro","iphone-17-pro-max","iphone-17e","iphone-air","iphone-18-pro","iphone-18-pro-max"],
  }),
  a({
    id: "strap-wrist",
    name: "Wrist Strap",
    group: "cases",
    generation: "Strap",
    year: 2025,
    partNumber: "MKF74",
    colours: ["Burgundy","Black","Crisp Blue","Magenta","Olive","Taupe"],
    defaultColour: "Burgundy",
    connection: "MagSafe / case",
    charging: null,
    features: ["Strap","6 colours","Official Apple"],
    featureIds: ["strap"],
    weightG: null,
    tagline: "Carry with MagSafe-compatible cases.",
    whoItSuits: "MagSafe iPhone owners — confirm model fit.",
    whyChoose: ["Strap finish", "Exact model fit matters", "Colour chosen at checkout — part number on bag"] as [string, string, string],
    platform: "iphone",
    checkFinalSpecs: true,
    notes: "Fits iphone-17, iphone-17-pro, iphone-17-pro-max, iphone-17e, iphone-air, iphone-18-pro, iphone-18-pro-max — check Apple's list.",
    imageProductKey: "strap-wrist",
    stocked: true,
    material: "Strap",
    fitsDeviceIds: ["iphone-17","iphone-17-pro","iphone-17-pro-max","iphone-17e","iphone-air","iphone-18-pro","iphone-18-pro-max"],
  }),
  a({
    id: "folio-ipad-a16",
    name: "Smart Folio for iPad A16",
    group: "cases",
    generation: "Smart Folio",
    year: 2025,
    partNumber: "MDEN4",
    colours: ["Lemonade","Sky","Watermelon","White"],
    defaultColour: "Lemonade",
    connection: "Smart Folio attach",
    charging: null,
    features: ["Smart Folio","4 colours","Official Apple"],
    featureIds: ["smart-folio"],
    weightG: null,
    tagline: "Front and back cover with stand angles.",
    whoItSuits: "Owners of ipad a16.",
    whyChoose: ["Smart Folio finish", "Exact model fit matters", "Colour chosen at checkout — part number on bag"] as [string, string, string],
    platform: "ipad",
    checkFinalSpecs: true,
    notes: "Fits ipad-a16 — check Apple's list.",
    imageProductKey: "folio-ipad-a16",
    stocked: true,
    material: "Smart Folio",
    fitsDeviceIds: ["ipad-a16"],
  }),
  a({
    id: "folio-ipad-air-11-m4",
    name: "Smart Folio for iPad Air 11-inch M4",
    group: "cases",
    generation: "Smart Folio",
    year: 2025,
    partNumber: "MWK53",
    colours: ["Charcoal Gray","Denim","Light Violet","Sage"],
    defaultColour: "Charcoal Gray",
    connection: "Smart Folio attach",
    charging: null,
    features: ["Smart Folio","4 colours","Official Apple"],
    featureIds: ["smart-folio"],
    weightG: null,
    tagline: "Front and back cover with stand angles.",
    whoItSuits: "Matching device only — use the finder.",
    whyChoose: ["Smart Folio finish", "Exact model fit matters", "Colour chosen at checkout — part number on bag"] as [string, string, string],
    platform: "ipad",
    checkFinalSpecs: true,
    notes: "Fits ipad-air-11-m4, ipad-air-11-m3, ipad-air-11-m2 — check Apple's list.",
    imageProductKey: "folio-ipad-air-11-m4",
    stocked: true,
    material: "Smart Folio",
    fitsDeviceIds: ["ipad-air-11-m4","ipad-air-11-m3","ipad-air-11-m2"],
  }),
  a({
    id: "folio-ipad-air-13-m4",
    name: "Smart Folio for iPad Air 13-inch M4",
    group: "cases",
    generation: "Smart Folio",
    year: 2025,
    partNumber: "MWK93",
    colours: ["Charcoal Gray","Denim","Light Violet","Sage"],
    defaultColour: "Charcoal Gray",
    connection: "Smart Folio attach",
    charging: null,
    features: ["Smart Folio","4 colours","Official Apple"],
    featureIds: ["smart-folio"],
    weightG: null,
    tagline: "Front and back cover with stand angles.",
    whoItSuits: "Matching device only — use the finder.",
    whyChoose: ["Smart Folio finish", "Exact model fit matters", "Colour chosen at checkout — part number on bag"] as [string, string, string],
    platform: "ipad",
    checkFinalSpecs: true,
    notes: "Fits ipad-air-13-m4, ipad-air-13-m3, ipad-air-13-m2 — check Apple's list.",
    imageProductKey: "folio-ipad-air-13-m4",
    stocked: true,
    material: "Smart Folio",
    fitsDeviceIds: ["ipad-air-13-m4","ipad-air-13-m3","ipad-air-13-m2"],
  }),
  a({
    id: "folio-ipad-pro-11-m5",
    name: "Smart Folio for iPad Pro 11-inch M5",
    group: "cases",
    generation: "Smart Folio",
    year: 2025,
    partNumber: "MW983",
    colours: ["Black","Denim","White"],
    defaultColour: "Black",
    connection: "Smart Folio attach",
    charging: null,
    features: ["Smart Folio","3 colours","Official Apple"],
    featureIds: ["smart-folio"],
    weightG: null,
    tagline: "Front and back cover with stand angles.",
    whoItSuits: "Matching device only — use the finder.",
    whyChoose: ["Smart Folio finish", "Exact model fit matters", "Colour chosen at checkout — part number on bag"] as [string, string, string],
    platform: "ipad",
    checkFinalSpecs: true,
    notes: "Fits ipad-pro-11-m5, ipad-pro-11-m4 — check Apple's list.",
    imageProductKey: "folio-ipad-pro-11-m5",
    stocked: true,
    material: "Smart Folio",
    fitsDeviceIds: ["ipad-pro-11-m5","ipad-pro-11-m4"],
  }),
  a({
    id: "folio-ipad-pro-13-m5",
    name: "Smart Folio for iPad Pro 13-inch M5",
    group: "cases",
    generation: "Smart Folio",
    year: 2025,
    partNumber: "MWK33",
    colours: ["Black","Denim","White"],
    defaultColour: "Black",
    connection: "Smart Folio attach",
    charging: null,
    features: ["Smart Folio","3 colours","Official Apple"],
    featureIds: ["smart-folio"],
    weightG: null,
    tagline: "Front and back cover with stand angles.",
    whoItSuits: "Matching device only — use the finder.",
    whyChoose: ["Smart Folio finish", "Exact model fit matters", "Colour chosen at checkout — part number on bag"] as [string, string, string],
    platform: "ipad",
    checkFinalSpecs: true,
    notes: "Fits ipad-pro-13-m5, ipad-pro-13-m4 — check Apple's list.",
    imageProductKey: "folio-ipad-pro-13-m5",
    stocked: true,
    material: "Smart Folio",
    fitsDeviceIds: ["ipad-pro-13-m5","ipad-pro-13-m4"],
  }),
  a({
    id: "folio-ipad-mini-a17-pro",
    name: "Smart Folio for iPad mini A17 Pro",
    group: "cases",
    generation: "Smart Folio",
    year: 2025,
    partNumber: "MC2Q4",
    colours: ["Charcoal Gray","Denim","Light Violet","Sage"],
    defaultColour: "Charcoal Gray",
    connection: "Smart Folio attach",
    charging: null,
    features: ["Smart Folio","4 colours","Official Apple"],
    featureIds: ["smart-folio"],
    weightG: null,
    tagline: "Front and back cover with stand angles.",
    whoItSuits: "Owners of ipad mini a17 pro.",
    whyChoose: ["Smart Folio finish", "Exact model fit matters", "Colour chosen at checkout — part number on bag"] as [string, string, string],
    platform: "ipad",
    checkFinalSpecs: true,
    notes: "Fits ipad-mini-a17-pro — check Apple's list.",
    imageProductKey: "folio-ipad-mini-a17-pro",
    stocked: true,
    material: "Smart Folio",
    fitsDeviceIds: ["ipad-mini-a17-pro"],
  }),
];


export function powerProducts(): Accessory[] {
  return accessories.filter((a) => a.group === "power" && a.stocked !== false);
}

export function caseProducts(): Accessory[] {
  return accessories.filter((a) => a.group === "cases" && a.stocked !== false);
}

export function adapters(): Accessory[] {
  return powerProducts().filter((p) => p.powerKind === "adapter");
}

export function cables(): Accessory[] {
  return powerProducts().filter((p) => p.powerKind === "cable");
}

export function magsafeChargers(): Accessory[] {
  return powerProducts().filter((p) => p.powerKind === "magsafe" || p.powerKind === "watch");
}

export function getCaseVariants(productId: string): CaseVariantFamily | null {
  const all = (accessoriesManifest as { caseVariants?: Record<string, CaseVariantFamily> }).caseVariants;
  return all?.[productId] || null;
}

export function getVariantImage(
  productId: string,
  partNumber: string,
): { src: string; swatch: string | null; colour: string; partNumber: string; angles: string[] } | null {
  const family = getCaseVariants(productId);
  if (!family) return null;
  const v = family.variants.find((x) => x.partNumber === partNumber) || family.variants[0];
  if (!v) return null;
  return {
    src: v.mainImage,
    swatch: v.swatchImage,
    colour: v.colour,
    partNumber: v.partNumber,
    angles: v.angleImages || [],
  };
}

function fit(status: FitResult["status"], reason: string): FitResult {
  return { status, reason, checkFinalSpecs: true };
}

/** caseFits(deviceId, caseId) */
export function caseFits(deviceId: string, caseId: string): FitResult {
  const product = getAccessory(caseId);
  if (!product || product.group !== "cases") return fit("no", "Unknown case.");
  const d = deviceId.toLowerCase();
  if (/older|legacy|whatsapp/.test(d)) {
    return fit("note", "Older iPhone cases — ask on WhatsApp for stock and fit.");
  }
  const listed = product.fitsDeviceIds || [];
  if (!listed.length) return fit("note", "Confirm fit on Apple's list — check.");
  if (listed.some((id) => d === id || d.includes(id) || id.includes(d))) {
    return fit("fits", "Listed for this device family — check Apple's list.");
  }
  if (caseId.startsWith("folio-") && /ipad/.test(d)) {
    return fit("no", "This Smart Folio is for a different iPad size or chip — check.");
  }
  if ((caseId.startsWith("strap-") || caseId.includes("duo") || caseId.includes("finewoven")) && /iphone/.test(d)) {
    return fit("note", "MagSafe accessory — confirm MagSafe support on your iPhone.");
  }
  return fit("no", "Does not fit this device per our model map — check.");
}

/** chargerAdvice(deviceId) */
export function chargerAdvice(deviceId: string): {
  recommended: string[];
  optional: string[];
  note: string;
} {
  const d = deviceId.toLowerCase();
  if (/iphone|airpods|watch/.test(d) && !/macbook|imac|mac-mini|mac-studio/.test(d)) {
    return {
      recommended: ["power-adapter-20w", "cable-usbc-60w-1m"],
      optional: ["magsafe-charger-1m", "power-adapter-35w-dual"],
      note: "20W is the everyday phone class. MagSafe charger needs a USB-C adapter.",
    };
  }
  if (/ipad/.test(d)) {
    return {
      recommended: ["power-adapter-20w", "cable-usbc-60w-1m"],
      optional: ["power-adapter-35w-dual", "power-adapter-70w"],
      note: "Many iPads ship with or accept 20W; larger Pro models can use higher-watt bricks.",
    };
  }
  if (/macbook-air|mac-mini|imac/.test(d)) {
    return {
      recommended: ["power-adapter-70w", "cable-usbc-240w-2m"],
      optional: ["cable-magsafe3-2m", "power-adapter-96w"],
      note: "70W covers most Air and many desktop needs. MagSafe 3 cable if your Mac has MagSafe.",
    };
  }
  if (/macbook-pro-14|14-inch/.test(d)) {
    return {
      recommended: ["power-adapter-70w", "cable-usbc-240w-2m"],
      optional: ["power-adapter-96w", "cable-magsafe3-2m"],
      note: "70W is the common daily brick; 96W adds headroom.",
    };
  }
  if (/macbook-pro-16|16-inch|mac-studio/.test(d)) {
    return {
      recommended: ["power-adapter-140w", "cable-usbc-240w-2m"],
      optional: ["power-adapter-96w", "cable-magsafe3-2m", "cable-tb5-1m"],
      note: "140W for full-rate charge on the highest-watt MacBooks — use a high-watt cable.",
    };
  }
  if (/macbook|mac/.test(d)) {
    return {
      recommended: ["power-adapter-70w", "cable-usbc-240w-2m"],
      optional: ["power-adapter-96w", "power-adapter-140w"],
      note: "Start at 70W unless you know you need more — check Apple's wattage for your Mac.",
    };
  }
  return {
    recommended: ["power-adapter-20w", "cable-usbc-60w-1m"],
    optional: ["power-adapter-70w"],
    note: "Pick your device for a tighter recommendation. Check Apple's list.",
  };
}

export function pairingNote(adapterId: string, cableId: string): string {
  const adapter = getAccessory(adapterId);
  const cable = getAccessory(cableId);
  if (!adapter || !cable) return "Pick an adapter and a cable to see pairing notes.";
  const aw = adapter.wattage;
  const cw = cable.wattage;
  if (adapter.powerKind === "adapter" && cable.powerKind === "cable") {
    if (aw && cw && cw < aw) {
      return adapter.name + " can deliver up to " + aw + "W, but " + cable.name + " is rated " + cw + "W — the cable becomes the limit.";
    }
    if (aw && cw && cw >= aw) {
      return cable.name + " can carry " + adapter.name + " power (" + aw + "W). Good pairing.";
    }
    return "Pair " + adapter.name + " with " + cable.name + " — confirm wattage on Apple's pages.";
  }
  if (adapter.powerKind === "magsafe") {
    return "MagSafe Charger needs a USB-C power adapter (often 20W+). Cable is built in.";
  }
  return adapter.name + " + " + cable.name + " — check final specs.";
}
