/**
 * iPad catalog (Pro / Air / mini / standard, 2020 - 2026).
 * Specs from Apple's published figures in the iPad prompt.
 * re-verify every number on apple.com before launch.
 * M5 Pro, M4 Air, and A16 iPad carry checkFinalSpecs.
 */

import { ipadBasePricesKes } from "./config";

export type IpadFamily = "Pro" | "Air" | "mini" | "iPad";
export type IpadChipGen = "M5" | "M4" | "M3" | "M2" | "M1" | "A17" | "A16" | "A15" | "A14" | "A13" | "A12Z" | "A12";

export type PencilSupport = "pro" | "usb-c" | "2nd" | "1st";
export type KeyboardSupport = "magic-pro" | "magic-air" | "magic-folio" | "smart-keyboard" | "none";

export type IpadModel = {
  id: keyof typeof ipadBasePricesKes;
  name: string;
  family: IpadFamily;
  chipGen: IpadChipGen;
  chip: string;
  year: number;
  generation?: string;
  screenInches: number;
  display: {
    diagonal: number;
    resolution: string;
    ppi: number;
    panel: string;
    brightnessNits: number;
    peakHdrNits?: number;
    refreshHz: number;
    promotion?: boolean;
    nanoTextureOptional?: boolean;
  };
  cpuCores: string;
  gpuCores: string;
  memoryGb: number[];
  storageOptions: string[];
  batteryHours: number;
  ports: string[];
  frontCamera: string;
  rearCamera: string;
  biometrics: "Face ID" | "Touch ID";
  pencils: PencilSupport[];
  keyboards: KeyboardSupport[];
  wifi: string;
  bluetooth: string;
  cellular: boolean;
  weightG: number;
  thicknessKey: "pro-11-m4" | "pro-13-m4" | "pro-older" | "air" | "mini" | "ipad";
  colours: string[];
  defaultColour: string;
  appleIntelligence: boolean;
  tagline: string;
  whoItSuits: string;
  whyChoose: [string, string, string];
  basePriceKes: number;
  overviewOnly?: boolean;
  checkFinalSpecs?: boolean;
  isNew?: boolean;
  notes?: string;
};

const P = ipadBasePricesKes;

/** re-verify all specs against apple.com before launch. */
export const ipadModels: IpadModel[] = [
  // -- Pro --
  {
    id: "ipad-pro-11-2020",
    name: "iPad Pro 11″ (2020)",
    family: "Pro",
    chipGen: "A12Z",
    chip: "A12Z Bionic",
    year: 2020,
    generation: "2nd gen",
    screenInches: 11,
    display: {
      diagonal: 11,
      resolution: "2388×1668",
      ppi: 264,
      panel: "Liquid Retina",
      brightnessNits: 600,
      refreshHz: 120,
      promotion: true,
    },
    cpuCores: "8-core",
    gpuCores: "8-core",
    memoryGb: [6],
    storageOptions: ["128 GB", "256 GB", "512 GB", "1 TB"],
    batteryHours: 10,
    ports: ["USB-C"],
    frontCamera: "7MP TrueDepth",
    rearCamera: "12MP Wide + 10MP Ultra Wide + LiDAR",
    biometrics: "Face ID",
    pencils: ["2nd"],
    keyboards: ["magic-pro"],
    wifi: "Wi-Fi 6",
    bluetooth: "5.0",
    cellular: true,
    weightG: 471,
    thicknessKey: "pro-older",
    colours: ["space-gray", "silver"],
    defaultColour: "space-gray",
    appleIntelligence: false,
    tagline: "The first Pro with LiDAR.",
    whoItSuits: "Creators who want ProMotion on a budget and will check condition.",
    whyChoose: [
      "ProMotion 120 Hz Liquid Retina.",
      "LiDAR and dual rear cameras.",
      "Apple Pencil (2nd gen) support.",
    ],
    basePriceKes: P["ipad-pro-11-2020"],
    overviewOnly: true,
    notes: "Check battery health and condition on older stock.",
  },
  {
    id: "ipad-pro-12-9-2020",
    name: "iPad Pro 12.9″ (2020)",
    family: "Pro",
    chipGen: "A12Z",
    chip: "A12Z Bionic",
    year: 2020,
    generation: "4th gen",
    screenInches: 12.9,
    display: {
      diagonal: 12.9,
      resolution: "2732×2048",
      ppi: 264,
      panel: "Liquid Retina",
      brightnessNits: 600,
      refreshHz: 120,
      promotion: true,
    },
    cpuCores: "8-core",
    gpuCores: "8-core",
    memoryGb: [6],
    storageOptions: ["128 GB", "256 GB", "512 GB", "1 TB"],
    batteryHours: 10,
    ports: ["USB-C"],
    frontCamera: "7MP TrueDepth",
    rearCamera: "12MP Wide + 10MP Ultra Wide + LiDAR",
    biometrics: "Face ID",
    pencils: ["2nd"],
    keyboards: ["magic-pro"],
    wifi: "Wi-Fi 6",
    bluetooth: "5.0",
    cellular: true,
    weightG: 641,
    thicknessKey: "pro-older",
    colours: ["space-gray", "silver"],
    defaultColour: "space-gray",
    appleIntelligence: false,
    tagline: "Big canvas, LiDAR, ProMotion.",
    whoItSuits: "Illustration and video on a large older Pro.",
    whyChoose: [
      "12.9″ ProMotion display.",
      "LiDAR Scanner.",
      "Magic Keyboard ready.",
    ],
    basePriceKes: P["ipad-pro-12-9-2020"],
    overviewOnly: true,
  },
  {
    id: "ipad-pro-11-m1",
    name: "iPad Pro 11″ M1",
    family: "Pro",
    chipGen: "M1",
    chip: "M1",
    year: 2021,
    generation: "3rd gen",
    screenInches: 11,
    display: {
      diagonal: 11,
      resolution: "2388×1668",
      ppi: 264,
      panel: "Liquid Retina",
      brightnessNits: 600,
      refreshHz: 120,
      promotion: true,
    },
    cpuCores: "8-core",
    gpuCores: "8-core",
    memoryGb: [8, 16],
    storageOptions: ["128 GB", "256 GB", "512 GB", "1 TB", "2 TB"],
    batteryHours: 10,
    ports: ["Thunderbolt / USB 4"],
    frontCamera: "12MP Ultra Wide Center Stage",
    rearCamera: "12MP Wide + 10MP Ultra Wide + LiDAR",
    biometrics: "Face ID",
    pencils: ["2nd"],
    keyboards: ["magic-pro"],
    wifi: "Wi-Fi 6",
    bluetooth: "5.0",
    cellular: true,
    weightG: 466,
    thicknessKey: "pro-older",
    colours: ["space-gray", "silver"],
    defaultColour: "space-gray",
    appleIntelligence: true,
    tagline: "M1 power in an 11-inch Pro.",
    whoItSuits: "Creators who want Apple Intelligence on a compact Pro.",
    whyChoose: [
      "M1 and Thunderbolt.",
      "Center Stage front camera.",
      "Apple Intelligence supported.",
    ],
    basePriceKes: P["ipad-pro-11-m1"],
    overviewOnly: true,
  },
  {
    id: "ipad-pro-12-9-m1",
    name: "iPad Pro 12.9″ M1",
    family: "Pro",
    chipGen: "M1",
    chip: "M1",
    year: 2021,
    generation: "5th gen",
    screenInches: 12.9,
    display: {
      diagonal: 12.9,
      resolution: "2732×2048",
      ppi: 264,
      panel: "Liquid Retina XDR (mini-LED)",
      brightnessNits: 1000,
      peakHdrNits: 1600,
      refreshHz: 120,
      promotion: true,
    },
    cpuCores: "8-core",
    gpuCores: "8-core",
    memoryGb: [8, 16],
    storageOptions: ["128 GB", "256 GB", "512 GB", "1 TB", "2 TB"],
    batteryHours: 10,
    ports: ["Thunderbolt / USB 4"],
    frontCamera: "12MP Ultra Wide Center Stage",
    rearCamera: "12MP Wide + 10MP Ultra Wide + LiDAR",
    biometrics: "Face ID",
    pencils: ["2nd"],
    keyboards: ["magic-pro"],
    wifi: "Wi-Fi 6",
    bluetooth: "5.0",
    cellular: true,
    weightG: 682,
    thicknessKey: "pro-older",
    colours: ["space-gray", "silver"],
    defaultColour: "space-gray",
    appleIntelligence: true,
    tagline: "XDR brightness meets M1.",
    whoItSuits: "Colour-critical work on a large mini-LED screen.",
    whyChoose: [
      "Liquid Retina XDR mini-LED.",
      "M1 and Thunderbolt.",
      "Apple Intelligence supported.",
    ],
    basePriceKes: P["ipad-pro-12-9-m1"],
    overviewOnly: true,
  },
  {
    id: "ipad-pro-11-m2",
    name: "iPad Pro 11″ M2",
    family: "Pro",
    chipGen: "M2",
    chip: "M2",
    year: 2022,
    generation: "4th gen",
    screenInches: 11,
    display: {
      diagonal: 11,
      resolution: "2388×1668",
      ppi: 264,
      panel: "Liquid Retina",
      brightnessNits: 600,
      refreshHz: 120,
      promotion: true,
    },
    cpuCores: "8-core",
    gpuCores: "10-core",
    memoryGb: [8, 16],
    storageOptions: ["128 GB", "256 GB", "512 GB", "1 TB", "2 TB"],
    batteryHours: 10,
    ports: ["Thunderbolt / USB 4"],
    frontCamera: "12MP Ultra Wide Center Stage",
    rearCamera: "12MP Wide + 10MP Ultra Wide + LiDAR",
    biometrics: "Face ID",
    pencils: ["2nd"],
    keyboards: ["magic-pro"],
    wifi: "Wi-Fi 6E",
    bluetooth: "5.3",
    cellular: true,
    weightG: 466,
    thicknessKey: "pro-older",
    colours: ["space-gray", "silver"],
    defaultColour: "space-gray",
    appleIntelligence: true,
    tagline: "M2 with Pencil hover.",
    whoItSuits: "Artists who want hover before the OLED Pro.",
    whyChoose: [
      "Apple Pencil hover.",
      "M2 and Wi-Fi 6E.",
      "Same compact Pro design.",
    ],
    basePriceKes: P["ipad-pro-11-m2"],
    overviewOnly: true,
  },
  {
    id: "ipad-pro-12-9-m2",
    name: "iPad Pro 12.9″ M2",
    family: "Pro",
    chipGen: "M2",
    chip: "M2",
    year: 2022,
    generation: "6th gen",
    screenInches: 12.9,
    display: {
      diagonal: 12.9,
      resolution: "2732×2048",
      ppi: 264,
      panel: "Liquid Retina XDR (mini-LED)",
      brightnessNits: 1000,
      peakHdrNits: 1600,
      refreshHz: 120,
      promotion: true,
    },
    cpuCores: "8-core",
    gpuCores: "10-core",
    memoryGb: [8, 16],
    storageOptions: ["128 GB", "256 GB", "512 GB", "1 TB", "2 TB"],
    batteryHours: 10,
    ports: ["Thunderbolt / USB 4"],
    frontCamera: "12MP Ultra Wide Center Stage",
    rearCamera: "12MP Wide + 10MP Ultra Wide + LiDAR",
    biometrics: "Face ID",
    pencils: ["2nd"],
    keyboards: ["magic-pro"],
    wifi: "Wi-Fi 6E",
    bluetooth: "5.3",
    cellular: true,
    weightG: 682,
    thicknessKey: "pro-older",
    colours: ["space-gray", "silver"],
    defaultColour: "space-gray",
    appleIntelligence: true,
    tagline: "XDR and Pencil hover.",
    whoItSuits: "Pros who need the big XDR before tandem OLED.",
    whyChoose: [
      "Liquid Retina XDR.",
      "Pencil hover on M2.",
      "Apple Intelligence supported.",
    ],
    basePriceKes: P["ipad-pro-12-9-m2"],
    overviewOnly: true,
  },
  {
    id: "ipad-pro-11-m4",
    name: "iPad Pro 11″ M4",
    family: "Pro",
    chipGen: "M4",
    chip: "M4",
    year: 2024,
    screenInches: 11,
    display: {
      diagonal: 11,
      resolution: "2420×1668",
      ppi: 264,
      panel: "Ultra Retina XDR (tandem OLED)",
      brightnessNits: 1000,
      peakHdrNits: 1600,
      refreshHz: 120,
      promotion: true,
      nanoTextureOptional: true,
    },
    cpuCores: "9 or 10-core",
    gpuCores: "10-core",
    memoryGb: [8, 16],
    storageOptions: ["256 GB", "512 GB", "1 TB", "2 TB"],
    batteryHours: 10,
    ports: ["Thunderbolt / USB 4"],
    frontCamera: "12MP landscape Center Stage",
    rearCamera: "12MP Wide",
    biometrics: "Face ID",
    pencils: ["pro"],
    keyboards: ["magic-pro"],
    wifi: "Wi-Fi 6E",
    bluetooth: "5.3",
    cellular: true,
    weightG: 444,
    thicknessKey: "pro-11-m4",
    colours: ["silver", "space-black"],
    defaultColour: "space-black",
    appleIntelligence: true,
    tagline: "Tandem OLED. Impossibly thin.",
    whoItSuits: "Creators who want the best screen in a carryable size.",
    whyChoose: [
      "Ultra Retina XDR tandem OLED.",
      "About 5.3 mm thin.",
      "Apple Pencil Pro and new Magic Keyboard.",
    ],
    basePriceKes: P["ipad-pro-11-m4"],
    isNew: true,
  },
  {
    id: "ipad-pro-13-m4",
    name: "iPad Pro 13″ M4",
    family: "Pro",
    chipGen: "M4",
    chip: "M4",
    year: 2024,
    screenInches: 13,
    display: {
      diagonal: 13,
      resolution: "2752×2064",
      ppi: 264,
      panel: "Ultra Retina XDR (tandem OLED)",
      brightnessNits: 1000,
      peakHdrNits: 1600,
      refreshHz: 120,
      promotion: true,
      nanoTextureOptional: true,
    },
    cpuCores: "9 or 10-core",
    gpuCores: "10-core",
    memoryGb: [8, 16],
    storageOptions: ["256 GB", "512 GB", "1 TB", "2 TB"],
    batteryHours: 10,
    ports: ["Thunderbolt / USB 4"],
    frontCamera: "12MP landscape Center Stage",
    rearCamera: "12MP Wide",
    biometrics: "Face ID",
    pencils: ["pro"],
    keyboards: ["magic-pro"],
    wifi: "Wi-Fi 6E",
    bluetooth: "5.3",
    cellular: true,
    weightG: 579,
    thicknessKey: "pro-13-m4",
    colours: ["silver", "space-black"],
    defaultColour: "space-black",
    appleIntelligence: true,
    tagline: "The largest, thinnest Pro.",
    whoItSuits: "Illustration, video and Stage Manager on a laptop-class canvas.",
    whyChoose: [
      "13″ tandem OLED at about 5.1 mm.",
      "M4 with Apple Pencil Pro.",
      "Optional nano-texture on 1 and 2 TB.",
    ],
    basePriceKes: P["ipad-pro-13-m4"],
    isNew: true,
  },
  {
    id: "ipad-pro-11-m5",
    name: "iPad Pro 11″ M5",
    family: "Pro",
    chipGen: "M5",
    chip: "M5",
    year: 2025,
    screenInches: 11,
    display: {
      diagonal: 11,
      resolution: "2420×1668",
      ppi: 264,
      panel: "Ultra Retina XDR (tandem OLED)",
      brightnessNits: 1000,
      peakHdrNits: 1600,
      refreshHz: 120,
      promotion: true,
      nanoTextureOptional: true,
    },
    cpuCores: "9 or 10-core",
    gpuCores: "10-core",
    memoryGb: [12, 16],
    storageOptions: ["256 GB", "512 GB", "1 TB", "2 TB"],
    batteryHours: 10,
    ports: ["Thunderbolt / USB 4"],
    frontCamera: "12MP landscape Center Stage",
    rearCamera: "12MP Wide",
    biometrics: "Face ID",
    pencils: ["pro"],
    keyboards: ["magic-pro"],
    wifi: "Wi-Fi 7",
    bluetooth: "5.3",
    cellular: true,
    weightG: 444,
    thicknessKey: "pro-11-m4",
    colours: ["silver", "space-black"],
    defaultColour: "space-black",
    appleIntelligence: true,
    tagline: "Same thin OLED body. Newer silicon.",
    whoItSuits: "Buyers who want the latest Pro chip in 11 inches.",
    whyChoose: [
      "M5 on the M4 design.",
      "Wi-Fi 7 and newer wireless chips on cellular.",
      "Apple's claim: roughly faster CPU and GPU than M4.",
    ],
    basePriceKes: P["ipad-pro-11-m5"],
    checkFinalSpecs: true,
    isNew: true,
  },
  {
    id: "ipad-pro-13-m5",
    name: "iPad Pro 13″ M5",
    family: "Pro",
    chipGen: "M5",
    chip: "M5",
    year: 2025,
    screenInches: 13,
    display: {
      diagonal: 13,
      resolution: "2752×2064",
      ppi: 264,
      panel: "Ultra Retina XDR (tandem OLED)",
      brightnessNits: 1000,
      peakHdrNits: 1600,
      refreshHz: 120,
      promotion: true,
      nanoTextureOptional: true,
    },
    cpuCores: "9 or 10-core",
    gpuCores: "10-core",
    memoryGb: [12, 16],
    storageOptions: ["256 GB", "512 GB", "1 TB", "2 TB"],
    batteryHours: 10,
    ports: ["Thunderbolt / USB 4"],
    frontCamera: "12MP landscape Center Stage",
    rearCamera: "12MP Wide",
    biometrics: "Face ID",
    pencils: ["pro"],
    keyboards: ["magic-pro"],
    wifi: "Wi-Fi 7",
    bluetooth: "5.3",
    cellular: true,
    weightG: 579,
    thicknessKey: "pro-13-m4",
    colours: ["silver", "space-black"],
    defaultColour: "space-black",
    appleIntelligence: true,
    tagline: "Flagship canvas with M5.",
    whoItSuits: "Pros who want the newest chip on the biggest OLED.",
    whyChoose: [
      "13″ Ultra Retina XDR.",
      "M5 with more base memory.",
      "",
    ],
    basePriceKes: P["ipad-pro-13-m5"],
    checkFinalSpecs: true,
    isNew: true,
  },

  // -- Air --
  {
    id: "ipad-air-4",
    name: "iPad Air (4th gen)",
    family: "Air",
    chipGen: "A14",
    chip: "A14 Bionic",
    year: 2020,
    generation: "4th gen",
    screenInches: 10.9,
    display: {
      diagonal: 10.9,
      resolution: "2360×1640",
      ppi: 264,
      panel: "Liquid Retina",
      brightnessNits: 500,
      refreshHz: 60,
    },
    cpuCores: "6-core",
    gpuCores: "4-core",
    memoryGb: [4],
    storageOptions: ["64 GB", "256 GB"],
    batteryHours: 10,
    ports: ["USB-C"],
    frontCamera: "7MP",
    rearCamera: "12MP Wide",
    biometrics: "Touch ID",
    pencils: ["2nd"],
    keyboards: ["magic-air"],
    wifi: "Wi-Fi 6",
    bluetooth: "5.0",
    cellular: true,
    weightG: 458,
    thicknessKey: "air",
    colours: ["space-gray", "silver", "rose-gold", "green", "sky-blue"],
    defaultColour: "sky-blue",
    appleIntelligence: false,
    tagline: "The modern Air shape starts here.",
    whoItSuits: "Everyday use on a value Air - check condition.",
    whyChoose: [
      "10.9″ Liquid Retina.",
      "USB-C and Touch ID.",
      "Apple Pencil (2nd gen).",
    ],
    basePriceKes: P["ipad-air-4"],
    overviewOnly: true,
  },
  {
    id: "ipad-air-5",
    name: "iPad Air (5th gen)",
    family: "Air",
    chipGen: "M1",
    chip: "M1",
    year: 2022,
    generation: "5th gen",
    screenInches: 10.9,
    display: {
      diagonal: 10.9,
      resolution: "2360×1640",
      ppi: 264,
      panel: "Liquid Retina",
      brightnessNits: 500,
      refreshHz: 60,
    },
    cpuCores: "8-core",
    gpuCores: "8-core",
    memoryGb: [8],
    storageOptions: ["64 GB", "256 GB"],
    batteryHours: 10,
    ports: ["USB-C"],
    frontCamera: "12MP Ultra Wide Center Stage",
    rearCamera: "12MP Wide",
    biometrics: "Touch ID",
    pencils: ["2nd"],
    keyboards: ["magic-air"],
    wifi: "Wi-Fi 6",
    bluetooth: "5.0",
    cellular: true,
    weightG: 461,
    thicknessKey: "air",
    colours: ["space-gray", "starlight", "pink", "purple", "blue"],
    defaultColour: "blue",
    appleIntelligence: true,
    tagline: "M1 in the Air.",
    whoItSuits: "Students and creatives who want M1 without Pro price.",
    whyChoose: [
      "M1 and Apple Intelligence.",
      "Center Stage front camera.",
      "Five colours.",
    ],
    basePriceKes: P["ipad-air-5"],
    overviewOnly: true,
  },
  {
    id: "ipad-air-11-m2",
    name: "iPad Air 11″ M2",
    family: "Air",
    chipGen: "M2",
    chip: "M2",
    year: 2024,
    screenInches: 11,
    display: {
      diagonal: 11,
      resolution: "2360×1640",
      ppi: 264,
      panel: "Liquid Retina",
      brightnessNits: 500,
      refreshHz: 60,
    },
    cpuCores: "8-core",
    gpuCores: "10-core",
    memoryGb: [8],
    storageOptions: ["128 GB", "256 GB", "512 GB", "1 TB"],
    batteryHours: 10,
    ports: ["USB-C"],
    frontCamera: "12MP landscape Center Stage",
    rearCamera: "12MP Wide",
    biometrics: "Touch ID",
    pencils: ["pro", "usb-c"],
    keyboards: ["magic-air"],
    wifi: "Wi-Fi 6E",
    bluetooth: "5.3",
    cellular: true,
    weightG: 462,
    thicknessKey: "air",
    colours: ["blue", "purple", "space-gray", "starlight"],
    defaultColour: "blue",
    appleIntelligence: true,
    tagline: "Two sizes. Pencil Pro. Everyday power.",
    whoItSuits: "Most people who draw, study or work lightly.",
    whyChoose: [
      "Apple Pencil Pro support.",
      "Landscape Center Stage camera.",
      "Apple Intelligence.",
    ],
    basePriceKes: P["ipad-air-11-m2"],
  },
  {
    id: "ipad-air-13-m2",
    name: "iPad Air 13″ M2",
    family: "Air",
    chipGen: "M2",
    chip: "M2",
    year: 2024,
    screenInches: 13,
    display: {
      diagonal: 13,
      resolution: "2732×2048",
      ppi: 264,
      panel: "Liquid Retina",
      brightnessNits: 600,
      refreshHz: 60,
    },
    cpuCores: "8-core",
    gpuCores: "10-core",
    memoryGb: [8],
    storageOptions: ["128 GB", "256 GB", "512 GB", "1 TB"],
    batteryHours: 10,
    ports: ["USB-C"],
    frontCamera: "12MP landscape Center Stage",
    rearCamera: "12MP Wide",
    biometrics: "Touch ID",
    pencils: ["pro", "usb-c"],
    keyboards: ["magic-air"],
    wifi: "Wi-Fi 6E",
    bluetooth: "5.3",
    cellular: true,
    weightG: 617,
    thicknessKey: "air",
    colours: ["blue", "purple", "space-gray", "starlight"],
    defaultColour: "blue",
    appleIntelligence: true,
    tagline: "Air room without Pro price.",
    whoItSuits: "Notes, reading and light creative work on a larger canvas.",
    whyChoose: [
      "13″ Liquid Retina at about 600 nits.",
      "Pencil Pro and Magic Keyboard.",
      "Same colours as 11″ Air.",
    ],
    basePriceKes: P["ipad-air-13-m2"],
  },
  {
    id: "ipad-air-11-m3",
    name: "iPad Air 11″ M3",
    family: "Air",
    chipGen: "M3",
    chip: "M3",
    year: 2025,
    screenInches: 11,
    display: {
      diagonal: 11,
      resolution: "2360×1640",
      ppi: 264,
      panel: "Liquid Retina",
      brightnessNits: 500,
      refreshHz: 60,
    },
    cpuCores: "8-core",
    gpuCores: "9-core",
    memoryGb: [8],
    storageOptions: ["128 GB", "256 GB", "512 GB", "1 TB"],
    batteryHours: 10,
    ports: ["USB-C"],
    frontCamera: "12MP landscape Center Stage",
    rearCamera: "12MP Wide",
    biometrics: "Touch ID",
    pencils: ["pro", "usb-c"],
    keyboards: ["magic-air"],
    wifi: "Wi-Fi 6E",
    bluetooth: "5.3",
    cellular: true,
    weightG: 462,
    thicknessKey: "air",
    colours: ["blue", "purple", "space-gray", "starlight"],
    defaultColour: "purple",
    appleIntelligence: true,
    tagline: "M3 in the everyday Air.",
    whoItSuits: "Buyers who want a step up from M2 without going Pro.",
    whyChoose: [
      "M3 with Pencil Pro.",
      "Works with the newer Magic Keyboard.",
      "Same thin Air body.",
    ],
    basePriceKes: P["ipad-air-11-m3"],
  },
  {
    id: "ipad-air-13-m3",
    name: "iPad Air 13″ M3",
    family: "Air",
    chipGen: "M3",
    chip: "M3",
    year: 2025,
    screenInches: 13,
    display: {
      diagonal: 13,
      resolution: "2732×2048",
      ppi: 264,
      panel: "Liquid Retina",
      brightnessNits: 600,
      refreshHz: 60,
    },
    cpuCores: "8-core",
    gpuCores: "9-core",
    memoryGb: [8],
    storageOptions: ["128 GB", "256 GB", "512 GB", "1 TB"],
    batteryHours: 10,
    ports: ["USB-C"],
    frontCamera: "12MP landscape Center Stage",
    rearCamera: "12MP Wide",
    biometrics: "Touch ID",
    pencils: ["pro", "usb-c"],
    keyboards: ["magic-air"],
    wifi: "Wi-Fi 6E",
    bluetooth: "5.3",
    cellular: true,
    weightG: 617,
    thicknessKey: "air",
    colours: ["blue", "purple", "space-gray", "starlight"],
    defaultColour: "purple",
    appleIntelligence: true,
    tagline: "Bigger Air with M3.",
    whoItSuits: "Split-screen work and drawing on 13 inches.",
    whyChoose: [
      "13″ at 600 nits.",
      "M3 and Pencil Pro.",
      "Apple Intelligence.",
    ],
    basePriceKes: P["ipad-air-13-m3"],
  },
  {
    id: "ipad-air-11-m4",
    name: "iPad Air 11″ M4",
    family: "Air",
    chipGen: "M4",
    chip: "M4",
    year: 2026,
    screenInches: 11,
    display: {
      diagonal: 11,
      resolution: "2360×1640",
      ppi: 264,
      panel: "Liquid Retina",
      brightnessNits: 500,
      refreshHz: 60,
    },
    cpuCores: "8-core (3P+5E)",
    gpuCores: "9-core",
    memoryGb: [12],
    storageOptions: ["128 GB", "256 GB", "512 GB", "1 TB"],
    batteryHours: 10,
    ports: ["USB-C"],
    frontCamera: "12MP landscape Center Stage",
    rearCamera: "12MP Wide",
    biometrics: "Touch ID",
    pencils: ["pro", "usb-c"],
    keyboards: ["magic-air"],
    wifi: "Wi-Fi 7",
    bluetooth: "6",
    cellular: true,
    weightG: 462,
    thicknessKey: "air",
    colours: ["blue", "purple", "starlight", "space-gray"],
    defaultColour: "blue",
    appleIntelligence: true,
    tagline: "Latest Air silicon. Everyday size.",
    whoItSuits: "Buyers waiting for the newest Air in 11 inches.",
    whyChoose: [
      "M4 with 12 GB memory.",
      "Wi-Fi 7.",
      "",
    ],
    basePriceKes: P["ipad-air-11-m4"],
    checkFinalSpecs: true,
    isNew: true,
  },
  {
    id: "ipad-air-13-m4",
    name: "iPad Air 13″ M4",
    family: "Air",
    chipGen: "M4",
    chip: "M4",
    year: 2026,
    screenInches: 13,
    display: {
      diagonal: 13,
      resolution: "2732×2048",
      ppi: 264,
      panel: "Liquid Retina",
      brightnessNits: 600,
      refreshHz: 60,
    },
    cpuCores: "8-core (3P+5E)",
    gpuCores: "9-core",
    memoryGb: [12],
    storageOptions: ["128 GB", "256 GB", "512 GB", "1 TB"],
    batteryHours: 10,
    ports: ["USB-C"],
    frontCamera: "12MP landscape Center Stage",
    rearCamera: "12MP Wide",
    biometrics: "Touch ID",
    pencils: ["pro", "usb-c"],
    keyboards: ["magic-air"],
    wifi: "Wi-Fi 7",
    bluetooth: "6",
    cellular: true,
    weightG: 617,
    thicknessKey: "air",
    colours: ["blue", "purple", "starlight", "space-gray"],
    defaultColour: "blue",
    appleIntelligence: true,
    tagline: "Newest large Air.",
    whoItSuits: "People who want Air size with the latest chip.",
    whyChoose: [
      "M4 and 12 GB memory.",
      "13″ at 600 nits.",
      "",
    ],
    basePriceKes: P["ipad-air-13-m4"],
    checkFinalSpecs: true,
    isNew: true,
  },

  // -- mini --
  {
    id: "ipad-mini-6",
    name: "iPad mini (6th gen)",
    family: "mini",
    chipGen: "A15",
    chip: "A15 Bionic",
    year: 2021,
    generation: "6th gen",
    screenInches: 8.3,
    display: {
      diagonal: 8.3,
      resolution: "2266×1488",
      ppi: 326,
      panel: "Liquid Retina",
      brightnessNits: 500,
      refreshHz: 60,
    },
    cpuCores: "6-core",
    gpuCores: "5-core",
    memoryGb: [4],
    storageOptions: ["64 GB", "256 GB"],
    batteryHours: 10,
    ports: ["USB-C"],
    frontCamera: "12MP Ultra Wide Center Stage",
    rearCamera: "12MP Wide",
    biometrics: "Touch ID",
    pencils: ["2nd"],
    keyboards: ["none"],
    wifi: "Wi-Fi 6",
    bluetooth: "5.0",
    cellular: true,
    weightG: 293,
    thicknessKey: "mini",
    colours: ["starlight", "space-gray", "pink", "purple"],
    defaultColour: "purple",
    appleIntelligence: false,
    tagline: "All-screen mini.",
    whoItSuits: "Reading, travel and one-hand notes.",
    whyChoose: [
      "8.3″ Liquid Retina at 326 ppi.",
      "About 293 g.",
      "Apple Pencil (2nd gen).",
    ],
    basePriceKes: P["ipad-mini-6"],
    overviewOnly: true,
  },
  {
    id: "ipad-mini-a17-pro",
    name: "iPad mini (A17 Pro)",
    family: "mini",
    chipGen: "A17",
    chip: "A17 Pro",
    year: 2024,
    screenInches: 8.3,
    display: {
      diagonal: 8.3,
      resolution: "2266×1488",
      ppi: 326,
      panel: "Liquid Retina",
      brightnessNits: 500,
      refreshHz: 60,
    },
    cpuCores: "6-core",
    gpuCores: "5-core",
    memoryGb: [8],
    storageOptions: ["128 GB", "256 GB", "512 GB"],
    batteryHours: 10,
    ports: ["USB-C"],
    frontCamera: "12MP Ultra Wide Center Stage",
    rearCamera: "12MP Wide",
    biometrics: "Touch ID",
    pencils: ["pro", "usb-c"],
    keyboards: ["none"],
    wifi: "Wi-Fi 6E",
    bluetooth: "5.3",
    cellular: true,
    weightG: 293,
    thicknessKey: "mini",
    colours: ["blue", "purple", "starlight", "space-gray"],
    defaultColour: "blue",
    appleIntelligence: true,
    tagline: "Pocket Pro. Pencil Pro.",
    whoItSuits: "Travel, comics, notes - and Apple Intelligence on the go.",
    whyChoose: [
      "A17 Pro with Apple Intelligence.",
      "Apple Pencil Pro.",
      "Still about 293 g.",
    ],
    basePriceKes: P["ipad-mini-a17-pro"],
    isNew: true,
  },

  // -- standard iPad --
  {
    id: "ipad-8",
    name: "iPad (8th gen)",
    family: "iPad",
    chipGen: "A12",
    chip: "A12 Bionic",
    year: 2020,
    generation: "8th gen",
    screenInches: 10.2,
    display: {
      diagonal: 10.2,
      resolution: "2160×1620",
      ppi: 264,
      panel: "Retina",
      brightnessNits: 500,
      refreshHz: 60,
    },
    cpuCores: "6-core",
    gpuCores: "4-core",
    memoryGb: [3],
    storageOptions: ["32 GB", "128 GB"],
    batteryHours: 10,
    ports: ["Lightning"],
    frontCamera: "1.2MP",
    rearCamera: "8MP",
    biometrics: "Touch ID",
    pencils: ["1st"],
    keyboards: ["smart-keyboard"],
    wifi: "Wi-Fi 5",
    bluetooth: "4.2",
    cellular: true,
    weightG: 490,
    thicknessKey: "ipad",
    colours: ["space-gray", "silver", "gold"],
    defaultColour: "space-gray",
    appleIntelligence: false,
    tagline: "Home-button classic.",
    whoItSuits: "Kids and first tablets on a tight budget - check condition.",
    whyChoose: [
      "Familiar Home button.",
      "Apple Pencil (1st gen).",
      "Lowest sample price in the range.",
    ],
    basePriceKes: P["ipad-8"],
    overviewOnly: true,
  },
  {
    id: "ipad-9",
    name: "iPad (9th gen)",
    family: "iPad",
    chipGen: "A13",
    chip: "A13 Bionic",
    year: 2021,
    generation: "9th gen",
    screenInches: 10.2,
    display: {
      diagonal: 10.2,
      resolution: "2160×1620",
      ppi: 264,
      panel: "Retina",
      brightnessNits: 500,
      refreshHz: 60,
    },
    cpuCores: "6-core",
    gpuCores: "4-core",
    memoryGb: [3],
    storageOptions: ["64 GB", "256 GB"],
    batteryHours: 10,
    ports: ["Lightning"],
    frontCamera: "12MP Ultra Wide Center Stage",
    rearCamera: "8MP",
    biometrics: "Touch ID",
    pencils: ["1st"],
    keyboards: ["smart-keyboard"],
    wifi: "Wi-Fi 5",
    bluetooth: "4.2",
    cellular: true,
    weightG: 487,
    thicknessKey: "ipad",
    colours: ["space-gray", "silver"],
    defaultColour: "space-gray",
    appleIntelligence: false,
    tagline: "Center Stage on the classic iPad.",
    whoItSuits: "Video calls and school on a budget.",
    whyChoose: [
      "Center Stage front camera.",
      "True Tone display.",
      "Still Lightning - plan adapters.",
    ],
    basePriceKes: P["ipad-9"],
    overviewOnly: true,
  },
  {
    id: "ipad-10",
    name: "iPad (10th gen)",
    family: "iPad",
    chipGen: "A14",
    chip: "A14 Bionic",
    year: 2022,
    generation: "10th gen",
    screenInches: 10.9,
    display: {
      diagonal: 10.9,
      resolution: "2360×1640",
      ppi: 264,
      panel: "Liquid Retina",
      brightnessNits: 500,
      refreshHz: 60,
    },
    cpuCores: "6-core",
    gpuCores: "4-core",
    memoryGb: [4],
    storageOptions: ["64 GB", "256 GB"],
    batteryHours: 10,
    ports: ["USB-C"],
    frontCamera: "12MP landscape Center Stage",
    rearCamera: "12MP Wide",
    biometrics: "Touch ID",
    pencils: ["1st", "usb-c"],
    keyboards: ["magic-folio"],
    wifi: "Wi-Fi 6",
    bluetooth: "5.2",
    cellular: true,
    weightG: 477,
    thicknessKey: "ipad",
    colours: ["blue", "pink", "yellow", "silver"],
    defaultColour: "blue",
    appleIntelligence: false,
    tagline: "Colourful. USB-C. Family favourite.",
    whoItSuits: "Kids, families and first serious tablets.",
    whyChoose: [
      "All-screen colourful design.",
      "USB-C and landscape Center Stage.",
      "Magic Keyboard Folio option.",
    ],
    basePriceKes: P["ipad-10"],
  },
  {
    id: "ipad-a16",
    name: "iPad (A16)",
    family: "iPad",
    chipGen: "A16",
    chip: "A16",
    year: 2025,
    screenInches: 11,
    display: {
      diagonal: 11,
      resolution: "2360×1640",
      ppi: 264,
      panel: "Liquid Retina",
      brightnessNits: 500,
      refreshHz: 60,
    },
    cpuCores: "6-core",
    gpuCores: "5-core",
    memoryGb: [6],
    storageOptions: ["128 GB", "256 GB", "512 GB"],
    batteryHours: 10,
    ports: ["USB-C"],
    frontCamera: "12MP landscape Center Stage",
    rearCamera: "12MP Wide",
    biometrics: "Touch ID",
    pencils: ["1st", "usb-c"],
    keyboards: ["magic-folio"],
    wifi: "Wi-Fi 6",
    bluetooth: "5.3",
    cellular: true,
    weightG: 477,
    thicknessKey: "ipad",
    colours: ["blue", "pink", "yellow", "silver"],
    defaultColour: "pink",
    appleIntelligence: false,
    tagline: "Newest standard iPad. Still approachable.",
    whoItSuits: "Families who want more storage and a newer chip.",
    whyChoose: [
      "A16 with storage from 128 GB.",
      "Same colourful USB-C design.",
      "Does not support Apple Intelligence.",
    ],
    basePriceKes: P["ipad-a16"],
    checkFinalSpecs: true,
    isNew: true,
  },
];

export function getIpadModel(id: string): IpadModel | undefined {
  return ipadModels.find((m) => m.id === id);
}

export function ipadModelsByFamily(family: IpadFamily): IpadModel[] {
  return ipadModels.filter((m) => m.family === family);
}

export function lowestIpadPrice(family?: IpadFamily): number {
  const list = family ? ipadModelsByFamily(family) : ipadModels;
  return Math.min(...list.map((m) => m.basePriceKes));
}

export function ipadSubline(model: IpadModel): string {
  return `${model.display.diagonal}″ · ${model.chip} · ${model.storageOptions[0]}`;
}

export function supportsPencilPro(model: IpadModel): boolean {
  return model.pencils.includes("pro");
}
