/**
 * MacBook Air + Pro catalog (Apple silicon M1 - M5, 2020+).
 * Specs from Apple's published figures in the Mac prompt.
 * Owner: re-verify every number on apple.com before launch.
 * M5 rows carry checkFinalSpecs - lower confidence until confirmed.
 */

import { macBasePricesKes } from "./config";

export type MacFamily = "Air" | "Pro";
export type MacChipGen = "M1" | "M2" | "M3" | "M4" | "M5";

export type MacModel = {
  id: keyof typeof macBasePricesKes;
  name: string;
  family: MacFamily;
  chipGen: MacChipGen;
  /** Display name for chip tier, e.g. "M4 Pro" */
  chip: string;
  year: number;
  screenInches: 13 | 14 | 15 | 16;
  cpuCores: string;
  gpuCores: string;
  memoryOptionsGb: number[];
  storageOptions: string[];
  display: {
    diagonal: number;
    resolution: string;
    ppi: number;
    panel: string;
    brightnessNits: number;
    peakHdrNits?: number;
    refreshHz: number;
    promotion?: boolean;
    nanoTextureOptional?: boolean;
  };
  batteryVideoHours: number;
  batteryWebHours?: number;
  charging: string;
  ports: string[];
  camera: string;
  speakers: string;
  weightKg: number;
  colours: string[];
  wifi: string;
  bluetooth: string;
  tagline: string;
  whoItSuits: string;
  whyChoose: [string, string, string];
  basePriceKes: number;
  defaultColour: string;
  fanless: boolean;
  touchBar?: boolean;
  magsafe: boolean;
  externalDisplays: string;
  thicknessKey: "air-m1" | "air-13-m2-later" | "air-15" | "pro-13" | "pro-14" | "pro-16";
  /** Missing dedicated store colour shots - use overview as main */
  overviewOnly?: boolean;
  /** Show "Check final specs" badge */
  checkFinalSpecs?: boolean;
  notes?: string;
  isNew?: boolean;
};

const P = macBasePricesKes;

/** Owner: re-verify all specs against apple.com before launch. */
export const macModels: MacModel[] = [
  // -- Air --
  {
    id: "macbook-air-13-m1",
    name: "MacBook Air 13″ M1",
    family: "Air",
    chipGen: "M1",
    chip: "M1",
    year: 2020,
    screenInches: 13,
    cpuCores: "8-core",
    gpuCores: "7 or 8-core",
    memoryOptionsGb: [8, 16],
    storageOptions: ["256GB", "512GB", "1TB", "2TB"],
    display: {
      diagonal: 13.3,
      resolution: "2560×1600",
      ppi: 227,
      panel: "LED IPS · P3",
      brightnessNits: 400,
      refreshHz: 60,
    },
    batteryVideoHours: 18,
    batteryWebHours: 15,
    charging: "USB-C",
    ports: ["2× Thunderbolt / USB 4", "3.5 mm headphone"],
    camera: "720p FaceTime HD",
    speakers: "Stereo speakers",
    weightKg: 1.29,
    colours: ["space-gray", "silver", "gold"],
    wifi: "Wi-Fi 6",
    bluetooth: "Bluetooth 5.0",
    tagline: "The original Apple silicon Air.",
    whoItSuits: "Everyday work, study, and light creative tasks on a budget.",
    whyChoose: [
      "Still capable for browsing, docs, and streaming.",
      "Fanless and quiet.",
      "Lowest sample price in the Air line - check battery health on older units.",
    ],
    basePriceKes: P["macbook-air-13-m1"],
    defaultColour: "space-gray",
    fanless: true,
    magsafe: false,
    externalDisplays: "One external display",
    thicknessKey: "air-m1",
    notes: "Store shots use the 2018-labelled chassis (identical design).",
  },
  {
    id: "macbook-air-13-m2",
    name: "MacBook Air 13″ M2",
    family: "Air",
    chipGen: "M2",
    chip: "M2",
    year: 2022,
    screenInches: 13,
    cpuCores: "8-core",
    gpuCores: "8 or 10-core",
    memoryOptionsGb: [8, 16, 24],
    storageOptions: ["256GB", "512GB", "1TB", "2TB"],
    display: {
      diagonal: 13.6,
      resolution: "2560×1664",
      ppi: 224,
      panel: "Liquid Retina",
      brightnessNits: 500,
      refreshHz: 60,
    },
    batteryVideoHours: 18,
    charging: "MagSafe 3 + USB-C",
    ports: ["MagSafe 3", "2× Thunderbolt / USB 4", "3.5 mm headphone"],
    camera: "1080p FaceTime HD",
    speakers: "Four-speaker system",
    weightKg: 1.24,
    colours: ["midnight", "starlight", "space-gray", "silver"],
    wifi: "Wi-Fi 6",
    bluetooth: "Bluetooth 5.0",
    tagline: "Redesigned Air. MagSafe returns.",
    whoItSuits: "Students and everyday users who want the thinner chassis.",
    whyChoose: [
      "Liquid Retina and MagSafe 3.",
      "Four-speaker sound.",
      "Main photo uses the colour overview until a store shot is added.",
    ],
    basePriceKes: P["macbook-air-13-m2"],
    defaultColour: "midnight",
    fanless: true,
    magsafe: true,
    externalDisplays: "One external display",
    thicknessKey: "air-13-m2-later",
    overviewOnly: true,
  },
  {
    id: "macbook-air-15-m2",
    name: "MacBook Air 15″ M2",
    family: "Air",
    chipGen: "M2",
    chip: "M2",
    year: 2023,
    screenInches: 15,
    cpuCores: "8-core",
    gpuCores: "10-core",
    memoryOptionsGb: [8, 16, 24],
    storageOptions: ["256GB", "512GB", "1TB", "2TB"],
    display: {
      diagonal: 15.3,
      resolution: "2880×1864",
      ppi: 224,
      panel: "Liquid Retina",
      brightnessNits: 500,
      refreshHz: 60,
    },
    batteryVideoHours: 18,
    charging: "MagSafe 3 + USB-C",
    ports: ["MagSafe 3", "2× Thunderbolt / USB 4", "3.5 mm headphone"],
    camera: "1080p FaceTime HD",
    speakers: "Six-speaker system",
    weightKg: 1.51,
    colours: ["midnight", "starlight", "space-gray", "silver"],
    wifi: "Wi-Fi 6",
    bluetooth: "Bluetooth 5.0",
    tagline: "A big screen without the Pro bulk.",
    whoItSuits: "Writers and multitaskers who want more canvas, still thin.",
    whyChoose: [
      "15.3″ Liquid Retina in an Air body.",
      "Six-speaker audio.",
      "Same MagSafe charging as later Airs.",
    ],
    basePriceKes: P["macbook-air-15-m2"],
    defaultColour: "midnight",
    fanless: true,
    magsafe: true,
    externalDisplays: "One external display",
    thicknessKey: "air-15",
  },
  {
    id: "macbook-air-13-m3",
    name: "MacBook Air 13″ M3",
    family: "Air",
    chipGen: "M3",
    chip: "M3",
    year: 2024,
    screenInches: 13,
    cpuCores: "8-core",
    gpuCores: "8 or 10-core",
    memoryOptionsGb: [8, 16, 24],
    storageOptions: ["256GB", "512GB", "1TB", "2TB"],
    display: {
      diagonal: 13.6,
      resolution: "2560×1664",
      ppi: 224,
      panel: "Liquid Retina",
      brightnessNits: 500,
      refreshHz: 60,
    },
    batteryVideoHours: 18,
    charging: "MagSafe 3 + USB-C",
    ports: ["MagSafe 3", "2× Thunderbolt / USB 4", "3.5 mm headphone"],
    camera: "1080p FaceTime HD",
    speakers: "Four-speaker system",
    weightKg: 1.24,
    colours: ["midnight", "starlight", "space-gray", "silver"],
    wifi: "Wi-Fi 6E",
    bluetooth: "Bluetooth 5.3",
    tagline: "Two displays with the lid closed.",
    whoItSuits: "Desk setups that need a second and third screen.",
    whyChoose: [
      "Supports two external displays with the lid closed.",
      "Wi-Fi 6E.",
      "Same thin 13″ chassis as M2.",
    ],
    basePriceKes: P["macbook-air-13-m3"],
    defaultColour: "midnight",
    fanless: true,
    magsafe: true,
    externalDisplays: "Up to two external displays with the lid closed",
    thicknessKey: "air-13-m2-later",
  },
  {
    id: "macbook-air-15-m3",
    name: "MacBook Air 15″ M3",
    family: "Air",
    chipGen: "M3",
    chip: "M3",
    year: 2024,
    screenInches: 15,
    cpuCores: "8-core",
    gpuCores: "10-core",
    memoryOptionsGb: [8, 16, 24],
    storageOptions: ["256GB", "512GB", "1TB", "2TB"],
    display: {
      diagonal: 15.3,
      resolution: "2880×1864",
      ppi: 224,
      panel: "Liquid Retina",
      brightnessNits: 500,
      refreshHz: 60,
    },
    batteryVideoHours: 18,
    charging: "MagSafe 3 + USB-C",
    ports: ["MagSafe 3", "2× Thunderbolt / USB 4", "3.5 mm headphone"],
    camera: "1080p FaceTime HD",
    speakers: "Six-speaker system",
    weightKg: 1.51,
    colours: ["midnight", "starlight", "space-gray", "silver"],
    wifi: "Wi-Fi 6E",
    bluetooth: "Bluetooth 5.3",
    tagline: "15″ Air with M3 and dual-display desk support.",
    whoItSuits: "People who want space without a Pro.",
    whyChoose: [
      "15″ canvas plus M3 graphics.",
      "Two external displays with lid closed.",
      "Main photo uses colour overview until a store shot arrives.",
    ],
    basePriceKes: P["macbook-air-15-m3"],
    defaultColour: "midnight",
    fanless: true,
    magsafe: true,
    externalDisplays: "Up to two external displays with the lid closed",
    thicknessKey: "air-15",
    overviewOnly: true,
  },
  {
    id: "macbook-air-13-m4",
    name: "MacBook Air 13″ M4",
    family: "Air",
    chipGen: "M4",
    chip: "M4",
    year: 2025,
    screenInches: 13,
    cpuCores: "10-core",
    gpuCores: "8 or 10-core",
    memoryOptionsGb: [16, 24, 32],
    storageOptions: ["256GB", "512GB", "1TB", "2TB"],
    display: {
      diagonal: 13.6,
      resolution: "2560×1664",
      ppi: 224,
      panel: "Liquid Retina",
      brightnessNits: 500,
      refreshHz: 60,
    },
    batteryVideoHours: 18,
    charging: "MagSafe 3 + USB-C",
    ports: ["MagSafe 3", "2× Thunderbolt 4", "3.5 mm headphone"],
    camera: "12MP Center Stage with Desk View",
    speakers: "Four-speaker system",
    weightKg: 1.24,
    colours: ["midnight", "starlight", "silver", "sky-blue"],
    wifi: "Wi-Fi 6E",
    bluetooth: "Bluetooth 5.3",
    tagline: "16 GB base. Sky Blue. Center Stage.",
    whoItSuits: "Students and everyday buyers starting in 2025 - 2026.",
    whyChoose: [
      "16 GB memory as the base configuration.",
      "12MP Center Stage camera with Desk View.",
      "Two external displays with the lid open.",
    ],
    basePriceKes: P["macbook-air-13-m4"],
    defaultColour: "sky-blue",
    fanless: true,
    magsafe: true,
    externalDisplays: "Up to two external displays with the lid open",
    thicknessKey: "air-13-m2-later",
    isNew: true,
  },
  {
    id: "macbook-air-15-m4",
    name: "MacBook Air 15″ M4",
    family: "Air",
    chipGen: "M4",
    chip: "M4",
    year: 2025,
    screenInches: 15,
    cpuCores: "10-core",
    gpuCores: "10-core",
    memoryOptionsGb: [16, 24, 32],
    storageOptions: ["256GB", "512GB", "1TB", "2TB"],
    display: {
      diagonal: 15.3,
      resolution: "2880×1864",
      ppi: 224,
      panel: "Liquid Retina",
      brightnessNits: 500,
      refreshHz: 60,
    },
    batteryVideoHours: 18,
    charging: "MagSafe 3 + USB-C",
    ports: ["MagSafe 3", "2× Thunderbolt 4", "3.5 mm headphone"],
    camera: "12MP Center Stage with Desk View",
    speakers: "Six-speaker system",
    weightKg: 1.51,
    colours: ["midnight", "starlight", "silver", "sky-blue"],
    wifi: "Wi-Fi 6E",
    bluetooth: "Bluetooth 5.3",
    tagline: "The big Air with M4.",
    whoItSuits: "Creators who want space and silence.",
    whyChoose: [
      "15″ Liquid Retina with M4.",
      "16 GB base memory.",
      "Center Stage and Desk View for meetings.",
    ],
    basePriceKes: P["macbook-air-15-m4"],
    defaultColour: "sky-blue",
    fanless: true,
    magsafe: true,
    externalDisplays: "Up to two external displays with the lid open",
    thicknessKey: "air-15",
    isNew: true,
  },
  {
    id: "macbook-air-13-m5",
    name: "MacBook Air 13″ M5",
    family: "Air",
    chipGen: "M5",
    chip: "M5",
    year: 2026,
    screenInches: 13,
    cpuCores: "10-core (4P + 6E)",
    gpuCores: "8 or 10-core",
    memoryOptionsGb: [16, 24, 32],
    storageOptions: ["512GB", "1TB", "2TB", "4TB"],
    display: {
      diagonal: 13.6,
      resolution: "2560×1664",
      ppi: 224,
      panel: "Liquid Retina",
      brightnessNits: 500,
      refreshHz: 60,
    },
    batteryVideoHours: 18,
    batteryWebHours: 15,
    charging: "MagSafe 3 (40W adapter, 60W max) + USB-C",
    ports: ["MagSafe 3", "2× Thunderbolt 4", "3.5 mm headphone"],
    camera: "12MP Center Stage with Desk View",
    speakers: "Four-speaker system",
    weightKg: 1.23,
    colours: ["sky-blue", "silver", "starlight", "midnight"],
    wifi: "Wi-Fi 7",
    bluetooth: "Bluetooth 6",
    tagline: "Newest Air. Check final specs before order.",
    whoItSuits: "Buyers who want the latest Air silicon.",
    whyChoose: [
      "Newest Apple silicon in the Air line.",
      "Wi-Fi 7 and Bluetooth 6.",
      "Specs flagged until the owner verifies Apple’s page.",
    ],
    basePriceKes: P["macbook-air-13-m5"],
    defaultColour: "sky-blue",
    fanless: true,
    magsafe: true,
    externalDisplays: "Confirm on Apple’s page before launch",
    thicknessKey: "air-13-m2-later",
    overviewOnly: true,
    checkFinalSpecs: true,
    isNew: true,
  },
  {
    id: "macbook-air-15-m5",
    name: "MacBook Air 15″ M5",
    family: "Air",
    chipGen: "M5",
    chip: "M5",
    year: 2026,
    screenInches: 15,
    cpuCores: "10-core",
    gpuCores: "10-core",
    memoryOptionsGb: [16, 24, 32],
    storageOptions: ["512GB", "1TB", "2TB", "4TB"],
    display: {
      diagonal: 15.3,
      resolution: "2880×1864",
      ppi: 224,
      panel: "Liquid Retina",
      brightnessNits: 500,
      refreshHz: 60,
    },
    batteryVideoHours: 18,
    batteryWebHours: 15,
    charging: "MagSafe 3 + USB-C",
    ports: ["MagSafe 3", "2× Thunderbolt 4", "3.5 mm headphone"],
    camera: "12MP Center Stage with Desk View",
    speakers: "Six-speaker system",
    weightKg: 1.51,
    colours: ["sky-blue", "silver", "starlight", "midnight"],
    wifi: "Wi-Fi 7",
    bluetooth: "Bluetooth 6",
    tagline: "15″ M5 Air - verify every figure before launch.",
    whoItSuits: "Buyers waiting for the latest 15″ Air.",
    whyChoose: [
      "Largest newest Air.",
      "Check final specs flag is on until verified.",
      "Overview image until store shots exist.",
    ],
    basePriceKes: P["macbook-air-15-m5"],
    defaultColour: "sky-blue",
    fanless: true,
    magsafe: true,
    externalDisplays: "Confirm on Apple’s page before launch",
    thicknessKey: "air-15",
    overviewOnly: true,
    checkFinalSpecs: true,
    isNew: true,
  },

  // -- Pro 13 --
  {
    id: "macbook-pro-13-m1",
    name: "MacBook Pro 13″ M1",
    family: "Pro",
    chipGen: "M1",
    chip: "M1",
    year: 2020,
    screenInches: 13,
    cpuCores: "8-core",
    gpuCores: "8-core",
    memoryOptionsGb: [8, 16],
    storageOptions: ["256GB", "512GB", "1TB", "2TB"],
    display: {
      diagonal: 13.3,
      resolution: "2560×1600",
      ppi: 227,
      panel: "Retina",
      brightnessNits: 500,
      refreshHz: 60,
    },
    batteryVideoHours: 20,
    batteryWebHours: 17,
    charging: "USB-C",
    ports: ["2× Thunderbolt / USB 4", "3.5 mm headphone"],
    camera: "720p FaceTime HD",
    speakers: "Stereo speakers",
    weightKg: 1.4,
    colours: ["space-gray", "silver"],
    wifi: "Wi-Fi 6",
    bluetooth: "Bluetooth 5.0",
    tagline: "Active cooling. Touch Bar era.",
    whoItSuits: "Buyers who need a fan and longer sessions on a compact Pro.",
    whyChoose: [
      "Fan for sustained loads.",
      "Touch Bar (unique to 13″ M1/M2 Pro).",
      "Check battery health on older stock.",
    ],
    basePriceKes: P["macbook-pro-13-m1"],
    defaultColour: "space-gray",
    fanless: false,
    touchBar: true,
    magsafe: false,
    externalDisplays: "One external display",
    thicknessKey: "pro-13",
  },
  {
    id: "macbook-pro-13-m2",
    name: "MacBook Pro 13″ M2",
    family: "Pro",
    chipGen: "M2",
    chip: "M2",
    year: 2022,
    screenInches: 13,
    cpuCores: "8-core",
    gpuCores: "10-core",
    memoryOptionsGb: [8, 16, 24],
    storageOptions: ["256GB", "512GB", "1TB", "2TB"],
    display: {
      diagonal: 13.3,
      resolution: "2560×1600",
      ppi: 227,
      panel: "Retina",
      brightnessNits: 500,
      refreshHz: 60,
    },
    batteryVideoHours: 20,
    charging: "USB-C",
    ports: ["2× Thunderbolt / USB 4", "3.5 mm headphone"],
    camera: "720p FaceTime HD",
    speakers: "Stereo speakers",
    weightKg: 1.4,
    colours: ["space-gray", "silver"],
    wifi: "Wi-Fi 6",
    bluetooth: "Bluetooth 5.0",
    tagline: "Last of the Touch Bar Pros.",
    whoItSuits: "Compact Pro buyers who still want active cooling.",
    whyChoose: [
      "M2 in the familiar 13″ Pro body.",
      "Touch Bar retained.",
      "Up to 20 hours video (Apple claim).",
    ],
    basePriceKes: P["macbook-pro-13-m2"],
    defaultColour: "space-gray",
    fanless: false,
    touchBar: true,
    magsafe: false,
    externalDisplays: "One external display",
    thicknessKey: "pro-13",
  },

  // -- Pro 14 / 16 --
  {
    id: "macbook-pro-14-m1-pro",
    name: "MacBook Pro 14″ M1 Pro",
    family: "Pro",
    chipGen: "M1",
    chip: "M1 Pro",
    year: 2021,
    screenInches: 14,
    cpuCores: "8 or 10-core",
    gpuCores: "14 or 16-core",
    memoryOptionsGb: [16, 32],
    storageOptions: ["512GB", "1TB", "2TB", "4TB", "8TB"],
    display: {
      diagonal: 14.2,
      resolution: "3024×1964",
      ppi: 254,
      panel: "Liquid Retina XDR mini-LED",
      brightnessNits: 1000,
      peakHdrNits: 1600,
      refreshHz: 120,
      promotion: true,
    },
    batteryVideoHours: 17,
    charging: "MagSafe 3",
    ports: ["3× Thunderbolt 4", "HDMI", "SDXC", "MagSafe 3", "3.5 mm"],
    camera: "1080p FaceTime HD",
    speakers: "Six-speaker system",
    weightKg: 1.6,
    colours: ["space-gray", "silver"],
    wifi: "Wi-Fi 6",
    bluetooth: "Bluetooth 5.0",
    tagline: "XDR. ProMotion. Full-height keys.",
    whoItSuits: "Creators entering the modern Pro era.",
    whyChoose: [
      "Liquid Retina XDR with ProMotion.",
      "HDMI and SD card built in.",
      "No Touch Bar - full-height function keys.",
    ],
    basePriceKes: P["macbook-pro-14-m1-pro"],
    defaultColour: "space-gray",
    fanless: false,
    magsafe: true,
    externalDisplays: "Up to two external displays (Pro) / more with Max configs",
    thicknessKey: "pro-14",
  },
  {
    id: "macbook-pro-16-m1-pro",
    name: "MacBook Pro 16″ M1 Pro",
    family: "Pro",
    chipGen: "M1",
    chip: "M1 Pro",
    year: 2021,
    screenInches: 16,
    cpuCores: "8 or 10-core",
    gpuCores: "14 or 16-core",
    memoryOptionsGb: [16, 32],
    storageOptions: ["512GB", "1TB", "2TB", "4TB", "8TB"],
    display: {
      diagonal: 16.2,
      resolution: "3456×2234",
      ppi: 254,
      panel: "Liquid Retina XDR mini-LED",
      brightnessNits: 1000,
      peakHdrNits: 1600,
      refreshHz: 120,
      promotion: true,
    },
    batteryVideoHours: 21,
    charging: "MagSafe 3",
    ports: ["3× Thunderbolt 4", "HDMI", "SDXC", "MagSafe 3", "3.5 mm"],
    camera: "1080p FaceTime HD",
    speakers: "Six-speaker system",
    weightKg: 2.1,
    colours: ["space-gray", "silver"],
    wifi: "Wi-Fi 6",
    bluetooth: "Bluetooth 5.0",
    tagline: "The big XDR canvas.",
    whoItSuits: "Video editors and developers who want desk-class space.",
    whyChoose: [
      "16.2″ XDR with ProMotion.",
      "Longest video claim in the M1 Pro line.",
      "Full ports: HDMI, SD, MagSafe.",
    ],
    basePriceKes: P["macbook-pro-16-m1-pro"],
    defaultColour: "space-gray",
    fanless: false,
    magsafe: true,
    externalDisplays: "Up to two external displays (Pro) / more with Max configs",
    thicknessKey: "pro-16",
  },
  {
    id: "macbook-pro-14-m2-pro",
    name: "MacBook Pro 14″ M2 Pro",
    family: "Pro",
    chipGen: "M2",
    chip: "M2 Pro",
    year: 2023,
    screenInches: 14,
    cpuCores: "Up to 12-core",
    gpuCores: "Up to 19-core",
    memoryOptionsGb: [16, 32],
    storageOptions: ["512GB", "1TB", "2TB", "4TB", "8TB"],
    display: {
      diagonal: 14.2,
      resolution: "3024×1964",
      ppi: 254,
      panel: "Liquid Retina XDR",
      brightnessNits: 1000,
      peakHdrNits: 1600,
      refreshHz: 120,
      promotion: true,
    },
    batteryVideoHours: 18,
    charging: "MagSafe 3",
    ports: ["3× Thunderbolt 4", "HDMI 2.1", "SDXC", "MagSafe 3", "3.5 mm"],
    camera: "1080p FaceTime HD",
    speakers: "Six-speaker system",
    weightKg: 1.6,
    colours: ["space-gray", "silver"],
    wifi: "Wi-Fi 6E",
    bluetooth: "Bluetooth 5.3",
    tagline: "HDMI 2.1. Wi-Fi 6E.",
    whoItSuits: "Pro workflows that outgrew M1 Pro.",
    whyChoose: [
      "Stronger Pro/Max silicon options.",
      "HDMI 2.1.",
      "Same XDR body language.",
    ],
    basePriceKes: P["macbook-pro-14-m2-pro"],
    defaultColour: "space-gray",
    fanless: false,
    magsafe: true,
    externalDisplays: "Multiple external displays depending on chip",
    thicknessKey: "pro-14",
  },
  {
    id: "macbook-pro-16-m2-pro",
    name: "MacBook Pro 16″ M2 Pro",
    family: "Pro",
    chipGen: "M2",
    chip: "M2 Pro",
    year: 2023,
    screenInches: 16,
    cpuCores: "Up to 12-core",
    gpuCores: "Up to 19-core",
    memoryOptionsGb: [16, 32],
    storageOptions: ["512GB", "1TB", "2TB", "4TB", "8TB"],
    display: {
      diagonal: 16.2,
      resolution: "3456×2234",
      ppi: 254,
      panel: "Liquid Retina XDR",
      brightnessNits: 1000,
      peakHdrNits: 1600,
      refreshHz: 120,
      promotion: true,
    },
    batteryVideoHours: 22,
    charging: "MagSafe 3",
    ports: ["3× Thunderbolt 4", "HDMI 2.1", "SDXC", "MagSafe 3", "3.5 mm"],
    camera: "1080p FaceTime HD",
    speakers: "Six-speaker system",
    weightKg: 2.1,
    colours: ["space-gray", "silver"],
    wifi: "Wi-Fi 6E",
    bluetooth: "Bluetooth 5.3",
    tagline: "16″ endurance Pro.",
    whoItSuits: "Heavy creative and compile workloads on the go.",
    whyChoose: [
      "Up to 22 h video (Apple claim).",
      "Large XDR panel.",
      "Pro/Max memory headroom available.",
    ],
    basePriceKes: P["macbook-pro-16-m2-pro"],
    defaultColour: "space-gray",
    fanless: false,
    magsafe: true,
    externalDisplays: "Multiple external displays depending on chip",
    thicknessKey: "pro-16",
  },
  {
    id: "macbook-pro-14-m3",
    name: "MacBook Pro 14″ M3",
    family: "Pro",
    chipGen: "M3",
    chip: "M3",
    year: 2023,
    screenInches: 14,
    cpuCores: "8-core",
    gpuCores: "10-core",
    memoryOptionsGb: [8, 16, 24],
    storageOptions: ["512GB", "1TB", "2TB"],
    display: {
      diagonal: 14.2,
      resolution: "3024×1964",
      ppi: 254,
      panel: "Liquid Retina XDR",
      brightnessNits: 1000,
      peakHdrNits: 1600,
      refreshHz: 120,
      promotion: true,
    },
    batteryVideoHours: 22,
    charging: "MagSafe 3",
    ports: ["3× Thunderbolt 4", "HDMI", "SDXC", "MagSafe 3", "3.5 mm"],
    camera: "1080p FaceTime HD",
    speakers: "Six-speaker system",
    weightKg: 1.55,
    colours: ["space-gray", "silver"],
    wifi: "Wi-Fi 6E",
    bluetooth: "Bluetooth 5.3",
    tagline: "XDR Pro at the entry M3 tier.",
    whoItSuits: "Buyers who want ProMotion without Pro/Max silicon.",
    whyChoose: [
      "Full XDR + ProMotion.",
      "Lower entry than M3 Pro.",
      "Space Gray / Silver finishes.",
    ],
    basePriceKes: P["macbook-pro-14-m3"],
    defaultColour: "silver",
    fanless: false,
    magsafe: true,
    externalDisplays: "Up to two external displays",
    thicknessKey: "pro-14",
  },
  {
    id: "macbook-pro-14-m3-pro",
    name: "MacBook Pro 14″ M3 Pro",
    family: "Pro",
    chipGen: "M3",
    chip: "M3 Pro",
    year: 2023,
    screenInches: 14,
    cpuCores: "Up to 12-core",
    gpuCores: "Up to 18-core",
    memoryOptionsGb: [18, 36],
    storageOptions: ["512GB", "1TB", "2TB", "4TB", "8TB"],
    display: {
      diagonal: 14.2,
      resolution: "3024×1964",
      ppi: 254,
      panel: "Liquid Retina XDR",
      brightnessNits: 1000,
      peakHdrNits: 1600,
      refreshHz: 120,
      promotion: true,
    },
    batteryVideoHours: 22,
    charging: "MagSafe 3",
    ports: ["3× Thunderbolt 4", "HDMI", "SDXC", "MagSafe 3", "3.5 mm"],
    camera: "1080p FaceTime HD",
    speakers: "Six-speaker system",
    weightKg: 1.61,
    colours: ["space-black", "silver"],
    wifi: "Wi-Fi 6E",
    bluetooth: "Bluetooth 5.3",
    tagline: "Space Black arrives.",
    whoItSuits: "Pros who need memory headroom and the dark finish.",
    whyChoose: [
      "Space Black option.",
      "Higher memory floors than base M3.",
      "Same XDR ProMotion panel.",
    ],
    basePriceKes: P["macbook-pro-14-m3-pro"],
    defaultColour: "space-black",
    fanless: false,
    magsafe: true,
    externalDisplays: "Multiple external displays",
    thicknessKey: "pro-14",
  },
  {
    id: "macbook-pro-16-m3-pro",
    name: "MacBook Pro 16″ M3 Pro",
    family: "Pro",
    chipGen: "M3",
    chip: "M3 Pro",
    year: 2023,
    screenInches: 16,
    cpuCores: "Up to 12-core",
    gpuCores: "Up to 18-core",
    memoryOptionsGb: [18, 36],
    storageOptions: ["512GB", "1TB", "2TB", "4TB", "8TB"],
    display: {
      diagonal: 16.2,
      resolution: "3456×2234",
      ppi: 254,
      panel: "Liquid Retina XDR",
      brightnessNits: 1000,
      peakHdrNits: 1600,
      refreshHz: 120,
      promotion: true,
    },
    batteryVideoHours: 22,
    charging: "MagSafe 3",
    ports: ["3× Thunderbolt 4", "HDMI", "SDXC", "MagSafe 3", "3.5 mm"],
    camera: "1080p FaceTime HD",
    speakers: "Six-speaker system",
    weightKg: 2.14,
    colours: ["space-black", "silver"],
    wifi: "Wi-Fi 6E",
    bluetooth: "Bluetooth 5.3",
    tagline: "16″ M3 Pro in Space Black.",
    whoItSuits: "Editors and developers who want the large panel.",
    whyChoose: [
      "16″ XDR.",
      "Space Black finish.",
      "Pro memory options.",
    ],
    basePriceKes: P["macbook-pro-16-m3-pro"],
    defaultColour: "space-black",
    fanless: false,
    magsafe: true,
    externalDisplays: "Multiple external displays",
    thicknessKey: "pro-16",
  },
  {
    id: "macbook-pro-14-m4",
    name: "MacBook Pro 14″ M4",
    family: "Pro",
    chipGen: "M4",
    chip: "M4",
    year: 2024,
    screenInches: 14,
    cpuCores: "10-core",
    gpuCores: "10-core",
    memoryOptionsGb: [16, 24, 32],
    storageOptions: ["512GB", "1TB", "2TB"],
    display: {
      diagonal: 14.2,
      resolution: "3024×1964",
      ppi: 254,
      panel: "Liquid Retina XDR",
      brightnessNits: 1000,
      peakHdrNits: 1600,
      refreshHz: 120,
      promotion: true,
      nanoTextureOptional: true,
    },
    batteryVideoHours: 24,
    charging: "MagSafe 3",
    ports: ["3× Thunderbolt 4", "HDMI", "SDXC", "MagSafe 3", "3.5 mm"],
    camera: "12MP Center Stage with Desk View",
    speakers: "Six-speaker system",
    weightKg: 1.55,
    colours: ["silver", "space-black"],
    wifi: "Wi-Fi 6E",
    bluetooth: "Bluetooth 5.3",
    tagline: "24-hour claim. Center Stage. Nano-texture option.",
    whoItSuits: "Pros who want the latest base Pro without Pro silicon.",
    whyChoose: [
      "Up to 24 h video (Apple claim).",
      "12MP Center Stage.",
      "Optional nano-texture glass.",
    ],
    basePriceKes: P["macbook-pro-14-m4"],
    defaultColour: "space-black",
    fanless: false,
    magsafe: true,
    externalDisplays: "Up to two external displays",
    thicknessKey: "pro-14",
    isNew: true,
  },
  {
    id: "macbook-pro-14-m4-pro",
    name: "MacBook Pro 14″ M4 Pro",
    family: "Pro",
    chipGen: "M4",
    chip: "M4 Pro",
    year: 2024,
    screenInches: 14,
    cpuCores: "Up to 14-core",
    gpuCores: "Up to 20-core",
    memoryOptionsGb: [24, 48],
    storageOptions: ["512GB", "1TB", "2TB", "4TB", "8TB"],
    display: {
      diagonal: 14.2,
      resolution: "3024×1964",
      ppi: 254,
      panel: "Liquid Retina XDR",
      brightnessNits: 1000,
      peakHdrNits: 1600,
      refreshHz: 120,
      promotion: true,
      nanoTextureOptional: true,
    },
    batteryVideoHours: 24,
    charging: "MagSafe 3",
    ports: ["3× Thunderbolt 5", "HDMI", "SDXC", "MagSafe 3", "3.5 mm"],
    camera: "12MP Center Stage with Desk View",
    speakers: "Six-speaker system",
    weightKg: 1.62,
    colours: ["silver", "space-black"],
    wifi: "Wi-Fi 6E",
    bluetooth: "Bluetooth 5.3",
    tagline: "Thunderbolt 5. Serious Pro silicon.",
    whoItSuits: "Developers, 3D, and heavy video.",
    whyChoose: [
      "Thunderbolt 5 on Pro/Max.",
      "Higher memory ceilings.",
      "Nano-texture optional.",
    ],
    basePriceKes: P["macbook-pro-14-m4-pro"],
    defaultColour: "space-black",
    fanless: false,
    magsafe: true,
    externalDisplays: "Up to three external displays",
    thicknessKey: "pro-14",
    isNew: true,
  },
  {
    id: "macbook-pro-16-m4-pro",
    name: "MacBook Pro 16″ M4 Pro",
    family: "Pro",
    chipGen: "M4",
    chip: "M4 Pro",
    year: 2024,
    screenInches: 16,
    cpuCores: "Up to 14-core",
    gpuCores: "Up to 20-core",
    memoryOptionsGb: [24, 48],
    storageOptions: ["512GB", "1TB", "2TB", "4TB", "8TB"],
    display: {
      diagonal: 16.2,
      resolution: "3456×2234",
      ppi: 254,
      panel: "Liquid Retina XDR",
      brightnessNits: 1000,
      peakHdrNits: 1600,
      refreshHz: 120,
      promotion: true,
      nanoTextureOptional: true,
    },
    batteryVideoHours: 24,
    charging: "MagSafe 3",
    ports: ["3× Thunderbolt 5", "HDMI", "SDXC", "MagSafe 3", "3.5 mm"],
    camera: "12MP Center Stage with Desk View",
    speakers: "Six-speaker system",
    weightKg: 2.14,
    colours: ["silver", "space-black"],
    wifi: "Wi-Fi 6E",
    bluetooth: "Bluetooth 5.3",
    tagline: "Largest M4 Pro canvas.",
    whoItSuits: "Pros who refuse to compromise on screen size.",
    whyChoose: [
      "16″ XDR + Thunderbolt 5.",
      "Long battery claim.",
      "Desk View camera.",
    ],
    basePriceKes: P["macbook-pro-16-m4-pro"],
    defaultColour: "space-black",
    fanless: false,
    magsafe: true,
    externalDisplays: "Up to three external displays",
    thicknessKey: "pro-16",
    isNew: true,
  },
  {
    id: "macbook-pro-14-m5",
    name: "MacBook Pro 14″ M5",
    family: "Pro",
    chipGen: "M5",
    chip: "M5",
    year: 2025,
    screenInches: 14,
    cpuCores: "Confirm on Apple’s page",
    gpuCores: "Confirm on Apple’s page",
    memoryOptionsGb: [16, 24, 32],
    storageOptions: ["512GB", "1TB", "2TB"],
    display: {
      diagonal: 14.2,
      resolution: "3024×1964",
      ppi: 254,
      panel: "Liquid Retina XDR",
      brightnessNits: 1000,
      peakHdrNits: 1600,
      refreshHz: 120,
      promotion: true,
      nanoTextureOptional: true,
    },
    batteryVideoHours: 24,
    charging: "MagSafe 3",
    ports: ["Thunderbolt", "HDMI", "SDXC", "MagSafe 3", "3.5 mm"],
    camera: "12MP Center Stage with Desk View",
    speakers: "Six-speaker system",
    weightKg: 1.55,
    colours: ["silver", "space-black"],
    wifi: "Wi-Fi 7",
    bluetooth: "Bluetooth 6",
    tagline: "Newest base Pro - check final specs.",
    whoItSuits: "Early adopters of M5 Pro hardware.",
    whyChoose: [
      "Newest generation entry Pro.",
      "Check final specs until verified.",
      "Overview image until store shots exist.",
    ],
    basePriceKes: P["macbook-pro-14-m5"],
    defaultColour: "space-black",
    fanless: false,
    magsafe: true,
    externalDisplays: "Confirm on Apple’s page",
    thicknessKey: "pro-14",
    overviewOnly: true,
    checkFinalSpecs: true,
    isNew: true,
  },
  {
    id: "macbook-pro-14-m5-pro",
    name: "MacBook Pro 14″ M5 Pro",
    family: "Pro",
    chipGen: "M5",
    chip: "M5 Pro",
    year: 2026,
    screenInches: 14,
    cpuCores: "Up to 18-core (flagged)",
    gpuCores: "Confirm on Apple’s page",
    memoryOptionsGb: [24, 48, 64],
    storageOptions: ["1TB", "2TB", "4TB", "8TB"],
    display: {
      diagonal: 14.2,
      resolution: "3024×1964",
      ppi: 254,
      panel: "Liquid Retina XDR",
      brightnessNits: 1000,
      peakHdrNits: 1600,
      refreshHz: 120,
      promotion: true,
      nanoTextureOptional: true,
    },
    batteryVideoHours: 24,
    charging: "MagSafe 3",
    ports: ["3× Thunderbolt 5", "HDMI (8K)", "SDXC", "MagSafe 3", "3.5 mm"],
    camera: "12MP Center Stage with Desk View",
    speakers: "Six-speaker system",
    weightKg: 1.62,
    colours: ["silver", "space-black"],
    wifi: "Wi-Fi 7",
    bluetooth: "Bluetooth 6",
    tagline: "M5 Pro - all figures flagged.",
    whoItSuits: "Power users waiting for verified M5 Pro stock.",
    whyChoose: [
      "Highest tier 14″ in this catalogue.",
      "Thunderbolt 5 and HDMI 8K listed - verify.",
      "Check final specs on every number.",
    ],
    basePriceKes: P["macbook-pro-14-m5-pro"],
    defaultColour: "space-black",
    fanless: false,
    magsafe: true,
    externalDisplays: "Confirm on Apple’s page",
    thicknessKey: "pro-14",
    overviewOnly: true,
    checkFinalSpecs: true,
    isNew: true,
  },
  {
    id: "macbook-pro-16-m5-pro",
    name: "MacBook Pro 16″ M5 Pro",
    family: "Pro",
    chipGen: "M5",
    chip: "M5 Pro",
    year: 2026,
    screenInches: 16,
    cpuCores: "Up to 18-core (flagged)",
    gpuCores: "Confirm on Apple’s page",
    memoryOptionsGb: [24, 48, 64],
    storageOptions: ["1TB", "2TB", "4TB", "8TB"],
    display: {
      diagonal: 16.2,
      resolution: "3456×2234",
      ppi: 254,
      panel: "Liquid Retina XDR",
      brightnessNits: 1000,
      peakHdrNits: 1600,
      refreshHz: 120,
      promotion: true,
      nanoTextureOptional: true,
    },
    batteryVideoHours: 24,
    charging: "MagSafe 3",
    ports: ["3× Thunderbolt 5", "HDMI (8K)", "SDXC", "MagSafe 3", "3.5 mm"],
    camera: "12MP Center Stage with Desk View",
    speakers: "Six-speaker system",
    weightKg: 2.14,
    colours: ["silver", "space-black"],
    wifi: "Wi-Fi 7",
    bluetooth: "Bluetooth 6",
    tagline: "Largest M5 Pro - verify before selling.",
    whoItSuits: "Teams standardising on the newest 16″ Pro.",
    whyChoose: [
      "Flagship size and silicon generation.",
      "All M5 Pro/Max numbers are provisional.",
      "Overview until product photos land.",
    ],
    basePriceKes: P["macbook-pro-16-m5-pro"],
    defaultColour: "space-black",
    fanless: false,
    magsafe: true,
    externalDisplays: "Confirm on Apple’s page",
    thicknessKey: "pro-16",
    overviewOnly: true,
    checkFinalSpecs: true,
    isNew: true,
  },
];

export function getMacModel(id: string): MacModel | undefined {
  return macModels.find((m) => m.id === id);
}

export function macModelsByFamily(family: MacFamily): MacModel[] {
  return macModels.filter((m) => m.family === family);
}

export function macModelsByChip(gen: MacChipGen): MacModel[] {
  return macModels.filter((m) => m.chipGen === gen);
}

export function macSubline(m: MacModel): string {
  return `${m.chip} · ${m.screenInches}″ · from ${m.memoryOptionsGb[0]} GB · ${m.storageOptions[0]}`;
}

export function lowestMacPrice(family?: MacFamily): number {
  const list = family ? macModelsByFamily(family) : macModels;
  return Math.min(...list.map((m) => m.basePriceKes));
}
