/**
 * Central image resolver for iPhone 11–16.
 * Every page uses getImage() — change paths only in the manifest.
 */

import {
  imageManifest,
  OVERVIEW_ONLY_MODELS,
  TEXT_ONLY_COLOURS,
  type IphoneView,
} from "./manifest";
import { colourLabel } from "./colours";

export const PLACEHOLDER_SRC = "/images/iphone/placeholder.svg";

export type ResolvedImage = {
  src: string;
  /** Sibling `.webp` when generated by `npm run images:iphone-webp` */
  srcWebp?: string;
  alt: string;
  view: IphoneView | "overview";
  /** Suggested display width: view1 ≈760, view2/3 ≈900 */
  width: number;
  /** true when we fell back because the requested file is missing */
  fallback: boolean;
  overviewOnly: boolean;
  note?: string;
};

function webpSibling(src: string): string | undefined {
  if (!src || src === PLACEHOLDER_SRC) return undefined;
  if (/\.webp$/i.test(src)) return src;
  return src.replace(/\.(jpe?g|png)$/i, ".webp");
}

function widthForView(view: IphoneView | "overview"): number {
  return view === 1 || view === "overview" ? 760 : 900;
}

export function isOverviewOnly(modelId: string): boolean {
  return (OVERVIEW_ONLY_MODELS as readonly string[]).includes(modelId);
}

export function availableViews(modelId: string, colourKey: string): IphoneView[] {
  const entry = imageManifest[modelId];
  if (!entry || entry.overviewOnly) return [];
  return (entry.colours[colourKey] as IphoneView[] | undefined) ?? [];
}

export function availableColours(modelId: string): string[] {
  const entry = imageManifest[modelId];
  if (!entry) return [];
  return Object.keys(entry.colours);
}

export function textOnlyColours(modelId: string): string[] {
  return TEXT_ONLY_COLOURS[modelId] ?? [];
}

/**
 * Resolve a product photo. Falls back: requested → first view of colour → overview → placeholder.
 */
export function getImage(
  modelId: string,
  colourKey: string | null | undefined,
  view: IphoneView | "overview" = 1,
  modelName?: string,
): ResolvedImage {
  const entry = imageManifest[modelId];
  const name = modelName ?? modelId.replace(/-/g, " ");
  const overviewOnly = isOverviewOnly(modelId);

  if (!entry) {
    return {
      src: PLACEHOLDER_SRC,
      alt: `${name}`,
      view: "overview",
      width: 760,
      fallback: true,
      overviewOnly: true,
      note: "Image unavailable",
    };
  }

  if (overviewOnly || view === "overview" || !colourKey) {
    const src = entry.overview || PLACEHOLDER_SRC;
    return {
      src,
      srcWebp: webpSibling(src),
      alt: `${name}, all colours overview`,
      view: "overview",
      width: widthForView("overview"),
      fallback: !entry.overview,
      overviewOnly,
      note: overviewOnly ? "Full angle set coming soon" : undefined,
    };
  }

  const views = availableViews(modelId, colourKey);
  let useView: IphoneView | "overview" = view === "overview" ? 1 : view;
  let fallback = false;

  if (!views.includes(useView as IphoneView)) {
    if (views.length) {
      useView = views[0];
      fallback = true;
    } else {
      const src = entry.overview || PLACEHOLDER_SRC;
      return {
        src,
        srcWebp: webpSibling(src),
        alt: `${name}, all colours overview`,
        view: "overview",
        width: widthForView("overview"),
        fallback: true,
        overviewOnly,
        note: "Full angle set coming soon",
      };
    }
  }

  const key = `${colourKey}|${useView}`;
  const src = entry.files[key];
  if (!src) {
    const ov = entry.overview || PLACEHOLDER_SRC;
    return {
      src: ov,
      srcWebp: webpSibling(ov),
      alt: `${name}, all colours overview`,
      view: "overview",
      width: widthForView("overview"),
      fallback: true,
      overviewOnly,
    };
  }

  const viewLabel =
    useView === 1
      ? "front and back"
      : useView === 2
        ? "camera close-up"
        : "camera and screen";

  return {
    src,
    srcWebp: webpSibling(src),
    alt: `${name} in ${colourLabel(colourKey)}, ${viewLabel}`,
    view: useView,
    width: widthForView(useView),
    fallback,
    overviewOnly: false,
  };
}

export function defaultColourForModel(modelId: string, preferred?: string): string | null {
  if (isOverviewOnly(modelId)) return null;
  const colours = availableColours(modelId);
  if (!colours.length) return null;
  if (preferred && colours.includes(preferred)) return preferred;
  return colours[0];
}
