/** Auto-derived from Gadget_Hub_iPhone_* packs. Paths relative to /public. */

export type IphoneView = 1 | 2 | 3;

export type ColourViews = Partial<Record<string, IphoneView[]>>;

export type ModelImageEntry = {
  overview?: string;
  /** colourKey → available views */
  colours: ColourViews;
  /** colourKey|view → absolute public path */
  files: Record<string, string>;
  /** true when only overview exists (no per-colour angles) */
  overviewOnly: boolean;
};

export const OVERVIEW_ONLY_MODELS = [
  "iphone-11",
  "iphone-12-pro",
  "iphone-12-pro-max",
  "iphone-16e",
] as const;

/** Colours listed for marketing but no image yet */
export const TEXT_ONLY_COLOURS: Record<string, string[]> = {
  "iphone-13-pro": ["sierra-blue"],
  "iphone-13-pro-max": ["sierra-blue"],
};

export const imageManifest: Record<string, ModelImageEntry> = {
  "iphone-11": {
    overview: "/Gadget_Hub_iPhone_11-13_Images/All_colours_overview/iphone-11_all-colours_back-view.jpg",
    overviewOnly: true,
    colours: {
    },
    files: {
    },
  },
  "iphone-11-pro": {
    overview: "/Gadget_Hub_iPhone_11-13_Images/All_colours_overview/iphone-11-pro_all-colours_back-view.jpg",
    overviewOnly: false,
    colours: {
      "gold": [1, 3],
      "midnight-green": [1, 2, 3],
      "silver": [1, 3],
      "space": [1, 3],
    },
    files: {
      "gold|1": "/Gadget_Hub_iPhone_11-13_Images/iPhone_11/iphone-11-pro/iphone-11-pro_gold_view1.jpg",
      "gold|3": "/Gadget_Hub_iPhone_11-13_Images/iPhone_11/iphone-11-pro/iphone-11-pro_gold_view3.jpg",
      "midnight-green|1": "/Gadget_Hub_iPhone_11-13_Images/iPhone_11/iphone-11-pro/iphone-11-pro_midnight-green_view1.jpg",
      "midnight-green|2": "/Gadget_Hub_iPhone_11-13_Images/iPhone_11/iphone-11-pro/iphone-11-pro_midnight-green_view2.jpg",
      "midnight-green|3": "/Gadget_Hub_iPhone_11-13_Images/iPhone_11/iphone-11-pro/iphone-11-pro_midnight-green_view3.jpg",
      "silver|1": "/Gadget_Hub_iPhone_11-13_Images/iPhone_11/iphone-11-pro/iphone-11-pro_silver_view1.jpg",
      "silver|3": "/Gadget_Hub_iPhone_11-13_Images/iPhone_11/iphone-11-pro/iphone-11-pro_silver_view3.jpg",
      "space|1": "/Gadget_Hub_iPhone_11-13_Images/iPhone_11/iphone-11-pro/iphone-11-pro_space_view1.jpg",
      "space|3": "/Gadget_Hub_iPhone_11-13_Images/iPhone_11/iphone-11-pro/iphone-11-pro_space_view3.jpg",
    },
  },
  "iphone-11-pro-max": {
    overview: "/Gadget_Hub_iPhone_11-13_Images/All_colours_overview/iphone-11-pro-max_all-colours_back-view.jpg",
    overviewOnly: false,
    colours: {
      "gold": [1, 3],
      "midnight-green": [1, 2, 3],
      "silver": [1, 3],
      "space": [1, 3],
    },
    files: {
      "gold|1": "/Gadget_Hub_iPhone_11-13_Images/iPhone_11/iphone-11-pro-max/iphone-11-pro-max_gold_view1.jpg",
      "gold|3": "/Gadget_Hub_iPhone_11-13_Images/iPhone_11/iphone-11-pro-max/iphone-11-pro-max_gold_view3.jpg",
      "midnight-green|1": "/Gadget_Hub_iPhone_11-13_Images/iPhone_11/iphone-11-pro-max/iphone-11-pro-max_midnight-green_view1.jpg",
      "midnight-green|2": "/Gadget_Hub_iPhone_11-13_Images/iPhone_11/iphone-11-pro-max/iphone-11-pro-max_midnight-green_view2.jpg",
      "midnight-green|3": "/Gadget_Hub_iPhone_11-13_Images/iPhone_11/iphone-11-pro-max/iphone-11-pro-max_midnight-green_view3.jpg",
      "silver|1": "/Gadget_Hub_iPhone_11-13_Images/iPhone_11/iphone-11-pro-max/iphone-11-pro-max_silver_view1.jpg",
      "silver|3": "/Gadget_Hub_iPhone_11-13_Images/iPhone_11/iphone-11-pro-max/iphone-11-pro-max_silver_view3.jpg",
      "space|1": "/Gadget_Hub_iPhone_11-13_Images/iPhone_11/iphone-11-pro-max/iphone-11-pro-max_space_view1.jpg",
      "space|3": "/Gadget_Hub_iPhone_11-13_Images/iPhone_11/iphone-11-pro-max/iphone-11-pro-max_space_view3.jpg",
    },
  },
  "iphone-12": {
    overview: "/Gadget_Hub_iPhone_11-13_Images/All_colours_overview/iphone-12_all-colours_back-view.png",
    overviewOnly: false,
    colours: {
      "black": [1, 2, 3],
      "blue": [1, 2, 3],
      "green": [1, 2, 3],
      "purple": [1, 2, 3],
      "red": [1, 2, 3],
      "white": [1, 2, 3],
    },
    files: {
      "black|1": "/Gadget_Hub_iPhone_11-13_Images/iPhone_12/iphone-12/iphone-12_black_view1.jpg",
      "black|2": "/Gadget_Hub_iPhone_11-13_Images/iPhone_12/iphone-12/iphone-12_black_view2.jpg",
      "black|3": "/Gadget_Hub_iPhone_11-13_Images/iPhone_12/iphone-12/iphone-12_black_view3.jpg",
      "blue|1": "/Gadget_Hub_iPhone_11-13_Images/iPhone_12/iphone-12/iphone-12_blue_view1.jpg",
      "blue|2": "/Gadget_Hub_iPhone_11-13_Images/iPhone_12/iphone-12/iphone-12_blue_view2.jpg",
      "blue|3": "/Gadget_Hub_iPhone_11-13_Images/iPhone_12/iphone-12/iphone-12_blue_view3.jpg",
      "green|1": "/Gadget_Hub_iPhone_11-13_Images/iPhone_12/iphone-12/iphone-12_green_view1.jpg",
      "green|2": "/Gadget_Hub_iPhone_11-13_Images/iPhone_12/iphone-12/iphone-12_green_view2.jpg",
      "green|3": "/Gadget_Hub_iPhone_11-13_Images/iPhone_12/iphone-12/iphone-12_green_view3.jpg",
      "purple|1": "/Gadget_Hub_iPhone_11-13_Images/iPhone_12/iphone-12/iphone-12_purple_view1.jpg",
      "purple|2": "/Gadget_Hub_iPhone_11-13_Images/iPhone_12/iphone-12/iphone-12_purple_view2.jpg",
      "purple|3": "/Gadget_Hub_iPhone_11-13_Images/iPhone_12/iphone-12/iphone-12_purple_view3.jpg",
      "red|1": "/Gadget_Hub_iPhone_11-13_Images/iPhone_12/iphone-12/iphone-12_red_view1.jpg",
      "red|2": "/Gadget_Hub_iPhone_11-13_Images/iPhone_12/iphone-12/iphone-12_red_view2.jpg",
      "red|3": "/Gadget_Hub_iPhone_11-13_Images/iPhone_12/iphone-12/iphone-12_red_view3.jpg",
      "white|1": "/Gadget_Hub_iPhone_11-13_Images/iPhone_12/iphone-12/iphone-12_white_view1.jpg",
      "white|2": "/Gadget_Hub_iPhone_11-13_Images/iPhone_12/iphone-12/iphone-12_white_view2.jpg",
      "white|3": "/Gadget_Hub_iPhone_11-13_Images/iPhone_12/iphone-12/iphone-12_white_view3.jpg",
    },
  },
  "iphone-12-mini": {
    overview: "/Gadget_Hub_iPhone_11-13_Images/All_colours_overview/iphone-12-mini_all-colours_back-view.png",
    overviewOnly: false,
    colours: {
      "black": [1, 2, 3],
      "blue": [1, 2, 3],
      "green": [1, 2, 3],
      "purple": [1, 2, 3],
      "red": [1, 2, 3],
      "white": [1, 2, 3],
    },
    files: {
      "black|1": "/Gadget_Hub_iPhone_11-13_Images/iPhone_12/iphone-12-mini/iphone-12-mini_black_view1.jpg",
      "black|2": "/Gadget_Hub_iPhone_11-13_Images/iPhone_12/iphone-12-mini/iphone-12-mini_black_view2.jpg",
      "black|3": "/Gadget_Hub_iPhone_11-13_Images/iPhone_12/iphone-12-mini/iphone-12-mini_black_view3.jpg",
      "blue|1": "/Gadget_Hub_iPhone_11-13_Images/iPhone_12/iphone-12-mini/iphone-12-mini_blue_view1.jpg",
      "blue|2": "/Gadget_Hub_iPhone_11-13_Images/iPhone_12/iphone-12-mini/iphone-12-mini_blue_view2.jpg",
      "blue|3": "/Gadget_Hub_iPhone_11-13_Images/iPhone_12/iphone-12-mini/iphone-12-mini_blue_view3.jpg",
      "green|1": "/Gadget_Hub_iPhone_11-13_Images/iPhone_12/iphone-12-mini/iphone-12-mini_green_view1.jpg",
      "green|2": "/Gadget_Hub_iPhone_11-13_Images/iPhone_12/iphone-12-mini/iphone-12-mini_green_view2.jpg",
      "green|3": "/Gadget_Hub_iPhone_11-13_Images/iPhone_12/iphone-12-mini/iphone-12-mini_green_view3.jpg",
      "purple|1": "/Gadget_Hub_iPhone_11-13_Images/iPhone_12/iphone-12-mini/iphone-12-mini_purple_view1.jpg",
      "purple|2": "/Gadget_Hub_iPhone_11-13_Images/iPhone_12/iphone-12-mini/iphone-12-mini_purple_view2.jpg",
      "purple|3": "/Gadget_Hub_iPhone_11-13_Images/iPhone_12/iphone-12-mini/iphone-12-mini_purple_view3.jpg",
      "red|1": "/Gadget_Hub_iPhone_11-13_Images/iPhone_12/iphone-12-mini/iphone-12-mini_red_view1.jpg",
      "red|2": "/Gadget_Hub_iPhone_11-13_Images/iPhone_12/iphone-12-mini/iphone-12-mini_red_view2.jpg",
      "red|3": "/Gadget_Hub_iPhone_11-13_Images/iPhone_12/iphone-12-mini/iphone-12-mini_red_view3.jpg",
      "white|1": "/Gadget_Hub_iPhone_11-13_Images/iPhone_12/iphone-12-mini/iphone-12-mini_white_view1.jpg",
      "white|2": "/Gadget_Hub_iPhone_11-13_Images/iPhone_12/iphone-12-mini/iphone-12-mini_white_view2.jpg",
      "white|3": "/Gadget_Hub_iPhone_11-13_Images/iPhone_12/iphone-12-mini/iphone-12-mini_white_view3.jpg",
    },
  },
  "iphone-12-pro": {
    overview: "/Gadget_Hub_iPhone_11-13_Images/All_colours_overview/iphone-12-pro_all-colours_back-view.jpg",
    overviewOnly: true,
    colours: {
    },
    files: {
    },
  },
  "iphone-12-pro-max": {
    overview: "/Gadget_Hub_iPhone_11-13_Images/All_colours_overview/iphone-12-pro-max_all-colours_back-view.jpg",
    overviewOnly: true,
    colours: {
    },
    files: {
    },
  },
  "iphone-13": {
    overview: "/Gadget_Hub_iPhone_11-13_Images/All_colours_overview/iphone-13_all-colours_back-view.png",
    overviewOnly: false,
    colours: {
      "blue": [1, 2, 3],
      "green": [1, 2, 3],
      "midnight": [1, 2, 3],
      "pink": [1, 2, 3],
      "product-red": [1, 2, 3],
      "starlight": [1, 2, 3],
    },
    files: {
      "blue|1": "/Gadget_Hub_iPhone_11-13_Images/iPhone_13/iphone-13/iphone-13_blue_view1.jpg",
      "blue|2": "/Gadget_Hub_iPhone_11-13_Images/iPhone_13/iphone-13/iphone-13_blue_view2.jpg",
      "blue|3": "/Gadget_Hub_iPhone_11-13_Images/iPhone_13/iphone-13/iphone-13_blue_view3.jpg",
      "green|1": "/Gadget_Hub_iPhone_11-13_Images/iPhone_13/iphone-13/iphone-13_green_view1.jpg",
      "green|2": "/Gadget_Hub_iPhone_11-13_Images/iPhone_13/iphone-13/iphone-13_green_view2.jpg",
      "green|3": "/Gadget_Hub_iPhone_11-13_Images/iPhone_13/iphone-13/iphone-13_green_view3.jpg",
      "midnight|1": "/Gadget_Hub_iPhone_11-13_Images/iPhone_13/iphone-13/iphone-13_midnight_view1.jpg",
      "midnight|2": "/Gadget_Hub_iPhone_11-13_Images/iPhone_13/iphone-13/iphone-13_midnight_view2.jpg",
      "midnight|3": "/Gadget_Hub_iPhone_11-13_Images/iPhone_13/iphone-13/iphone-13_midnight_view3.jpg",
      "pink|1": "/Gadget_Hub_iPhone_11-13_Images/iPhone_13/iphone-13/iphone-13_pink_view1.jpg",
      "pink|2": "/Gadget_Hub_iPhone_11-13_Images/iPhone_13/iphone-13/iphone-13_pink_view2.jpg",
      "pink|3": "/Gadget_Hub_iPhone_11-13_Images/iPhone_13/iphone-13/iphone-13_pink_view3.jpg",
      "product-red|1": "/Gadget_Hub_iPhone_11-13_Images/iPhone_13/iphone-13/iphone-13_product-red_view1.jpg",
      "product-red|2": "/Gadget_Hub_iPhone_11-13_Images/iPhone_13/iphone-13/iphone-13_product-red_view2.jpg",
      "product-red|3": "/Gadget_Hub_iPhone_11-13_Images/iPhone_13/iphone-13/iphone-13_product-red_view3.jpg",
      "starlight|1": "/Gadget_Hub_iPhone_11-13_Images/iPhone_13/iphone-13/iphone-13_starlight_view1.jpg",
      "starlight|2": "/Gadget_Hub_iPhone_11-13_Images/iPhone_13/iphone-13/iphone-13_starlight_view2.jpg",
      "starlight|3": "/Gadget_Hub_iPhone_11-13_Images/iPhone_13/iphone-13/iphone-13_starlight_view3.jpg",
    },
  },
  "iphone-13-mini": {
    overview: "/Gadget_Hub_iPhone_11-13_Images/All_colours_overview/iphone-13-mini_all-colours_back-view.png",
    overviewOnly: false,
    colours: {
      "blue": [1, 2, 3],
      "green": [1, 2, 3],
      "midnight": [1, 2, 3],
      "pink": [1, 2, 3],
      "product-red": [1, 2, 3],
      "starlight": [1, 2, 3],
    },
    files: {
      "blue|1": "/Gadget_Hub_iPhone_11-13_Images/iPhone_13/iphone-13-mini/iphone-13-mini_blue_view1.jpg",
      "blue|2": "/Gadget_Hub_iPhone_11-13_Images/iPhone_13/iphone-13-mini/iphone-13-mini_blue_view2.jpg",
      "blue|3": "/Gadget_Hub_iPhone_11-13_Images/iPhone_13/iphone-13-mini/iphone-13-mini_blue_view3.jpg",
      "green|1": "/Gadget_Hub_iPhone_11-13_Images/iPhone_13/iphone-13-mini/iphone-13-mini_green_view1.jpg",
      "green|2": "/Gadget_Hub_iPhone_11-13_Images/iPhone_13/iphone-13-mini/iphone-13-mini_green_view2.jpg",
      "green|3": "/Gadget_Hub_iPhone_11-13_Images/iPhone_13/iphone-13-mini/iphone-13-mini_green_view3.jpg",
      "midnight|1": "/Gadget_Hub_iPhone_11-13_Images/iPhone_13/iphone-13-mini/iphone-13-mini_midnight_view1.jpg",
      "midnight|2": "/Gadget_Hub_iPhone_11-13_Images/iPhone_13/iphone-13-mini/iphone-13-mini_midnight_view2.jpg",
      "midnight|3": "/Gadget_Hub_iPhone_11-13_Images/iPhone_13/iphone-13-mini/iphone-13-mini_midnight_view3.jpg",
      "pink|1": "/Gadget_Hub_iPhone_11-13_Images/iPhone_13/iphone-13-mini/iphone-13-mini_pink_view1.jpg",
      "pink|2": "/Gadget_Hub_iPhone_11-13_Images/iPhone_13/iphone-13-mini/iphone-13-mini_pink_view2.jpg",
      "pink|3": "/Gadget_Hub_iPhone_11-13_Images/iPhone_13/iphone-13-mini/iphone-13-mini_pink_view3.jpg",
      "product-red|1": "/Gadget_Hub_iPhone_11-13_Images/iPhone_13/iphone-13-mini/iphone-13-mini_product-red_view1.jpg",
      "product-red|2": "/Gadget_Hub_iPhone_11-13_Images/iPhone_13/iphone-13-mini/iphone-13-mini_product-red_view2.jpg",
      "product-red|3": "/Gadget_Hub_iPhone_11-13_Images/iPhone_13/iphone-13-mini/iphone-13-mini_product-red_view3.jpg",
      "starlight|1": "/Gadget_Hub_iPhone_11-13_Images/iPhone_13/iphone-13-mini/iphone-13-mini_starlight_view1.jpg",
      "starlight|2": "/Gadget_Hub_iPhone_11-13_Images/iPhone_13/iphone-13-mini/iphone-13-mini_starlight_view2.jpg",
      "starlight|3": "/Gadget_Hub_iPhone_11-13_Images/iPhone_13/iphone-13-mini/iphone-13-mini_starlight_view3.jpg",
    },
  },
  "iphone-13-pro": {
    overview: "/Gadget_Hub_iPhone_11-13_Images/All_colours_overview/iphone-13-pro_all-colours_back-view.png",
    overviewOnly: false,
    colours: {
      "gold": [1, 2, 3],
      "graphite": [1, 2, 3],
      "silver": [1, 2, 3],
    },
    files: {
      "gold|1": "/Gadget_Hub_iPhone_11-13_Images/iPhone_13/iphone-13-pro/iphone-13-pro_gold_view1.jpg",
      "gold|2": "/Gadget_Hub_iPhone_11-13_Images/iPhone_13/iphone-13-pro/iphone-13-pro_gold_view2.jpg",
      "gold|3": "/Gadget_Hub_iPhone_11-13_Images/iPhone_13/iphone-13-pro/iphone-13-pro_gold_view3.jpg",
      "graphite|1": "/Gadget_Hub_iPhone_11-13_Images/iPhone_13/iphone-13-pro/iphone-13-pro_graphite_view1.jpg",
      "graphite|2": "/Gadget_Hub_iPhone_11-13_Images/iPhone_13/iphone-13-pro/iphone-13-pro_graphite_view2.jpg",
      "graphite|3": "/Gadget_Hub_iPhone_11-13_Images/iPhone_13/iphone-13-pro/iphone-13-pro_graphite_view3.jpg",
      "silver|1": "/Gadget_Hub_iPhone_11-13_Images/iPhone_13/iphone-13-pro/iphone-13-pro_silver_view1.jpg",
      "silver|2": "/Gadget_Hub_iPhone_11-13_Images/iPhone_13/iphone-13-pro/iphone-13-pro_silver_view2.jpg",
      "silver|3": "/Gadget_Hub_iPhone_11-13_Images/iPhone_13/iphone-13-pro/iphone-13-pro_silver_view3.jpg",
    },
  },
  "iphone-13-pro-max": {
    overview: "/Gadget_Hub_iPhone_11-13_Images/All_colours_overview/iphone-13-pro-max_all-colours_back-view.png",
    overviewOnly: false,
    colours: {
      "gold": [1, 2, 3],
      "graphite": [1, 2, 3],
      "silver": [1, 2, 3],
    },
    files: {
      "gold|1": "/Gadget_Hub_iPhone_11-13_Images/iPhone_13/iphone-13-pro-max/iphone-13-pro-max_gold_view1.jpg",
      "gold|2": "/Gadget_Hub_iPhone_11-13_Images/iPhone_13/iphone-13-pro-max/iphone-13-pro-max_gold_view2.jpg",
      "gold|3": "/Gadget_Hub_iPhone_11-13_Images/iPhone_13/iphone-13-pro-max/iphone-13-pro-max_gold_view3.jpg",
      "graphite|1": "/Gadget_Hub_iPhone_11-13_Images/iPhone_13/iphone-13-pro-max/iphone-13-pro-max_graphite_view1.jpg",
      "graphite|2": "/Gadget_Hub_iPhone_11-13_Images/iPhone_13/iphone-13-pro-max/iphone-13-pro-max_graphite_view2.jpg",
      "graphite|3": "/Gadget_Hub_iPhone_11-13_Images/iPhone_13/iphone-13-pro-max/iphone-13-pro-max_graphite_view3.jpg",
      "silver|1": "/Gadget_Hub_iPhone_11-13_Images/iPhone_13/iphone-13-pro-max/iphone-13-pro-max_silver_view1.jpg",
      "silver|2": "/Gadget_Hub_iPhone_11-13_Images/iPhone_13/iphone-13-pro-max/iphone-13-pro-max_silver_view2.jpg",
      "silver|3": "/Gadget_Hub_iPhone_11-13_Images/iPhone_13/iphone-13-pro-max/iphone-13-pro-max_silver_view3.jpg",
    },
  },
  "iphone-14": {
    overview: "/Gadget_Hub_iPhone_11-13_Images/All_colours_overview/iphone-14_all-colours_back-view.png",
    overviewOnly: false,
    colours: {
      "blue": [1, 2, 3],
      "midnight": [1, 2, 3],
      "purple": [1, 2, 3],
      "red": [1, 2, 3],
      "starlight": [1, 2, 3],
      "yellow": [1, 2, 3],
    },
    files: {
      "blue|1": "/Gadget_Hub_iPhone_14-16_Images/iPhone_14/iphone-14/iphone-14_blue_view1.jpg",
      "blue|2": "/Gadget_Hub_iPhone_14-16_Images/iPhone_14/iphone-14/iphone-14_blue_view2.jpg",
      "blue|3": "/Gadget_Hub_iPhone_14-16_Images/iPhone_14/iphone-14/iphone-14_blue_view3.jpg",
      "midnight|1": "/Gadget_Hub_iPhone_14-16_Images/iPhone_14/iphone-14/iphone-14_midnight_view1.jpg",
      "midnight|2": "/Gadget_Hub_iPhone_14-16_Images/iPhone_14/iphone-14/iphone-14_midnight_view2.jpg",
      "midnight|3": "/Gadget_Hub_iPhone_14-16_Images/iPhone_14/iphone-14/iphone-14_midnight_view3.jpg",
      "purple|1": "/Gadget_Hub_iPhone_14-16_Images/iPhone_14/iphone-14/iphone-14_purple_view1.jpg",
      "purple|2": "/Gadget_Hub_iPhone_14-16_Images/iPhone_14/iphone-14/iphone-14_purple_view2.jpg",
      "purple|3": "/Gadget_Hub_iPhone_14-16_Images/iPhone_14/iphone-14/iphone-14_purple_view3.jpg",
      "red|1": "/Gadget_Hub_iPhone_14-16_Images/iPhone_14/iphone-14/iphone-14_red_view1.jpg",
      "red|2": "/Gadget_Hub_iPhone_14-16_Images/iPhone_14/iphone-14/iphone-14_red_view2.jpg",
      "red|3": "/Gadget_Hub_iPhone_14-16_Images/iPhone_14/iphone-14/iphone-14_red_view3.jpg",
      "starlight|1": "/Gadget_Hub_iPhone_14-16_Images/iPhone_14/iphone-14/iphone-14_starlight_view1.jpg",
      "starlight|2": "/Gadget_Hub_iPhone_14-16_Images/iPhone_14/iphone-14/iphone-14_starlight_view2.jpg",
      "starlight|3": "/Gadget_Hub_iPhone_14-16_Images/iPhone_14/iphone-14/iphone-14_starlight_view3.jpg",
      "yellow|1": "/Gadget_Hub_iPhone_14-16_Images/iPhone_14/iphone-14/iphone-14_yellow_view1.jpg",
      "yellow|2": "/Gadget_Hub_iPhone_14-16_Images/iPhone_14/iphone-14/iphone-14_yellow_view2.jpg",
      "yellow|3": "/Gadget_Hub_iPhone_14-16_Images/iPhone_14/iphone-14/iphone-14_yellow_view3.jpg",
    },
  },
  "iphone-14-plus": {
    overview: "/Gadget_Hub_iPhone_11-13_Images/All_colours_overview/iphone-14-plus_all-colours_back-view.png",
    overviewOnly: false,
    colours: {
      "blue": [1, 2, 3],
      "midnight": [1, 2, 3],
      "purple": [1, 2, 3],
      "red": [1, 2, 3],
      "starlight": [1, 2, 3],
      "yellow": [1, 2, 3],
    },
    files: {
      "blue|1": "/Gadget_Hub_iPhone_14-16_Images/iPhone_14/iphone-14-plus/iphone-14-plus_blue_view1.jpg",
      "blue|2": "/Gadget_Hub_iPhone_14-16_Images/iPhone_14/iphone-14-plus/iphone-14-plus_blue_view2.jpg",
      "blue|3": "/Gadget_Hub_iPhone_14-16_Images/iPhone_14/iphone-14-plus/iphone-14-plus_blue_view3.jpg",
      "midnight|1": "/Gadget_Hub_iPhone_14-16_Images/iPhone_14/iphone-14-plus/iphone-14-plus_midnight_view1.jpg",
      "midnight|2": "/Gadget_Hub_iPhone_14-16_Images/iPhone_14/iphone-14-plus/iphone-14-plus_midnight_view2.jpg",
      "midnight|3": "/Gadget_Hub_iPhone_14-16_Images/iPhone_14/iphone-14-plus/iphone-14-plus_midnight_view3.jpg",
      "purple|1": "/Gadget_Hub_iPhone_14-16_Images/iPhone_14/iphone-14-plus/iphone-14-plus_purple_view1.jpg",
      "purple|2": "/Gadget_Hub_iPhone_14-16_Images/iPhone_14/iphone-14-plus/iphone-14-plus_purple_view2.jpg",
      "purple|3": "/Gadget_Hub_iPhone_14-16_Images/iPhone_14/iphone-14-plus/iphone-14-plus_purple_view3.jpg",
      "red|1": "/Gadget_Hub_iPhone_14-16_Images/iPhone_14/iphone-14-plus/iphone-14-plus_red_view1.jpg",
      "red|2": "/Gadget_Hub_iPhone_14-16_Images/iPhone_14/iphone-14-plus/iphone-14-plus_red_view2.jpg",
      "red|3": "/Gadget_Hub_iPhone_14-16_Images/iPhone_14/iphone-14-plus/iphone-14-plus_red_view3.jpg",
      "starlight|1": "/Gadget_Hub_iPhone_14-16_Images/iPhone_14/iphone-14-plus/iphone-14-plus_starlight_view1.jpg",
      "starlight|2": "/Gadget_Hub_iPhone_14-16_Images/iPhone_14/iphone-14-plus/iphone-14-plus_starlight_view2.jpg",
      "starlight|3": "/Gadget_Hub_iPhone_14-16_Images/iPhone_14/iphone-14-plus/iphone-14-plus_starlight_view3.jpg",
      "yellow|1": "/Gadget_Hub_iPhone_14-16_Images/iPhone_14/iphone-14-plus/iphone-14-plus_yellow_view1.jpg",
      "yellow|2": "/Gadget_Hub_iPhone_14-16_Images/iPhone_14/iphone-14-plus/iphone-14-plus_yellow_view2.jpg",
      "yellow|3": "/Gadget_Hub_iPhone_14-16_Images/iPhone_14/iphone-14-plus/iphone-14-plus_yellow_view3.jpg",
    },
  },
  "iphone-14-pro": {
    overview: "/Gadget_Hub_iPhone_11-13_Images/All_colours_overview/iphone-14-pro_all-colours_back-view.png",
    overviewOnly: false,
    colours: {
      "deeppurple": [1, 2, 3],
      "gold": [1, 2, 3],
      "silver": [1, 2, 3],
      "spaceblack": [1, 2, 3],
    },
    files: {
      "deeppurple|1": "/Gadget_Hub_iPhone_14-16_Images/iPhone_14/iphone-14-pro/iphone-14-pro_deeppurple_view1.jpg",
      "deeppurple|2": "/Gadget_Hub_iPhone_14-16_Images/iPhone_14/iphone-14-pro/iphone-14-pro_deeppurple_view2.jpg",
      "deeppurple|3": "/Gadget_Hub_iPhone_14-16_Images/iPhone_14/iphone-14-pro/iphone-14-pro_deeppurple_view3.jpg",
      "gold|1": "/Gadget_Hub_iPhone_14-16_Images/iPhone_14/iphone-14-pro/iphone-14-pro_gold_view1.jpg",
      "gold|2": "/Gadget_Hub_iPhone_14-16_Images/iPhone_14/iphone-14-pro/iphone-14-pro_gold_view2.jpg",
      "gold|3": "/Gadget_Hub_iPhone_14-16_Images/iPhone_14/iphone-14-pro/iphone-14-pro_gold_view3.jpg",
      "silver|1": "/Gadget_Hub_iPhone_14-16_Images/iPhone_14/iphone-14-pro/iphone-14-pro_silver_view1.jpg",
      "silver|2": "/Gadget_Hub_iPhone_14-16_Images/iPhone_14/iphone-14-pro/iphone-14-pro_silver_view2.jpg",
      "silver|3": "/Gadget_Hub_iPhone_14-16_Images/iPhone_14/iphone-14-pro/iphone-14-pro_silver_view3.jpg",
      "spaceblack|1": "/Gadget_Hub_iPhone_14-16_Images/iPhone_14/iphone-14-pro/iphone-14-pro_spaceblack_view1.jpg",
      "spaceblack|2": "/Gadget_Hub_iPhone_14-16_Images/iPhone_14/iphone-14-pro/iphone-14-pro_spaceblack_view2.jpg",
      "spaceblack|3": "/Gadget_Hub_iPhone_14-16_Images/iPhone_14/iphone-14-pro/iphone-14-pro_spaceblack_view3.jpg",
    },
  },
  "iphone-14-pro-max": {
    overview: "/Gadget_Hub_iPhone_11-13_Images/All_colours_overview/iphone-14-pro-max_all-colours_back-view.png",
    overviewOnly: false,
    colours: {
      "deeppurple": [1, 2, 3],
      "gold": [1, 2, 3],
      "silver": [1, 2, 3],
      "spaceblack": [1, 2, 3],
    },
    files: {
      "deeppurple|1": "/Gadget_Hub_iPhone_14-16_Images/iPhone_14/iphone-14-pro-max/iphone-14-pro-max_deeppurple_view1.jpg",
      "deeppurple|2": "/Gadget_Hub_iPhone_14-16_Images/iPhone_14/iphone-14-pro-max/iphone-14-pro-max_deeppurple_view2.jpg",
      "deeppurple|3": "/Gadget_Hub_iPhone_14-16_Images/iPhone_14/iphone-14-pro-max/iphone-14-pro-max_deeppurple_view3.jpg",
      "gold|1": "/Gadget_Hub_iPhone_14-16_Images/iPhone_14/iphone-14-pro-max/iphone-14-pro-max_gold_view1.jpg",
      "gold|2": "/Gadget_Hub_iPhone_14-16_Images/iPhone_14/iphone-14-pro-max/iphone-14-pro-max_gold_view2.jpg",
      "gold|3": "/Gadget_Hub_iPhone_14-16_Images/iPhone_14/iphone-14-pro-max/iphone-14-pro-max_gold_view3.jpg",
      "silver|1": "/Gadget_Hub_iPhone_14-16_Images/iPhone_14/iphone-14-pro-max/iphone-14-pro-max_silver_view1.jpg",
      "silver|2": "/Gadget_Hub_iPhone_14-16_Images/iPhone_14/iphone-14-pro-max/iphone-14-pro-max_silver_view2.jpg",
      "silver|3": "/Gadget_Hub_iPhone_14-16_Images/iPhone_14/iphone-14-pro-max/iphone-14-pro-max_silver_view3.jpg",
      "spaceblack|1": "/Gadget_Hub_iPhone_14-16_Images/iPhone_14/iphone-14-pro-max/iphone-14-pro-max_spaceblack_view1.jpg",
      "spaceblack|2": "/Gadget_Hub_iPhone_14-16_Images/iPhone_14/iphone-14-pro-max/iphone-14-pro-max_spaceblack_view2.jpg",
      "spaceblack|3": "/Gadget_Hub_iPhone_14-16_Images/iPhone_14/iphone-14-pro-max/iphone-14-pro-max_spaceblack_view3.jpg",
    },
  },
  "iphone-15": {
    overview: "/Gadget_Hub_iPhone_11-13_Images/All_colours_overview/iphone-15_all-colours_back-view.png",
    overviewOnly: false,
    colours: {
      "black": [1, 2, 3],
      "blue": [1, 2, 3],
      "green": [1, 2, 3],
      "pink": [1, 2, 3],
      "yellow": [1, 2, 3],
    },
    files: {
      "black|1": "/Gadget_Hub_iPhone_14-16_Images/iPhone_15/iphone-15/iphone-15_black_view1.jpg",
      "black|2": "/Gadget_Hub_iPhone_14-16_Images/iPhone_15/iphone-15/iphone-15_black_view2.jpg",
      "black|3": "/Gadget_Hub_iPhone_14-16_Images/iPhone_15/iphone-15/iphone-15_black_view3.jpg",
      "blue|1": "/Gadget_Hub_iPhone_14-16_Images/iPhone_15/iphone-15/iphone-15_blue_view1.jpg",
      "blue|2": "/Gadget_Hub_iPhone_14-16_Images/iPhone_15/iphone-15/iphone-15_blue_view2.jpg",
      "blue|3": "/Gadget_Hub_iPhone_14-16_Images/iPhone_15/iphone-15/iphone-15_blue_view3.jpg",
      "green|1": "/Gadget_Hub_iPhone_14-16_Images/iPhone_15/iphone-15/iphone-15_green_view1.jpg",
      "green|2": "/Gadget_Hub_iPhone_14-16_Images/iPhone_15/iphone-15/iphone-15_green_view2.jpg",
      "green|3": "/Gadget_Hub_iPhone_14-16_Images/iPhone_15/iphone-15/iphone-15_green_view3.jpg",
      "pink|1": "/Gadget_Hub_iPhone_14-16_Images/iPhone_15/iphone-15/iphone-15_pink_view1.jpg",
      "pink|2": "/Gadget_Hub_iPhone_14-16_Images/iPhone_15/iphone-15/iphone-15_pink_view2.jpg",
      "pink|3": "/Gadget_Hub_iPhone_14-16_Images/iPhone_15/iphone-15/iphone-15_pink_view3.jpg",
      "yellow|1": "/Gadget_Hub_iPhone_14-16_Images/iPhone_15/iphone-15/iphone-15_yellow_view1.jpg",
      "yellow|2": "/Gadget_Hub_iPhone_14-16_Images/iPhone_15/iphone-15/iphone-15_yellow_view2.jpg",
      "yellow|3": "/Gadget_Hub_iPhone_14-16_Images/iPhone_15/iphone-15/iphone-15_yellow_view3.jpg",
    },
  },
  "iphone-15-plus": {
    overview: "/Gadget_Hub_iPhone_11-13_Images/All_colours_overview/iphone-15-plus_all-colours_back-view.png",
    overviewOnly: false,
    colours: {
      "black": [1, 2, 3],
      "blue": [1, 2, 3],
      "green": [1, 2, 3],
      "pink": [1, 2, 3],
      "yellow": [1, 2, 3],
    },
    files: {
      "black|1": "/Gadget_Hub_iPhone_14-16_Images/iPhone_15/iphone-15-plus/iphone-15-plus_black_view1.jpg",
      "black|2": "/Gadget_Hub_iPhone_14-16_Images/iPhone_15/iphone-15-plus/iphone-15-plus_black_view2.jpg",
      "black|3": "/Gadget_Hub_iPhone_14-16_Images/iPhone_15/iphone-15-plus/iphone-15-plus_black_view3.jpg",
      "blue|1": "/Gadget_Hub_iPhone_14-16_Images/iPhone_15/iphone-15-plus/iphone-15-plus_blue_view1.jpg",
      "blue|2": "/Gadget_Hub_iPhone_14-16_Images/iPhone_15/iphone-15-plus/iphone-15-plus_blue_view2.jpg",
      "blue|3": "/Gadget_Hub_iPhone_14-16_Images/iPhone_15/iphone-15-plus/iphone-15-plus_blue_view3.jpg",
      "green|1": "/Gadget_Hub_iPhone_14-16_Images/iPhone_15/iphone-15-plus/iphone-15-plus_green_view1.jpg",
      "green|2": "/Gadget_Hub_iPhone_14-16_Images/iPhone_15/iphone-15-plus/iphone-15-plus_green_view2.jpg",
      "green|3": "/Gadget_Hub_iPhone_14-16_Images/iPhone_15/iphone-15-plus/iphone-15-plus_green_view3.jpg",
      "pink|1": "/Gadget_Hub_iPhone_14-16_Images/iPhone_15/iphone-15-plus/iphone-15-plus_pink_view1.jpg",
      "pink|2": "/Gadget_Hub_iPhone_14-16_Images/iPhone_15/iphone-15-plus/iphone-15-plus_pink_view2.jpg",
      "pink|3": "/Gadget_Hub_iPhone_14-16_Images/iPhone_15/iphone-15-plus/iphone-15-plus_pink_view3.jpg",
      "yellow|1": "/Gadget_Hub_iPhone_14-16_Images/iPhone_15/iphone-15-plus/iphone-15-plus_yellow_view1.jpg",
      "yellow|2": "/Gadget_Hub_iPhone_14-16_Images/iPhone_15/iphone-15-plus/iphone-15-plus_yellow_view2.jpg",
      "yellow|3": "/Gadget_Hub_iPhone_14-16_Images/iPhone_15/iphone-15-plus/iphone-15-plus_yellow_view3.jpg",
    },
  },
  "iphone-15-pro": {
    overview: "/Gadget_Hub_iPhone_11-13_Images/All_colours_overview/iphone-15-pro_all-colours_back-view.png",
    overviewOnly: false,
    colours: {
      "blacktitanium": [1, 2, 3],
      "bluetitanium": [1, 2, 3],
      "naturaltitanium": [1, 2, 3],
      "whitetitanium": [1, 2, 3],
    },
    files: {
      "blacktitanium|1": "/Gadget_Hub_iPhone_14-16_Images/iPhone_15/iphone-15-pro/iphone-15-pro_blacktitanium_view1.jpg",
      "blacktitanium|2": "/Gadget_Hub_iPhone_14-16_Images/iPhone_15/iphone-15-pro/iphone-15-pro_blacktitanium_view2.jpg",
      "blacktitanium|3": "/Gadget_Hub_iPhone_14-16_Images/iPhone_15/iphone-15-pro/iphone-15-pro_blacktitanium_view3.jpg",
      "bluetitanium|1": "/Gadget_Hub_iPhone_14-16_Images/iPhone_15/iphone-15-pro/iphone-15-pro_bluetitanium_view1.jpg",
      "bluetitanium|2": "/Gadget_Hub_iPhone_14-16_Images/iPhone_15/iphone-15-pro/iphone-15-pro_bluetitanium_view2.jpg",
      "bluetitanium|3": "/Gadget_Hub_iPhone_14-16_Images/iPhone_15/iphone-15-pro/iphone-15-pro_bluetitanium_view3.jpg",
      "naturaltitanium|1": "/Gadget_Hub_iPhone_14-16_Images/iPhone_15/iphone-15-pro/iphone-15-pro_naturaltitanium_view1.jpg",
      "naturaltitanium|2": "/Gadget_Hub_iPhone_14-16_Images/iPhone_15/iphone-15-pro/iphone-15-pro_naturaltitanium_view2.jpg",
      "naturaltitanium|3": "/Gadget_Hub_iPhone_14-16_Images/iPhone_15/iphone-15-pro/iphone-15-pro_naturaltitanium_view3.jpg",
      "whitetitanium|1": "/Gadget_Hub_iPhone_14-16_Images/iPhone_15/iphone-15-pro/iphone-15-pro_whitetitanium_view1.jpg",
      "whitetitanium|2": "/Gadget_Hub_iPhone_14-16_Images/iPhone_15/iphone-15-pro/iphone-15-pro_whitetitanium_view2.jpg",
      "whitetitanium|3": "/Gadget_Hub_iPhone_14-16_Images/iPhone_15/iphone-15-pro/iphone-15-pro_whitetitanium_view3.jpg",
    },
  },
  "iphone-15-pro-max": {
    overview: "/Gadget_Hub_iPhone_11-13_Images/All_colours_overview/iphone-15-pro-max_all-colours_back-view.png",
    overviewOnly: false,
    colours: {
      "blacktitanium": [1, 2, 3],
      "bluetitanium": [1, 2, 3],
      "naturaltitanium": [1, 2, 3],
      "whitetitanium": [1, 2, 3],
    },
    files: {
      "blacktitanium|1": "/Gadget_Hub_iPhone_14-16_Images/iPhone_15/iphone-15-pro-max/iphone-15-pro-max_blacktitanium_view1.jpg",
      "blacktitanium|2": "/Gadget_Hub_iPhone_14-16_Images/iPhone_15/iphone-15-pro-max/iphone-15-pro-max_blacktitanium_view2.jpg",
      "blacktitanium|3": "/Gadget_Hub_iPhone_14-16_Images/iPhone_15/iphone-15-pro-max/iphone-15-pro-max_blacktitanium_view3.jpg",
      "bluetitanium|1": "/Gadget_Hub_iPhone_14-16_Images/iPhone_15/iphone-15-pro-max/iphone-15-pro-max_bluetitanium_view1.jpg",
      "bluetitanium|2": "/Gadget_Hub_iPhone_14-16_Images/iPhone_15/iphone-15-pro-max/iphone-15-pro-max_bluetitanium_view2.jpg",
      "bluetitanium|3": "/Gadget_Hub_iPhone_14-16_Images/iPhone_15/iphone-15-pro-max/iphone-15-pro-max_bluetitanium_view3.jpg",
      "naturaltitanium|1": "/Gadget_Hub_iPhone_14-16_Images/iPhone_15/iphone-15-pro-max/iphone-15-pro-max_naturaltitanium_view1.jpg",
      "naturaltitanium|2": "/Gadget_Hub_iPhone_14-16_Images/iPhone_15/iphone-15-pro-max/iphone-15-pro-max_naturaltitanium_view2.jpg",
      "naturaltitanium|3": "/Gadget_Hub_iPhone_14-16_Images/iPhone_15/iphone-15-pro-max/iphone-15-pro-max_naturaltitanium_view3.jpg",
      "whitetitanium|1": "/Gadget_Hub_iPhone_14-16_Images/iPhone_15/iphone-15-pro-max/iphone-15-pro-max_whitetitanium_view1.jpg",
      "whitetitanium|2": "/Gadget_Hub_iPhone_14-16_Images/iPhone_15/iphone-15-pro-max/iphone-15-pro-max_whitetitanium_view2.jpg",
      "whitetitanium|3": "/Gadget_Hub_iPhone_14-16_Images/iPhone_15/iphone-15-pro-max/iphone-15-pro-max_whitetitanium_view3.jpg",
    },
  },
  "iphone-16": {
    overview: "/Gadget_Hub_iPhone_11-13_Images/All_colours_overview/iphone-16_all-colours_back-view.png",
    overviewOnly: false,
    colours: {
      "black": [1, 2, 3],
      "pink": [1, 2, 3],
      "teal": [1, 2, 3],
      "ultramarine": [1, 2, 3],
      "white": [1, 2, 3],
    },
    files: {
      "black|1": "/Gadget_Hub_iPhone_14-16_Images/iPhone_16/iphone-16/iphone-16_black_view1.jpg",
      "black|2": "/Gadget_Hub_iPhone_14-16_Images/iPhone_16/iphone-16/iphone-16_black_view2.jpg",
      "black|3": "/Gadget_Hub_iPhone_14-16_Images/iPhone_16/iphone-16/iphone-16_black_view3.jpg",
      "pink|1": "/Gadget_Hub_iPhone_14-16_Images/iPhone_16/iphone-16/iphone-16_pink_view1.jpg",
      "pink|2": "/Gadget_Hub_iPhone_14-16_Images/iPhone_16/iphone-16/iphone-16_pink_view2.jpg",
      "pink|3": "/Gadget_Hub_iPhone_14-16_Images/iPhone_16/iphone-16/iphone-16_pink_view3.jpg",
      "teal|1": "/Gadget_Hub_iPhone_14-16_Images/iPhone_16/iphone-16/iphone-16_teal_view1.jpg",
      "teal|2": "/Gadget_Hub_iPhone_14-16_Images/iPhone_16/iphone-16/iphone-16_teal_view2.jpg",
      "teal|3": "/Gadget_Hub_iPhone_14-16_Images/iPhone_16/iphone-16/iphone-16_teal_view3.jpg",
      "ultramarine|1": "/Gadget_Hub_iPhone_14-16_Images/iPhone_16/iphone-16/iphone-16_ultramarine_view1.jpg",
      "ultramarine|2": "/Gadget_Hub_iPhone_14-16_Images/iPhone_16/iphone-16/iphone-16_ultramarine_view2.jpg",
      "ultramarine|3": "/Gadget_Hub_iPhone_14-16_Images/iPhone_16/iphone-16/iphone-16_ultramarine_view3.jpg",
      "white|1": "/Gadget_Hub_iPhone_14-16_Images/iPhone_16/iphone-16/iphone-16_white_view1.jpg",
      "white|2": "/Gadget_Hub_iPhone_14-16_Images/iPhone_16/iphone-16/iphone-16_white_view2.jpg",
      "white|3": "/Gadget_Hub_iPhone_14-16_Images/iPhone_16/iphone-16/iphone-16_white_view3.jpg",
    },
  },
  "iphone-16-plus": {
    overview: "/Gadget_Hub_iPhone_11-13_Images/All_colours_overview/iphone-16-plus_all-colours_back-view.png",
    overviewOnly: false,
    colours: {
      "black": [1, 2, 3],
      "pink": [1, 2, 3],
      "teal": [1, 2, 3],
      "ultramarine": [1, 2, 3],
      "white": [1, 2, 3],
    },
    files: {
      "black|1": "/Gadget_Hub_iPhone_14-16_Images/iPhone_16/iphone-16-plus/iphone-16-plus_black_view1.jpg",
      "black|2": "/Gadget_Hub_iPhone_14-16_Images/iPhone_16/iphone-16-plus/iphone-16-plus_black_view2.jpg",
      "black|3": "/Gadget_Hub_iPhone_14-16_Images/iPhone_16/iphone-16-plus/iphone-16-plus_black_view3.jpg",
      "pink|1": "/Gadget_Hub_iPhone_14-16_Images/iPhone_16/iphone-16-plus/iphone-16-plus_pink_view1.jpg",
      "pink|2": "/Gadget_Hub_iPhone_14-16_Images/iPhone_16/iphone-16-plus/iphone-16-plus_pink_view2.jpg",
      "pink|3": "/Gadget_Hub_iPhone_14-16_Images/iPhone_16/iphone-16-plus/iphone-16-plus_pink_view3.jpg",
      "teal|1": "/Gadget_Hub_iPhone_14-16_Images/iPhone_16/iphone-16-plus/iphone-16-plus_teal_view1.jpg",
      "teal|2": "/Gadget_Hub_iPhone_14-16_Images/iPhone_16/iphone-16-plus/iphone-16-plus_teal_view2.jpg",
      "teal|3": "/Gadget_Hub_iPhone_14-16_Images/iPhone_16/iphone-16-plus/iphone-16-plus_teal_view3.jpg",
      "ultramarine|1": "/Gadget_Hub_iPhone_14-16_Images/iPhone_16/iphone-16-plus/iphone-16-plus_ultramarine_view1.jpg",
      "ultramarine|2": "/Gadget_Hub_iPhone_14-16_Images/iPhone_16/iphone-16-plus/iphone-16-plus_ultramarine_view2.jpg",
      "ultramarine|3": "/Gadget_Hub_iPhone_14-16_Images/iPhone_16/iphone-16-plus/iphone-16-plus_ultramarine_view3.jpg",
      "white|1": "/Gadget_Hub_iPhone_14-16_Images/iPhone_16/iphone-16-plus/iphone-16-plus_white_view1.jpg",
      "white|2": "/Gadget_Hub_iPhone_14-16_Images/iPhone_16/iphone-16-plus/iphone-16-plus_white_view2.jpg",
      "white|3": "/Gadget_Hub_iPhone_14-16_Images/iPhone_16/iphone-16-plus/iphone-16-plus_white_view3.jpg",
    },
  },
  "iphone-16-pro": {
    overview: "/Gadget_Hub_iPhone_11-13_Images/All_colours_overview/iphone-16-pro_all-colours_back-view.png",
    overviewOnly: false,
    colours: {
      "blacktitanium": [1, 2, 3],
      "deserttitanium": [1, 2, 3],
      "naturaltitanium": [1, 2, 3],
      "whitetitanium": [1, 2, 3],
    },
    files: {
      "blacktitanium|1": "/Gadget_Hub_iPhone_14-16_Images/iPhone_16/iphone-16-pro/iphone-16-pro_blacktitanium_view1.jpg",
      "blacktitanium|2": "/Gadget_Hub_iPhone_14-16_Images/iPhone_16/iphone-16-pro/iphone-16-pro_blacktitanium_view2.jpg",
      "blacktitanium|3": "/Gadget_Hub_iPhone_14-16_Images/iPhone_16/iphone-16-pro/iphone-16-pro_blacktitanium_view3.jpg",
      "deserttitanium|1": "/Gadget_Hub_iPhone_14-16_Images/iPhone_16/iphone-16-pro/iphone-16-pro_deserttitanium_view1.jpg",
      "deserttitanium|2": "/Gadget_Hub_iPhone_14-16_Images/iPhone_16/iphone-16-pro/iphone-16-pro_deserttitanium_view2.jpg",
      "deserttitanium|3": "/Gadget_Hub_iPhone_14-16_Images/iPhone_16/iphone-16-pro/iphone-16-pro_deserttitanium_view3.jpg",
      "naturaltitanium|1": "/Gadget_Hub_iPhone_14-16_Images/iPhone_16/iphone-16-pro/iphone-16-pro_naturaltitanium_view1.jpg",
      "naturaltitanium|2": "/Gadget_Hub_iPhone_14-16_Images/iPhone_16/iphone-16-pro/iphone-16-pro_naturaltitanium_view2.jpg",
      "naturaltitanium|3": "/Gadget_Hub_iPhone_14-16_Images/iPhone_16/iphone-16-pro/iphone-16-pro_naturaltitanium_view3.jpg",
      "whitetitanium|1": "/Gadget_Hub_iPhone_14-16_Images/iPhone_16/iphone-16-pro/iphone-16-pro_whitetitanium_view1.jpg",
      "whitetitanium|2": "/Gadget_Hub_iPhone_14-16_Images/iPhone_16/iphone-16-pro/iphone-16-pro_whitetitanium_view2.jpg",
      "whitetitanium|3": "/Gadget_Hub_iPhone_14-16_Images/iPhone_16/iphone-16-pro/iphone-16-pro_whitetitanium_view3.jpg",
    },
  },
  "iphone-16-pro-max": {
    overview: "/Gadget_Hub_iPhone_11-13_Images/All_colours_overview/iphone-16-pro-max_all-colours_back-view.png",
    overviewOnly: false,
    colours: {
      "blacktitanium": [1, 2, 3],
      "deserttitanium": [1, 2, 3],
      "naturaltitanium": [1, 2, 3],
      "whitetitanium": [1, 2, 3],
    },
    files: {
      "blacktitanium|1": "/Gadget_Hub_iPhone_14-16_Images/iPhone_16/iphone-16-pro-max/iphone-16-pro-max_blacktitanium_view1.jpg",
      "blacktitanium|2": "/Gadget_Hub_iPhone_14-16_Images/iPhone_16/iphone-16-pro-max/iphone-16-pro-max_blacktitanium_view2.jpg",
      "blacktitanium|3": "/Gadget_Hub_iPhone_14-16_Images/iPhone_16/iphone-16-pro-max/iphone-16-pro-max_blacktitanium_view3.jpg",
      "deserttitanium|1": "/Gadget_Hub_iPhone_14-16_Images/iPhone_16/iphone-16-pro-max/iphone-16-pro-max_deserttitanium_view1.jpg",
      "deserttitanium|2": "/Gadget_Hub_iPhone_14-16_Images/iPhone_16/iphone-16-pro-max/iphone-16-pro-max_deserttitanium_view2.jpg",
      "deserttitanium|3": "/Gadget_Hub_iPhone_14-16_Images/iPhone_16/iphone-16-pro-max/iphone-16-pro-max_deserttitanium_view3.jpg",
      "naturaltitanium|1": "/Gadget_Hub_iPhone_14-16_Images/iPhone_16/iphone-16-pro-max/iphone-16-pro-max_naturaltitanium_view1.jpg",
      "naturaltitanium|2": "/Gadget_Hub_iPhone_14-16_Images/iPhone_16/iphone-16-pro-max/iphone-16-pro-max_naturaltitanium_view2.jpg",
      "naturaltitanium|3": "/Gadget_Hub_iPhone_14-16_Images/iPhone_16/iphone-16-pro-max/iphone-16-pro-max_naturaltitanium_view3.jpg",
      "whitetitanium|1": "/Gadget_Hub_iPhone_14-16_Images/iPhone_16/iphone-16-pro-max/iphone-16-pro-max_whitetitanium_view1.jpg",
      "whitetitanium|2": "/Gadget_Hub_iPhone_14-16_Images/iPhone_16/iphone-16-pro-max/iphone-16-pro-max_whitetitanium_view2.jpg",
      "whitetitanium|3": "/Gadget_Hub_iPhone_14-16_Images/iPhone_16/iphone-16-pro-max/iphone-16-pro-max_whitetitanium_view3.jpg",
    },
  },
  "iphone-16e": {
    overview: "/Gadget_Hub_iPhone_11-13_Images/All_colours_overview/iphone-16e_all-colours_back-view.png",
    overviewOnly: true,
    colours: {
    },
    files: {
    },
  },
};

