/**
 * iPhone 11 - 16 catalog.
 * Specs are Apple's published figures - owner: re-verify on apple.com before launch.
 * Base prices are SAMPLE placeholders in KES.
 */

export type IphoneTier = "Standard" | "Plus" | "Pro" | "Pro Max" | "mini" | "e";

export type IphoneModel = {
  id: string;
  name: string;
  family: 11 | 12 | 13 | 14 | 15 | 16;
  tier: IphoneTier;
  year: number;
  displayInches: number;
  resolution: string;
  ppi: number;
  refreshHz: number;
  chip: string;
  rearCameras: string[];
  batteryVideoHours: number;
  weightGrams: number;
  storage: string[];
  /** Sample base price KES (lowest storage) */
  basePriceKes: number;
  frame: string;
  glass: string;
  waterResistance: string;
  port: "Lightning" | "USB-C" | "USB-C (USB 3)";
  magsafe: boolean;
  cutout: "Notch" | "Dynamic Island";
  tagline: string;
  defaultColour: string | null;
  note?: string;
  /** Cellular generation */
  cellular: "LTE" | "5G";
  frontCamera: string;
  faceId: boolean;
  cameraControl: boolean;
  actionButton: boolean;
  crashDetection: boolean;
  appleIntelligence: boolean;
  wifi: string;
  displayNote?: string;
};

/**
 * Shared facts (prompt §3):
 * - Front camera 12MP TrueDepth, Face ID: all
 * - 5G from 12 onward; 11 series LTE
 * - IP68: 6 m / 30 min for 12 - 16; 4 m for 11 Pro/Max; 2 m for 11
 * - Camera Control: 16 / 16 Plus / 16 Pro / 16 Pro Max
 * - Action button: 15 Pro/Max + all 16 + 16e
 * - Crash Detection: 14+
 * - Apple Intelligence: 15 Pro/Max + all 16 + 16e
 * - Wi-Fi 7: 16 family (not 16e per prompt - prompt says 16, 16 Plus, 16 Pro, 16 Pro Max)
 * - Wi-Fi 6E: 15 Pro/Max; Wi-Fi 6 rest
 */

export const models: IphoneModel[] = [
  {
    id: "iphone-16-pro-max",
    name: "iPhone 16 Pro Max",
    family: 16,
    tier: "Pro Max",
    year: 2024,
    displayInches: 6.9,
    resolution: "2868×1320",
    ppi: 460,
    refreshHz: 120,
    chip: "A18 Pro",
    rearCameras: ["48MP Fusion", "48MP Ultra Wide", "12MP 5× Telephoto"],
    batteryVideoHours: 33,
    weightGrams: 227,
    storage: ["256GB", "512GB", "1TB"],
    basePriceKes: 174999,
    frame: "Titanium",
    glass: "Ceramic Shield",
    waterResistance: "IP68 (6 m for 30 min)",
    port: "USB-C (USB 3)",
    magsafe: true,
    cutout: "Dynamic Island",
    tagline: "The most Pro iPhone yet.",
    defaultColour: "deserttitanium",
    cellular: "5G",
    frontCamera: "12MP TrueDepth",
    faceId: true,
    cameraControl: true,
    actionButton: true,
    crashDetection: true,
    appleIntelligence: true,
    wifi: "Wi-Fi 7",
  },
  {
    id: "iphone-16-pro",
    name: "iPhone 16 Pro",
    family: 16,
    tier: "Pro",
    year: 2024,
    displayInches: 6.3,
    resolution: "2622×1206",
    ppi: 460,
    refreshHz: 120,
    chip: "A18 Pro",
    rearCameras: ["48MP Fusion", "48MP Ultra Wide", "12MP 5× Telephoto"],
    batteryVideoHours: 27,
    weightGrams: 199,
    storage: ["128GB", "256GB", "512GB", "1TB"],
    basePriceKes: 154999,
    frame: "Titanium",
    glass: "Ceramic Shield",
    waterResistance: "IP68 (6 m for 30 min)",
    port: "USB-C (USB 3)",
    magsafe: true,
    cutout: "Dynamic Island",
    tagline: "Pro camera. Pro titanium.",
    defaultColour: "deserttitanium",
    cellular: "5G",
    frontCamera: "12MP TrueDepth",
    faceId: true,
    cameraControl: true,
    actionButton: true,
    crashDetection: true,
    appleIntelligence: true,
    wifi: "Wi-Fi 7",
  },
  {
    id: "iphone-16-plus",
    name: "iPhone 16 Plus",
    family: 16,
    tier: "Plus",
    year: 2024,
    displayInches: 6.7,
    resolution: "2796×1290",
    ppi: 460,
    refreshHz: 60,
    chip: "A18",
    rearCameras: ["48MP Fusion", "12MP Ultra Wide"],
    batteryVideoHours: 27,
    weightGrams: 199,
    storage: ["128GB", "256GB", "512GB"],
    basePriceKes: 118999,
    frame: "Aluminium",
    glass: "Ceramic Shield",
    waterResistance: "IP68 (6 m for 30 min)",
    port: "USB-C",
    magsafe: true,
    cutout: "Dynamic Island",
    tagline: "Big screen. Camera Control.",
    defaultColour: "ultramarine",
    cellular: "5G",
    frontCamera: "12MP TrueDepth",
    faceId: true,
    cameraControl: true,
    actionButton: true,
    crashDetection: true,
    appleIntelligence: true,
    wifi: "Wi-Fi 7",
  },
  {
    id: "iphone-16",
    name: "iPhone 16",
    family: 16,
    tier: "Standard",
    year: 2024,
    displayInches: 6.1,
    resolution: "2556×1179",
    ppi: 460,
    refreshHz: 60,
    chip: "A18",
    rearCameras: ["48MP Fusion", "12MP Ultra Wide"],
    batteryVideoHours: 22,
    weightGrams: 170,
    storage: ["128GB", "256GB", "512GB"],
    basePriceKes: 104999,
    frame: "Aluminium",
    glass: "Ceramic Shield",
    waterResistance: "IP68 (6 m for 30 min)",
    port: "USB-C",
    magsafe: true,
    cutout: "Dynamic Island",
    tagline: "Camera Control. Built for Apple Intelligence.",
    defaultColour: "teal",
    cellular: "5G",
    frontCamera: "12MP TrueDepth",
    faceId: true,
    cameraControl: true,
    actionButton: true,
    crashDetection: true,
    appleIntelligence: true,
    wifi: "Wi-Fi 7",
  },
  {
    id: "iphone-16e",
    name: "iPhone 16e",
    family: 16,
    tier: "e",
    year: 2025,
    displayInches: 6.1,
    resolution: "2532×1170",
    ppi: 460,
    refreshHz: 60,
    chip: "A18",
    rearCameras: ["48MP Fusion (single)"],
    batteryVideoHours: 26,
    weightGrams: 167,
    storage: ["128GB", "256GB", "512GB"],
    basePriceKes: 78999,
    frame: "Aluminium",
    glass: "Ceramic Shield",
    waterResistance: "IP68 (6 m for 30 min)",
    port: "USB-C",
    magsafe: false,
    cutout: "Notch",
    tagline: "Essential. Powerful. Value.",
    defaultColour: null,
    note: "Overview image only. Full angle set coming soon.",
    cellular: "5G",
    frontCamera: "12MP TrueDepth",
    faceId: true,
    cameraControl: false,
    actionButton: true,
    crashDetection: true,
    appleIntelligence: true,
    wifi: "Wi-Fi 6",
  },
  {
    id: "iphone-15-pro-max",
    name: "iPhone 15 Pro Max",
    family: 15,
    tier: "Pro Max",
    year: 2023,
    displayInches: 6.7,
    resolution: "2796×1290",
    ppi: 460,
    refreshHz: 120,
    chip: "A17 Pro",
    rearCameras: ["48MP", "12MP Ultra Wide", "12MP 5× Tele"],
    batteryVideoHours: 29,
    weightGrams: 221,
    storage: ["256GB", "512GB", "1TB"],
    basePriceKes: 154999,
    frame: "Titanium",
    glass: "Ceramic Shield",
    waterResistance: "IP68 (6 m for 30 min)",
    port: "USB-C (USB 3)",
    magsafe: true,
    cutout: "Dynamic Island",
    tagline: "Titanium. A17 Pro. 5× zoom.",
    defaultColour: "bluetitanium",
    cellular: "5G",
    frontCamera: "12MP TrueDepth",
    faceId: true,
    cameraControl: false,
    actionButton: true,
    crashDetection: true,
    appleIntelligence: true,
    wifi: "Wi-Fi 6E",
  },
  {
    id: "iphone-15-pro",
    name: "iPhone 15 Pro",
    family: 15,
    tier: "Pro",
    year: 2023,
    displayInches: 6.1,
    resolution: "2556×1179",
    ppi: 460,
    refreshHz: 120,
    chip: "A17 Pro",
    rearCameras: ["48MP", "12MP Ultra Wide", "12MP 3× Tele"],
    batteryVideoHours: 23,
    weightGrams: 187,
    storage: ["128GB", "256GB", "512GB", "1TB"],
    basePriceKes: 139999,
    frame: "Titanium",
    glass: "Ceramic Shield",
    waterResistance: "IP68 (6 m for 30 min)",
    port: "USB-C (USB 3)",
    magsafe: true,
    cutout: "Dynamic Island",
    tagline: "Pro in a lighter titanium design.",
    defaultColour: "bluetitanium",
    cellular: "5G",
    frontCamera: "12MP TrueDepth",
    faceId: true,
    cameraControl: false,
    actionButton: true,
    crashDetection: true,
    appleIntelligence: true,
    wifi: "Wi-Fi 6E",
  },
  {
    id: "iphone-15-plus",
    name: "iPhone 15 Plus",
    family: 15,
    tier: "Plus",
    year: 2023,
    displayInches: 6.7,
    resolution: "2796×1290",
    ppi: 460,
    refreshHz: 60,
    chip: "A16 Bionic",
    rearCameras: ["48MP", "12MP Ultra Wide"],
    batteryVideoHours: 26,
    weightGrams: 201,
    storage: ["128GB", "256GB", "512GB"],
    basePriceKes: 104999,
    frame: "Aluminium",
    glass: "Ceramic Shield",
    waterResistance: "IP68 (6 m for 30 min)",
    port: "USB-C",
    magsafe: true,
    cutout: "Dynamic Island",
    tagline: "Big Dual-camera. USB-C.",
    defaultColour: "blue",
    cellular: "5G",
    frontCamera: "12MP TrueDepth",
    faceId: true,
    cameraControl: false,
    actionButton: false,
    crashDetection: true,
    appleIntelligence: false,
    wifi: "Wi-Fi 6",
  },
  {
    id: "iphone-15",
    name: "iPhone 15",
    family: 15,
    tier: "Standard",
    year: 2023,
    displayInches: 6.1,
    resolution: "2556×1179",
    ppi: 460,
    refreshHz: 60,
    chip: "A16 Bionic",
    rearCameras: ["48MP", "12MP Ultra Wide"],
    batteryVideoHours: 20,
    weightGrams: 171,
    storage: ["128GB", "256GB", "512GB"],
    basePriceKes: 94999,
    frame: "Aluminium",
    glass: "Ceramic Shield",
    waterResistance: "IP68 (6 m for 30 min)",
    port: "USB-C",
    magsafe: true,
    cutout: "Dynamic Island",
    tagline: "Dynamic Island. 48MP. USB-C.",
    defaultColour: "pink",
    cellular: "5G",
    frontCamera: "12MP TrueDepth",
    faceId: true,
    cameraControl: false,
    actionButton: false,
    crashDetection: true,
    appleIntelligence: false,
    wifi: "Wi-Fi 6",
  },
  {
    id: "iphone-14-pro-max",
    name: "iPhone 14 Pro Max",
    family: 14,
    tier: "Pro Max",
    year: 2022,
    displayInches: 6.7,
    resolution: "2796×1290",
    ppi: 460,
    refreshHz: 120,
    chip: "A16 Bionic",
    rearCameras: ["48MP", "12MP Ultra Wide", "12MP 3× Tele"],
    batteryVideoHours: 29,
    weightGrams: 240,
    storage: ["128GB", "256GB", "512GB", "1TB"],
    basePriceKes: 124999,
    frame: "Stainless steel",
    glass: "Ceramic Shield",
    waterResistance: "IP68 (6 m for 30 min)",
    port: "Lightning",
    magsafe: true,
    cutout: "Dynamic Island",
    tagline: "Always-On. 48MP Pro camera.",
    defaultColour: "deeppurple",
    cellular: "5G",
    frontCamera: "12MP TrueDepth",
    faceId: true,
    cameraControl: false,
    actionButton: false,
    crashDetection: true,
    appleIntelligence: false,
    wifi: "Wi-Fi 6",
  },
  {
    id: "iphone-14-pro",
    name: "iPhone 14 Pro",
    family: 14,
    tier: "Pro",
    year: 2022,
    displayInches: 6.1,
    resolution: "2556×1179",
    ppi: 460,
    refreshHz: 120,
    chip: "A16 Bionic",
    rearCameras: ["48MP", "12MP Ultra Wide", "12MP 3× Tele"],
    batteryVideoHours: 23,
    weightGrams: 206,
    storage: ["128GB", "256GB", "512GB", "1TB"],
    basePriceKes: 114999,
    frame: "Stainless steel",
    glass: "Ceramic Shield",
    waterResistance: "IP68 (6 m for 30 min)",
    port: "Lightning",
    magsafe: true,
    cutout: "Dynamic Island",
    tagline: "Dynamic Island arrives.",
    defaultColour: "deeppurple",
    cellular: "5G",
    frontCamera: "12MP TrueDepth",
    faceId: true,
    cameraControl: false,
    actionButton: false,
    crashDetection: true,
    appleIntelligence: false,
    wifi: "Wi-Fi 6",
  },
  {
    id: "iphone-14-plus",
    name: "iPhone 14 Plus",
    family: 14,
    tier: "Plus",
    year: 2022,
    displayInches: 6.7,
    resolution: "2778×1284",
    ppi: 458,
    refreshHz: 60,
    chip: "A15 Bionic",
    rearCameras: ["12MP", "12MP Ultra Wide"],
    batteryVideoHours: 26,
    weightGrams: 203,
    storage: ["128GB", "256GB", "512GB"],
    basePriceKes: 89999,
    frame: "Aluminium",
    glass: "Ceramic Shield",
    waterResistance: "IP68 (6 m for 30 min)",
    port: "Lightning",
    magsafe: true,
    cutout: "Notch",
    tagline: "Big battery. Big display.",
    defaultColour: "blue",
    cellular: "5G",
    frontCamera: "12MP TrueDepth",
    faceId: true,
    cameraControl: false,
    actionButton: false,
    crashDetection: true,
    appleIntelligence: false,
    wifi: "Wi-Fi 6",
  },
  {
    id: "iphone-14",
    name: "iPhone 14",
    family: 14,
    tier: "Standard",
    year: 2022,
    displayInches: 6.1,
    resolution: "2532×1170",
    ppi: 460,
    refreshHz: 60,
    chip: "A15 Bionic",
    rearCameras: ["12MP", "12MP Ultra Wide"],
    batteryVideoHours: 20,
    weightGrams: 172,
    storage: ["128GB", "256GB", "512GB"],
    basePriceKes: 79999,
    frame: "Aluminium",
    glass: "Ceramic Shield",
    waterResistance: "IP68 (6 m for 30 min)",
    port: "Lightning",
    magsafe: true,
    cutout: "Notch",
    tagline: "Crash Detection. Solid dual camera.",
    defaultColour: "midnight",
    cellular: "5G",
    frontCamera: "12MP TrueDepth",
    faceId: true,
    cameraControl: false,
    actionButton: false,
    crashDetection: true,
    appleIntelligence: false,
    wifi: "Wi-Fi 6",
  },
  {
    id: "iphone-13-pro-max",
    name: "iPhone 13 Pro Max",
    family: 13,
    tier: "Pro Max",
    year: 2021,
    displayInches: 6.7,
    resolution: "2778×1284",
    ppi: 458,
    refreshHz: 120,
    chip: "A15 Bionic",
    rearCameras: ["12MP Wide", "12MP Ultra Wide", "12MP 3× Tele", "LiDAR"],
    batteryVideoHours: 28,
    weightGrams: 238,
    storage: ["128GB", "256GB", "512GB", "1TB"],
    basePriceKes: 104999,
    frame: "Stainless steel",
    glass: "Ceramic Shield",
    waterResistance: "IP68 (6 m for 30 min)",
    port: "Lightning",
    magsafe: true,
    cutout: "Notch",
    tagline: "ProMotion. Pro camera system.",
    defaultColour: "gold",
    note: "Sierra Blue also shipped; image not in pack (text only).",
    cellular: "5G",
    frontCamera: "12MP TrueDepth",
    faceId: true,
    cameraControl: false,
    actionButton: false,
    crashDetection: false,
    appleIntelligence: false,
    wifi: "Wi-Fi 6",
  },
  {
    id: "iphone-13-pro",
    name: "iPhone 13 Pro",
    family: 13,
    tier: "Pro",
    year: 2021,
    displayInches: 6.1,
    resolution: "2532×1170",
    ppi: 460,
    refreshHz: 120,
    chip: "A15 Bionic",
    rearCameras: ["12MP Wide", "12MP Ultra Wide", "12MP 3× Tele", "LiDAR"],
    batteryVideoHours: 22,
    weightGrams: 204,
    storage: ["128GB", "256GB", "512GB", "1TB"],
    basePriceKes: 94999,
    frame: "Stainless steel",
    glass: "Ceramic Shield",
    waterResistance: "IP68 (6 m for 30 min)",
    port: "Lightning",
    magsafe: true,
    cutout: "Notch",
    tagline: "Pro cameras. ProMotion display.",
    defaultColour: "gold",
    note: "Sierra Blue also shipped; image not in pack (text only).",
    cellular: "5G",
    frontCamera: "12MP TrueDepth",
    faceId: true,
    cameraControl: false,
    actionButton: false,
    crashDetection: false,
    appleIntelligence: false,
    wifi: "Wi-Fi 6",
  },
  {
    id: "iphone-13",
    name: "iPhone 13",
    family: 13,
    tier: "Standard",
    year: 2021,
    displayInches: 6.1,
    resolution: "2532×1170",
    ppi: 460,
    refreshHz: 60,
    chip: "A15 Bionic",
    rearCameras: ["12MP Wide", "12MP Ultra Wide"],
    batteryVideoHours: 19,
    weightGrams: 174,
    storage: ["128GB", "256GB", "512GB"],
    basePriceKes: 69999,
    frame: "Aluminium",
    glass: "Ceramic Shield",
    waterResistance: "IP68 (6 m for 30 min)",
    port: "Lightning",
    magsafe: true,
    cutout: "Notch",
    tagline: "A15. Dual camera. Everyday favourite.",
    defaultColour: "pink",
    cellular: "5G",
    frontCamera: "12MP TrueDepth",
    faceId: true,
    cameraControl: false,
    actionButton: false,
    crashDetection: false,
    appleIntelligence: false,
    wifi: "Wi-Fi 6",
  },
  {
    id: "iphone-13-mini",
    name: "iPhone 13 mini",
    family: 13,
    tier: "mini",
    year: 2021,
    displayInches: 5.4,
    resolution: "2340×1080",
    ppi: 476,
    refreshHz: 60,
    chip: "A15 Bionic",
    rearCameras: ["12MP Wide", "12MP Ultra Wide"],
    batteryVideoHours: 17,
    weightGrams: 141,
    storage: ["128GB", "256GB", "512GB"],
    basePriceKes: 64999,
    frame: "Aluminium",
    glass: "Ceramic Shield",
    waterResistance: "IP68 (6 m for 30 min)",
    port: "Lightning",
    magsafe: true,
    cutout: "Notch",
    tagline: "Full power. Pocket size.",
    defaultColour: "blue",
    cellular: "5G",
    frontCamera: "12MP TrueDepth",
    faceId: true,
    cameraControl: false,
    actionButton: false,
    crashDetection: false,
    appleIntelligence: false,
    wifi: "Wi-Fi 6",
  },
  {
    id: "iphone-12-pro-max",
    name: "iPhone 12 Pro Max",
    family: 12,
    tier: "Pro Max",
    year: 2020,
    displayInches: 6.7,
    resolution: "2778×1284",
    ppi: 458,
    refreshHz: 60,
    chip: "A14 Bionic",
    rearCameras: ["12MP Wide", "12MP Ultra Wide", "12MP 2.5× Tele", "LiDAR"],
    batteryVideoHours: 20,
    weightGrams: 228,
    storage: ["128GB", "256GB", "512GB"],
    basePriceKes: 84999,
    frame: "Stainless steel",
    glass: "Ceramic Shield",
    waterResistance: "IP68 (6 m for 30 min)",
    port: "Lightning",
    magsafe: true,
    cutout: "Notch",
    tagline: "Pro camera system. 5G.",
    defaultColour: null,
    note: "Overview image only. Full angle set coming soon.",
    cellular: "5G",
    frontCamera: "12MP TrueDepth",
    faceId: true,
    cameraControl: false,
    actionButton: false,
    crashDetection: false,
    appleIntelligence: false,
    wifi: "Wi-Fi 6",
  },
  {
    id: "iphone-12-pro",
    name: "iPhone 12 Pro",
    family: 12,
    tier: "Pro",
    year: 2020,
    displayInches: 6.1,
    resolution: "2532×1170",
    ppi: 460,
    refreshHz: 60,
    chip: "A14 Bionic",
    rearCameras: ["12MP Wide", "12MP Ultra Wide", "12MP 2× Tele", "LiDAR"],
    batteryVideoHours: 17,
    weightGrams: 189,
    storage: ["128GB", "256GB", "512GB"],
    basePriceKes: 74999,
    frame: "Stainless steel",
    glass: "Ceramic Shield",
    waterResistance: "IP68 (6 m for 30 min)",
    port: "Lightning",
    magsafe: true,
    cutout: "Notch",
    tagline: "Pro cameras. Ceramic Shield.",
    defaultColour: null,
    note: "Overview image only. Full angle set coming soon.",
    cellular: "5G",
    frontCamera: "12MP TrueDepth",
    faceId: true,
    cameraControl: false,
    actionButton: false,
    crashDetection: false,
    appleIntelligence: false,
    wifi: "Wi-Fi 6",
  },
  {
    id: "iphone-12",
    name: "iPhone 12",
    family: 12,
    tier: "Standard",
    year: 2020,
    displayInches: 6.1,
    resolution: "2532×1170",
    ppi: 460,
    refreshHz: 60,
    chip: "A14 Bionic",
    rearCameras: ["12MP Wide", "12MP Ultra Wide"],
    batteryVideoHours: 17,
    weightGrams: 164,
    storage: ["64GB", "128GB", "256GB"],
    basePriceKes: 56999,
    frame: "Aluminium",
    glass: "Ceramic Shield",
    waterResistance: "IP68 (6 m for 30 min)",
    port: "Lightning",
    magsafe: true,
    cutout: "Notch",
    tagline: "5G. Dual camera. Square edges.",
    defaultColour: "blue",
    cellular: "5G",
    frontCamera: "12MP TrueDepth",
    faceId: true,
    cameraControl: false,
    actionButton: false,
    crashDetection: false,
    appleIntelligence: false,
    wifi: "Wi-Fi 6",
  },
  {
    id: "iphone-12-mini",
    name: "iPhone 12 mini",
    family: 12,
    tier: "mini",
    year: 2020,
    displayInches: 5.4,
    resolution: "2340×1080",
    ppi: 476,
    refreshHz: 60,
    chip: "A14 Bionic",
    rearCameras: ["12MP Wide", "12MP Ultra Wide"],
    batteryVideoHours: 15,
    weightGrams: 135,
    storage: ["64GB", "128GB", "256GB"],
    basePriceKes: 49999,
    frame: "Aluminium",
    glass: "Ceramic Shield",
    waterResistance: "IP68 (6 m for 30 min)",
    port: "Lightning",
    magsafe: true,
    cutout: "Notch",
    tagline: "Smallest 5G iPhone.",
    defaultColour: "purple",
    cellular: "5G",
    frontCamera: "12MP TrueDepth",
    faceId: true,
    cameraControl: false,
    actionButton: false,
    crashDetection: false,
    appleIntelligence: false,
    wifi: "Wi-Fi 6",
  },
  {
    id: "iphone-11-pro-max",
    name: "iPhone 11 Pro Max",
    family: 11,
    tier: "Pro Max",
    year: 2019,
    displayInches: 6.5,
    resolution: "2688×1242",
    ppi: 458,
    refreshHz: 60,
    chip: "A13 Bionic",
    rearCameras: ["12MP Wide", "12MP Ultra Wide", "12MP 2× Tele"],
    batteryVideoHours: 20,
    weightGrams: 226,
    storage: ["64GB", "256GB", "512GB"],
    basePriceKes: 59999,
    frame: "Stainless steel",
    glass: "Glass",
    waterResistance: "IP68 (4 m for 30 min)",
    port: "Lightning",
    magsafe: false,
    cutout: "Notch",
    tagline: "Triple camera. Long battery.",
    defaultColour: "midnight-green",
    cellular: "LTE",
    frontCamera: "12MP TrueDepth",
    faceId: true,
    cameraControl: false,
    actionButton: false,
    crashDetection: false,
    appleIntelligence: false,
    wifi: "Wi-Fi 6",
  },
  {
    id: "iphone-11-pro",
    name: "iPhone 11 Pro",
    family: 11,
    tier: "Pro",
    year: 2019,
    displayInches: 5.8,
    resolution: "2436×1125",
    ppi: 458,
    refreshHz: 60,
    chip: "A13 Bionic",
    rearCameras: ["12MP Wide", "12MP Ultra Wide", "12MP 2× Tele"],
    batteryVideoHours: 18,
    weightGrams: 188,
    storage: ["64GB", "256GB", "512GB"],
    basePriceKes: 54999,
    frame: "Stainless steel",
    glass: "Glass",
    waterResistance: "IP68 (4 m for 30 min)",
    port: "Lightning",
    magsafe: false,
    cutout: "Notch",
    tagline: "Triple camera. Compact Pro.",
    defaultColour: "midnight-green",
    cellular: "LTE",
    frontCamera: "12MP TrueDepth",
    faceId: true,
    cameraControl: false,
    actionButton: false,
    crashDetection: false,
    appleIntelligence: false,
    wifi: "Wi-Fi 6",
  },
  {
    id: "iphone-11",
    name: "iPhone 11",
    family: 11,
    tier: "Standard",
    year: 2019,
    displayInches: 6.1,
    resolution: "1792×828",
    ppi: 326,
    refreshHz: 60,
    chip: "A13 Bionic",
    rearCameras: ["12MP Wide", "12MP Ultra Wide"],
    batteryVideoHours: 17,
    weightGrams: 194,
    storage: ["64GB", "128GB", "256GB"],
    basePriceKes: 44999,
    frame: "Aluminium",
    glass: "Glass",
    waterResistance: "IP68 (2 m for 30 min)",
    port: "Lightning",
    magsafe: false,
    cutout: "Notch",
    tagline: "Dual camera. Liquid Retina LCD.",
    defaultColour: null,
    note: "Overview image only. Full angle set coming soon. LCD Liquid Retina display.",
    cellular: "LTE",
    frontCamera: "12MP TrueDepth",
    faceId: true,
    cameraControl: false,
    actionButton: false,
    crashDetection: false,
    appleIntelligence: false,
    wifi: "Wi-Fi 6",
    displayNote: "LCD Liquid Retina",
  },
];

export function getModel(id: string): IphoneModel | undefined {
  return models.find((m) => m.id === id);
}

export function modelsByFamily(family: IphoneModel["family"]): IphoneModel[] {
  return models.filter((m) => m.family === family);
}

export function modelSubline(m: IphoneModel): string {
  const cams = m.rearCameras.length;
  return `${m.displayInches}″ · ${m.chip} · ${cams} camera${cams === 1 ? "" : "s"}`;
}

export function isLatestTag(m: IphoneModel): boolean {
  return m.family === 16 && m.tier !== "e";
}

export function isValueTag(m: IphoneModel): boolean {
  return m.id === "iphone-16e";
}
