import type { HeroCategory } from "./types";

const IP = "/Hero/Gadget_Hub_Hero_Video_iPhone_part1of2/01_Cinematic_black_background_JPG";
const IP_CUT = "/Hero/Gadget_Hub_Hero_Video_iPhone_part2of2/02_Transparent_PNG_cutouts";
const MB = "/Hero/Gadget_Hub_Hero_Video_MacBook/01_Cinematic_black_background_JPG";
const MB_CUT = "/Hero/Gadget_Hub_Hero_Video_MacBook/02_Transparent_PNG_cutouts";
const PD = "/Hero/Gadget_Hub_Hero_Video_iPad/01_Cinematic_black_background_JPG";
const PD_CUT = "/Hero/Gadget_Hub_Hero_Video_iPad/02_Transparent_PNG_cutouts";
const WA = "/Hero/Gadget_Hub_Hero_Video_Watch/01_Cinematic_black_background_JPG";
const AP = "/Hero/Gadget_Hub_Hero_Video_AirPods/01_Cinematic_black_background_JPG";
const AP_CUT = "/Hero/Gadget_Hub_Hero_Video_AirPods/02_Transparent_PNG_cutouts";
const TV = "/Hero/Gadget_Hub_Hero_Video_TV_and_Home/01_Cinematic_black_background_JPG";
const TV_CUT = "/Hero/Gadget_Hub_Hero_Video_TV_and_Home/02_Transparent_PNG_cutouts";
const AX_CUT = "/Hero/Gadget_Hub_Hero_Video_Accessories/02_Transparent_PNG_cutouts";

const focusCinematic = { x: 62, y: 50 };
const focusCutout = { x: 66, y: 46 };

export const heroCategories: Record<string, HeroCategory> = {
  iphone: {
    slug: "iphone",
    displayName: "iPhone",
    eyebrow: "IPHONE",
    shopHref: "/iphone",
    shopLabel: "Shop iPhone",
    whatsappMessage: "Hi Gadget Hub, I am interested in iPhone.",
    scenes: [
      {
        id: "iphone-1",
        src: `${IP}/C01_iPhone_18_Pro_camera_hero.jpg`,
        type: "cinematic",
        title: "iPhone 18 Pro",
        subtitle: "The Pro camera system",
        motion: "push-in",
        focus: focusCinematic,
        alt: "iPhone 18 Pro camera system on black",
      },
      {
        id: "iphone-2",
        src: `${IP}/C07_iPhone_18_Pro_all_four_colours.jpg`,
        type: "cinematic",
        title: "Four finishes",
        subtitle: "Black, Burgundy, Glacier, Silver",
        motion: "pan",
        focus: focusCinematic,
        alt: "iPhone 18 Pro in four finishes on black",
      },
      {
        id: "iphone-3",
        src: `${IP_CUT}/P06_iPhone_Duo_Night_Sky_open.png`,
        type: "cutout",
        title: "iPhone Duo",
        subtitle: "Open it out",
        motion: "rise",
        focus: focusCutout,
        alt: "iPhone Duo in Night Sky open on black",
      },
      {
        id: "iphone-4",
        src: `${IP}/C09_Camera_lens_macro.jpg`,
        type: "cinematic",
        title: "Every detail",
        subtitle: "Up close",
        motion: "zoom-out",
        focus: focusCinematic,
        alt: "iPhone camera lens macro on black",
      },
    ],
  },
  macbook: {
    slug: "macbook",
    displayName: "MacBook",
    eyebrow: "MACBOOK",
    shopHref: "/mac",
    shopLabel: "Shop MacBook",
    whatsappMessage: "Hi Gadget Hub, I am interested in MacBook.",
    scenes: [
      {
        id: "macbook-1",
        src: `${MB}/C01_MacBook_Pro_open_hero.jpg`,
        type: "cinematic",
        title: "MacBook Pro",
        subtitle: "Opens up",
        motion: "push-in",
        focus: focusCinematic,
        alt: "MacBook Pro open on black",
      },
      {
        id: "macbook-2",
        src: `${MB_CUT}/P01_MacBook_Air_13_Midnight.png`,
        type: "cutout",
        title: "MacBook Air",
        subtitle: "Midnight",
        motion: "slide-right",
        focus: focusCutout,
        alt: "MacBook Air 13-inch Midnight cutout",
      },
      {
        id: "macbook-3",
        src: `${MB}/C03_MacBook_Pro_two_sizes.jpg`,
        type: "cinematic",
        title: "Two sizes",
        subtitle: "14 inch and 16 inch",
        motion: "push-in",
        focus: focusCinematic,
        alt: "MacBook Pro 14-inch and 16-inch on black",
      },
      {
        id: "macbook-4",
        src: `${MB}/C06_Display_colour_hero.jpg`,
        type: "cinematic",
        title: "The display",
        subtitle: "Colour that fills the screen",
        motion: "zoom-out",
        focus: focusCinematic,
        alt: "MacBook display colour hero on black",
      },
    ],
  },
  ipad: {
    slug: "ipad",
    displayName: "iPad",
    eyebrow: "IPAD",
    shopHref: "/ipad",
    shopLabel: "Shop iPad",
    whatsappMessage: "Hi Gadget Hub, I am interested in iPad.",
    scenes: [
      {
        id: "ipad-1",
        src: `${PD}/C01_iPad_Pro_side_glow.jpg`,
        type: "cinematic",
        title: "iPad Pro",
        subtitle: "Thin. Bright. Fast.",
        motion: "push-in",
        focus: focusCinematic,
        alt: "iPad Pro side glow on black",
      },
      {
        id: "ipad-2",
        src: `${PD_CUT}/P01_iPad_Air_Blue.png`,
        type: "cutout",
        title: "iPad Air",
        subtitle: "Blue",
        motion: "rise-tilt",
        focus: focusCutout,
        tiltDeg: 2,
        alt: "iPad Air in Blue cutout",
      },
      {
        id: "ipad-3",
        src: `${PD}/C02_iPad_Pro_with_Magic_Keyboard_black.jpg`,
        type: "cinematic",
        title: "With Magic Keyboard",
        subtitle: "A laptop when you need one",
        motion: "pan",
        focus: focusCinematic,
        alt: "iPad Pro with Magic Keyboard in black on black background",
      },
      {
        id: "ipad-4",
        src: `${PD}/C06_Apple_Pencil_Pro_drawing.jpg`,
        type: "cinematic",
        title: "Apple Pencil Pro",
        subtitle: "Draw, write, create",
        motion: "zoom-out",
        focus: focusCinematic,
        alt: "Apple Pencil Pro drawing on iPad",
      },
    ],
  },
  watch: {
    slug: "watch",
    displayName: "Watch",
    eyebrow: "WATCH",
    shopHref: "/watch",
    shopLabel: "Shop Watch",
    whatsappMessage: "Hi Gadget Hub, I am interested in Apple Watch.",
    scenes: [
      {
        id: "watch-1",
        src: `${WA}/C01_Series_12_full_watch.jpg`,
        type: "cinematic",
        title: "Apple Watch Series 12",
        subtitle: "Choose your finish",
        motion: "push-in",
        focus: focusCinematic,
        alt: "Apple Watch Series 12 full watch on black",
      },
      {
        id: "watch-2",
        src: `${WA}/C09_Series_12_bands_and_faces_collection.jpg`,
        type: "cinematic",
        title: "Bands and faces",
        subtitle: "Make it yours",
        motion: "tilt",
        focus: focusCinematic,
        tiltDeg: 2,
        alt: "Apple Watch bands and faces collection",
      },
      {
        id: "watch-3",
        src: `${WA}/C05_Series_12_Titanium_Radiant_Gold.jpg`,
        type: "cinematic",
        title: "Titanium Radiant Gold",
        subtitle: "Close up",
        motion: "push-in",
        focus: focusCinematic,
        alt: "Apple Watch Series 12 Titanium Radiant Gold close up",
      },
      {
        id: "watch-4",
        src: `${WA}/C12_Ultra_Black_Titanium.jpg`,
        type: "cinematic",
        title: "Apple Watch Ultra",
        subtitle: "Built for the outdoors",
        motion: "zoom-out",
        focus: focusCinematic,
        alt: "Apple Watch Ultra Black Titanium on black",
      },
    ],
  },
  airpods: {
    slug: "airpods",
    displayName: "AirPods",
    eyebrow: "AIRPODS",
    shopHref: "/airpods",
    shopLabel: "Shop AirPods",
    whatsappMessage: "Hi Gadget Hub, I am interested in AirPods.",
    scenes: [
      {
        id: "airpods-1",
        src: `${AP_CUT}/P06_AirPods_Pro_3_with_case.png`,
        type: "cutout",
        title: "AirPods Pro 3",
        subtitle: "With charging case",
        motion: "rise",
        focus: focusCutout,
        alt: "AirPods Pro 3 with charging case cutout",
      },
      {
        id: "airpods-2",
        src: `${AP_CUT}/P07_AirPods_Max_hero.png`,
        type: "cutout",
        title: "AirPods Max",
        subtitle: "Over-ear sound",
        motion: "slide-left",
        focus: focusCutout,
        alt: "AirPods Max hero cutout",
      },
      {
        id: "airpods-3",
        src: `${AP_CUT}/P01_AirPods_Max_Blue.png`,
        type: "cutout",
        title: "Pick your colour",
        subtitle: "Blue",
        motion: "colour-swap",
        focus: focusCutout,
        alt: "AirPods Max colour options",
        swap: [
          `${AP_CUT}/P01_AirPods_Max_Blue.png`,
          `${AP_CUT}/P02_AirPods_Max_Midnight.png`,
          `${AP_CUT}/P03_AirPods_Max_Orange.png`,
          `${AP_CUT}/P04_AirPods_Max_Purple.png`,
          `${AP_CUT}/P05_AirPods_Max_Starlight.png`,
        ],
      },
      {
        id: "airpods-4",
        src: `${AP}/C02_Sound_wave_glow_dark.jpg`,
        type: "cinematic",
        title: "Sound",
        subtitle: "Wrapped around you",
        motion: "push-in",
        focus: focusCinematic,
        alt: "AirPods sound wave glow on black",
      },
    ],
  },
  "tv-home": {
    slug: "tv-home",
    displayName: "TV and Home",
    eyebrow: "TV AND HOME",
    shopHref: "/tv-home",
    shopLabel: "Shop TV and Home",
    whatsappMessage: "Hi Gadget Hub, I am interested in TV and Home.",
    scenes: [
      {
        id: "tv-home-1",
        src: `${TV}/C01_HomePod_twins.jpg`,
        type: "cinematic",
        title: "HomePod",
        subtitle: "Midnight and White",
        motion: "push-in",
        focus: focusCinematic,
        alt: "HomePod Midnight and White on black",
      },
      {
        id: "tv-home-2",
        src: `${TV_CUT}/P04_Apple_TV_4K_and_remote.png`,
        type: "cutout",
        title: "Apple TV 4K",
        subtitle: "With Siri Remote",
        motion: "rise",
        focus: focusCutout,
        alt: "Apple TV 4K and Siri Remote cutout",
      },
      {
        id: "tv-home-3",
        src: `${TV}/C03_Home_theatre_Apple_TV_and_HomePods.jpg`,
        type: "cinematic",
        title: "Home theatre",
        subtitle: "Apple TV and HomePods together",
        motion: "push-in",
        focus: focusCinematic,
        alt: "Apple TV and HomePods home theatre setup",
      },
      {
        id: "tv-home-4",
        src: `${TV}/C02_HomePod_handoff_from_iPhone.jpg`,
        type: "cinematic",
        title: "Handoff",
        subtitle: "Music from your iPhone to HomePod",
        motion: "zoom-out",
        focus: focusCinematic,
        alt: "HomePod handoff from iPhone",
      },
    ],
  },
  accessories: {
    slug: "accessories",
    displayName: "Accessories",
    eyebrow: "ACCESSORIES",
    shopHref: "/accessories",
    shopLabel: "Shop Accessories",
    whatsappMessage: "Hi Gadget Hub, I am interested in Accessories.",
    scenes: [
      {
        id: "accessories-1",
        src: `${AX_CUT}/P01_MagSafe_Clear_Case_iPhone_18_Pro_Burgundy.png`,
        type: "cutout",
        title: "MagSafe Cases",
        subtitle: "iPhone 18 Pro",
        motion: "rise-tilt",
        focus: focusCutout,
        tiltDeg: 2,
        alt: "MagSafe clear case for iPhone 18 Pro in Burgundy",
      },
      {
        id: "accessories-2",
        src: `${AX_CUT}/P04_MagSafe_Charger_front.png`,
        type: "cutout",
        title: "MagSafe Charger",
        subtitle: "Snap on, charge",
        motion: "rise-from-below",
        focus: focusCutout,
        alt: "MagSafe Charger front cutout",
      },
      {
        id: "accessories-3",
        src: `${AX_CUT}/P07_35W_Dual_USB-C_Power_Adapter_angle.png`,
        type: "cutout",
        title: "Power adapters",
        subtitle: "35W Dual USB-C",
        motion: "tilt-8",
        focus: focusCutout,
        tiltDeg: 8,
        alt: "35W Dual USB-C Power Adapter",
      },
      {
        id: "accessories-4",
        src: `${AX_CUT}/P11_Apple_Pencil_Pro_upright.png`,
        type: "cutout",
        title: "Apple Pencil Pro",
        subtitle: "Draw, write, create",
        motion: "drift-down",
        focus: focusCutout,
        alt: "Apple Pencil Pro upright cutout",
      },
    ],
  },
};

export function getHeroCategory(slug: string): HeroCategory {
  const cat = heroCategories[slug];
  if (!cat) throw new Error(`[hero] Unknown category slug: ${slug}`);
  return cat;
}
