/**
 * AirPods catalog (2 - 5, Pro 1 - 3, Max 2020/USB-C/Max 2).
 * Specs from Apple's published compare page (apple.com/airpods/compare).
 * re-verify every figure before launch. Store null where unclear -
 * show nothing rather than guess. Groups marked checkFinalSpecs.
 */

import { airpodsBasePricesKes } from "./config";

export type AirpodsFamily = "AirPods" | "Pro" | "Max";
export type NoiseControl = "none" | "anc" | "adaptive" | "transparency";
export type CaseType = "lightning" | "usb-c" | "wireless" | "magsafe";

export type AirpodsModel = {
  id: keyof typeof airpodsBasePricesKes;
  name: string;
  family: AirpodsFamily;
  generation: string;
  year: number;
  type: "in-ear" | "over-ear";
  chip: string | null;
  noiseModes: NoiseControl[];
  spatialAudio: boolean | null;
  lossless: boolean | null;
  hearingTest: boolean | null;
  hearingAid: boolean | null;
  hearingProtection: boolean | null;
  heartRate: boolean | null;
  liveTranslation: boolean | null;
  conversationAwareness: boolean | null;
  touchControl: string | null;
  batterySingleHours: number | null;
  batteryWithCaseHours: number | null;
  caseTypes: CaseType[];
  caseOptions: ("usb-c" | "wireless")[];
  waterRating: string | null;
  mics: number | null;
  weightG: number | null;
  colours: string[];
  defaultColour: string;
  tagline: string;
  whoItSuits: string;
  whyChoose: [string, string, string];
  basePriceKes: number;
  isNew?: boolean;
  standInImage?: boolean;
  textOnlyColours?: boolean;
  checkFinalSpecs?: boolean;
  notes: string;
  pageFamily: "Pro" | "AirPods5" | "Max" | "Landing";
};

function m(
  partial: Omit<AirpodsModel, "basePriceKes"> & { id: keyof typeof airpodsBasePricesKes },
): AirpodsModel {
  return { ...partial, basePriceKes: airpodsBasePricesKes[partial.id] };
}

export const airpodsModels: AirpodsModel[] = [
  m({
    id: "airpods-pro-3",
    name: "AirPods Pro 3",
    family: "Pro",
    generation: "Pro 3",
    year: 2025,
    type: "in-ear",
    chip: "H2",
    noiseModes: ["none", "transparency", "adaptive", "anc"],
    spatialAudio: true,
    lossless: true,
    hearingTest: true,
    hearingAid: true,
    hearingProtection: true,
    heartRate: true,
    liveTranslation: true,
    conversationAwareness: true,
    touchControl: "Force sensor with volume swipe",
    batterySingleHours: null,
    batteryWithCaseHours: null,
    caseTypes: ["magsafe", "usb-c"],
    caseOptions: ["usb-c"],
    waterRating: "IP57",
    mics: null,
    weightG: 5.5,
    colours: ["white"],
    defaultColour: "white",
    tagline: "The quietest Pro yet - plus hearing care.",
    whoItSuits: "Commuters, travellers and anyone who wants the strongest in-ear ANC.",
    whyChoose: [
      "Strongest noise cancelling in the in-ear range - Apple's claim; check ratio in CONFIG.",
      "Hearing Test, Hearing Aid and Hearing Protection where available.",
      "Heart-rate sensing in workouts and MagSafe USB-C case with Precision Finding.",
    ],
    isNew: true,
    checkFinalSpecs: true,
    notes: "Hearing features - confirm Kenya availability. Battery hours check.",
    pageFamily: "Pro",
  }),
  m({
    id: "airpods-5",
    name: "AirPods 5",
    family: "AirPods",
    generation: "5",
    year: 2026,
    type: "in-ear",
    chip: "H2",
    noiseModes: ["none", "transparency", "adaptive"],
    spatialAudio: true,
    lossless: null,
    hearingTest: null,
    hearingAid: null,
    hearingProtection: null,
    heartRate: false,
    liveTranslation: null,
    conversationAwareness: true,
    touchControl: "Force sensor with volume swipe",
    batterySingleHours: null,
    batteryWithCaseHours: null,
    caseTypes: ["usb-c"],
    caseOptions: ["usb-c"],
    waterRating: null,
    mics: null,
    weightG: null,
    colours: ["white"],
    defaultColour: "white",
    tagline: "Open-fit AirPods with Adaptive Audio.",
    whoItSuits: "Everyday calls, music and people who prefer open tips.",
    whyChoose: [
      "H2 chip and Adaptive Audio without silicone tips.",
      "USB-C charging case - wireless case sold as a separate SKU.",
      "Newest standard AirPods - check battery and IP figures.",
    ],
    isNew: true,
    checkFinalSpecs: true,
    notes: "Confirm which Adaptive/Lossless claims apply. Battery check.",
    pageFamily: "AirPods5",
  }),
  m({
    id: "airpods-5-wireless",
    name: "AirPods 5 with Wireless Charging Case",
    family: "AirPods",
    generation: "5",
    year: 2026,
    type: "in-ear",
    chip: "H2",
    noiseModes: ["none", "transparency", "adaptive"],
    spatialAudio: true,
    lossless: null,
    hearingTest: null,
    hearingAid: null,
    hearingProtection: null,
    heartRate: false,
    liveTranslation: null,
    conversationAwareness: true,
    touchControl: "Force sensor with volume swipe",
    batterySingleHours: null,
    batteryWithCaseHours: null,
    caseTypes: ["usb-c", "wireless"],
    caseOptions: ["wireless"],
    waterRating: null,
    mics: null,
    weightG: null,
    colours: ["white"],
    defaultColour: "white",
    tagline: "AirPods 5 plus wireless charging.",
    whoItSuits: "Buyers who want a Qi / MagSafe-style drop charge.",
    whyChoose: [
      "Same earbuds as AirPods 5 with a wireless case.",
      "Sample price includes the wireless case step.",
      "Check charger compatibility before launch.",
    ],
    isNew: true,
    checkFinalSpecs: true,
    notes: "Wireless case SKU.",
    pageFamily: "AirPods5",
  }),
  m({
    id: "airpods-max-2",
    name: "AirPods Max 2",
    family: "Max",
    generation: "Max 2",
    year: 2025,
    type: "over-ear",
    chip: "H2",
    noiseModes: ["none", "transparency", "anc"],
    spatialAudio: true,
    lossless: null,
    hearingTest: null,
    hearingAid: null,
    hearingProtection: null,
    heartRate: false,
    liveTranslation: null,
    conversationAwareness: null,
    touchControl: "Digital Crown and noise control button",
    batterySingleHours: null,
    batteryWithCaseHours: null,
    caseTypes: ["usb-c"],
    caseOptions: ["usb-c"],
    waterRating: null,
    mics: 9,
    weightG: 386,
    colours: ["midnight", "blue", "orange", "purple", "starlight"],
    defaultColour: "midnight",
    tagline: "Over-ear quiet. Studio-class comfort.",
    whoItSuits: "Music lovers and long flights who prefer over-ear.",
    whyChoose: [
      "Over-ear ANC with Digital Crown volume.",
      "Five colours on the current Max design.",
      "About 386 g - check chip and mic count.",
    ],
    isNew: true,
    checkFinalSpecs: true,
    notes: "Confirm Max 2 vs USB-C 2024 naming against Apple's page.",
    pageFamily: "Max",
  }),
  m({
    id: "airpods-max-usbc",
    name: "AirPods Max (USB-C)",
    family: "Max",
    generation: "Max USB-C",
    year: 2024,
    type: "over-ear",
    chip: "H1",
    noiseModes: ["none", "transparency", "anc"],
    spatialAudio: true,
    lossless: null,
    hearingTest: false,
    hearingAid: false,
    hearingProtection: false,
    heartRate: false,
    liveTranslation: false,
    conversationAwareness: false,
    touchControl: "Digital Crown and noise control button",
    batterySingleHours: null,
    batteryWithCaseHours: null,
    caseTypes: ["usb-c"],
    caseOptions: ["usb-c"],
    waterRating: null,
    mics: 9,
    weightG: 386,
    colours: ["midnight", "blue", "orange", "purple", "starlight"],
    defaultColour: "midnight",
    tagline: "USB-C Max - five fresh colours.",
    whoItSuits: "Over-ear buyers who want the 2024 USB-C redesign.",
    whyChoose: [
      "USB-C charging and the current colour set.",
      "Smart Case included.",
      "Store photos are this model - flag check for chip.",
    ],
    checkFinalSpecs: true,
    notes: "2024 USB-C Max photos used for Max family shots.",
    pageFamily: "Max",
  }),
  m({
    id: "airpods-4",
    name: "AirPods 4",
    family: "AirPods",
    generation: "4",
    year: 2024,
    type: "in-ear",
    chip: "H2",
    noiseModes: ["none"],
    spatialAudio: true,
    lossless: false,
    hearingTest: false,
    hearingAid: false,
    hearingProtection: false,
    heartRate: false,
    liveTranslation: false,
    conversationAwareness: false,
    touchControl: "Force sensor",
    batterySingleHours: null,
    batteryWithCaseHours: null,
    caseTypes: ["usb-c"],
    caseOptions: ["usb-c"],
    waterRating: "IP54",
    mics: null,
    weightG: null,
    colours: ["white"],
    defaultColour: "white",
    tagline: "Open-fit AirPods. Simple price.",
    whoItSuits: "Budget everyday listening without ANC.",
    whyChoose: [
      "H2 chip at a lower sample price than ANC models.",
      "USB-C case.",
      "No Active Noise Cancellation on this SKU.",
    ],
    checkFinalSpecs: true,
    notes: "Also in stock / previous gen.",
    pageFamily: "Landing",
  }),
  m({
    id: "airpods-4-anc",
    name: "AirPods 4 with Active Noise Cancellation",
    family: "AirPods",
    generation: "4 ANC",
    year: 2024,
    type: "in-ear",
    chip: "H2",
    noiseModes: ["none", "transparency", "anc"],
    spatialAudio: true,
    lossless: false,
    hearingTest: false,
    hearingAid: false,
    hearingProtection: false,
    heartRate: false,
    liveTranslation: false,
    conversationAwareness: true,
    touchControl: "Force sensor",
    batterySingleHours: null,
    batteryWithCaseHours: null,
    caseTypes: ["usb-c", "wireless"],
    caseOptions: ["usb-c", "wireless"],
    waterRating: "IP54",
    mics: null,
    weightG: null,
    colours: ["white"],
    defaultColour: "white",
    tagline: "AirPods 4 with ANC when you need quiet.",
    whoItSuits: "Open-fit buyers who still want noise cancelling.",
    whyChoose: [
      "ANC without silicone tips.",
      "Wireless charging case option.",
      "Check battery figures before launch.",
    ],
    checkFinalSpecs: true,
    notes: "ANC version of AirPods 4.",
    pageFamily: "Landing",
  }),
  m({
    id: "airpods-pro-2",
    name: "AirPods Pro 2",
    family: "Pro",
    generation: "Pro 2",
    year: 2024,
    type: "in-ear",
    chip: "H2",
    noiseModes: ["none", "transparency", "adaptive", "anc"],
    spatialAudio: true,
    lossless: null,
    hearingTest: null,
    hearingAid: null,
    hearingProtection: null,
    heartRate: false,
    liveTranslation: false,
    conversationAwareness: true,
    touchControl: "Force sensor with volume swipe",
    batterySingleHours: null,
    batteryWithCaseHours: null,
    caseTypes: ["magsafe", "usb-c"],
    caseOptions: ["usb-c"],
    waterRating: "IP54",
    mics: null,
    weightG: null,
    colours: ["white"],
    defaultColour: "white",
    tagline: "Pro ANC - still a strong buy.",
    whoItSuits: "People who want Pro tips and ANC without Pro 3 pricing.",
    whyChoose: [
      "Pro-level ANC and Adaptive Audio.",
      "MagSafe USB-C case.",
      "2024 store shots - 'Image shows the current design' for older Pro 2 packs.",
    ],
    standInImage: true,
    checkFinalSpecs: true,
    notes: "2022/2023 Pro 2 packs use 2024 shots as stand-ins.",
    pageFamily: "Pro",
  }),
  m({
    id: "airpods-3",
    name: "AirPods (3rd generation)",
    family: "AirPods",
    generation: "3",
    year: 2021,
    type: "in-ear",
    chip: "H1",
    noiseModes: ["none"],
    spatialAudio: true,
    lossless: false,
    hearingTest: false,
    hearingAid: false,
    hearingProtection: false,
    heartRate: false,
    liveTranslation: false,
    conversationAwareness: false,
    touchControl: "Force sensor",
    batterySingleHours: null,
    batteryWithCaseHours: null,
    caseTypes: ["lightning", "magsafe"],
    caseOptions: ["usb-c"],
    waterRating: "IPX4",
    mics: null,
    weightG: null,
    colours: ["white"],
    defaultColour: "white",
    tagline: "Also in stock - check condition.",
    whoItSuits: "Tight budgets who accept an older open-fit model.",
    whyChoose: [
      "Lower sample price.",
      "Spatial Audio on H1.",
      "No store photo - case overview and stand-in note.",
    ],
    standInImage: true,
    checkFinalSpecs: true,
    notes: "Overview/case only. Check battery health.",
    pageFamily: "Landing",
  }),
  m({
    id: "airpods-2",
    name: "AirPods (2nd generation)",
    family: "AirPods",
    generation: "2",
    year: 2019,
    type: "in-ear",
    chip: "H1",
    noiseModes: ["none"],
    spatialAudio: false,
    lossless: false,
    hearingTest: false,
    hearingAid: false,
    hearingProtection: false,
    heartRate: false,
    liveTranslation: false,
    conversationAwareness: false,
    touchControl: "Double tap",
    batterySingleHours: null,
    batteryWithCaseHours: null,
    caseTypes: ["lightning", "wireless"],
    caseOptions: ["usb-c"],
    waterRating: null,
    mics: null,
    weightG: null,
    colours: ["white"],
    defaultColour: "white",
    tagline: "Entry AirPods - check condition.",
    whoItSuits: "Lowest budget first pair.",
    whyChoose: [
      "Lowest sample price in the shop.",
      "Lightning case (wireless optional historically).",
      "No store photo - case overview only.",
    ],
    standInImage: true,
    checkFinalSpecs: true,
    notes: "Also in stock. Check condition and battery.",
    pageFamily: "Landing",
  }),
  m({
    id: "airpods-pro-1",
    name: "AirPods Pro (1st generation)",
    family: "Pro",
    generation: "Pro 1",
    year: 2019,
    type: "in-ear",
    chip: "H1",
    noiseModes: ["none", "transparency", "anc"],
    spatialAudio: true,
    lossless: false,
    hearingTest: false,
    hearingAid: false,
    hearingProtection: false,
    heartRate: false,
    liveTranslation: false,
    conversationAwareness: false,
    touchControl: "Force sensor",
    batterySingleHours: null,
    batteryWithCaseHours: null,
    caseTypes: ["lightning", "wireless", "magsafe"],
    caseOptions: ["usb-c"],
    waterRating: "IPX4",
    mics: null,
    weightG: null,
    colours: ["white"],
    defaultColour: "white",
    tagline: "Also in stock - Pro tips on a budget.",
    whoItSuits: "Buyers who want silicone tips and ANC at a lower price.",
    whyChoose: [
      "ANC with tips at a sample price below Pro 2.",
      "No store photo - case overview.",
      "Confirm battery health on the invoice.",
    ],
    standInImage: true,
    checkFinalSpecs: true,
    notes: "Show only if stock exists.",
    pageFamily: "Pro",
  }),
  m({
    id: "airpods-max-2020",
    name: "AirPods Max (2020)",
    family: "Max",
    generation: "Max Lightning",
    year: 2020,
    type: "over-ear",
    chip: "H1",
    noiseModes: ["none", "transparency", "anc"],
    spatialAudio: true,
    lossless: false,
    hearingTest: false,
    hearingAid: false,
    hearingProtection: false,
    heartRate: false,
    liveTranslation: false,
    conversationAwareness: false,
    touchControl: "Digital Crown and noise control button",
    batterySingleHours: null,
    batteryWithCaseHours: null,
    caseTypes: ["lightning"],
    caseOptions: ["usb-c"],
    waterRating: null,
    mics: 9,
    weightG: 384.8,
    colours: ["space-gray", "silver", "sky-blue", "green", "pink"],
    defaultColour: "space-gray",
    tagline: "Original Max - Lightning. Text condition.",
    whoItSuits: "Over-ear buyers watching the budget.",
    whyChoose: [
      "Lower sample price than USB-C Max.",
      "No store colour photos - text chips only.",
      "Confirm condition and battery.",
    ],
    standInImage: true,
    textOnlyColours: true,
    checkFinalSpecs: true,
    notes: "2020 colours have no image - text chips only.",
    pageFamily: "Max",
  }),
];

export function getAirpodsModel(id: string): AirpodsModel | undefined {
  return airpodsModels.find((m) => m.id === id);
}

export function airpodsModelsByFamily(family: AirpodsFamily): AirpodsModel[] {
  return airpodsModels.filter((m) => m.family === family);
}

export function lowestAirpodsPrice(family?: AirpodsFamily): number {
  const pool = family ? airpodsModelsByFamily(family) : airpodsModels;
  return Math.min(...pool.map((m) => m.basePriceKes));
}

export function airpodsSubline(model: AirpodsModel): string {
  return `${model.generation} · ${model.type} · ${model.chip || "check chip"}`;
}

export function hasAnc(model: AirpodsModel): boolean {
  return model.noiseModes.includes("anc");
}

export function hasHearing(model: AirpodsModel): boolean {
  return Boolean(model.hearingTest || model.hearingAid || model.hearingProtection);
}
